### ISSUE TITLE
An error occurs when the number of custom steps is less than the preset number of steps in performance mode and the refiner switching time is too large

### ISSUE THREAD

**Issue by xhoxye** [lllyasviel/Fooocus#1005]
**Describe the problem**
An error occurs when the number of custom steps is less than the preset number of steps in performance mode and the refiner switching time is too large

Performance: Quality 60
Refiner Switch At: 0.9
Forced Overwrite of Sampling Step: 50
60 * 0.9 = 54 > 50

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

Total time: 37.22 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 2606762822901728070
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 50 - 54
[Fooocus] Initializing ...
[Fooocus] Loading models ...
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] An asian girl, highly detailed, light glowing, amazing, delicate, elegant, intricate, sharp focus, pretty, complex, still, dynamic composition, ambient background, professional, confident, attractive, creative, expressive, beautiful, agile, new, passionate, futuristic, focused, awesome, inspired, cute, advanced, illuminated, cinematic, dramatic, glossy, color, designed
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
[Fooocus] Encoding negative #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1152, 896)
Preparation time: 1.19 seconds
[Sampler] refiner_swap_method = vae
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.99 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:30<00:00,  1.64it/s]
Fooocus VAE-based swap.
Requested to load Interposer
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.12 seconds
Requested to load BaseModel
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.42 seconds
Traceback (most recent call last):
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "E:\AI\Fooocus\Fooocus21791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\Fooocus\Fooocus21791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "E:\AI\Fooocus\Fooocus21791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\Fooocus\Fooocus21791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\modules\default_pipeline.py", line 467, in process_diffusion
    sampled_latent = core.ksampler(
  File "E:\AI\Fooocus\Fooocus21791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\Fooocus\Fooocus21791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\modules\core.py", line 315, in ksampler
    samples = fcbh.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\backend\headless\fcbh\sample.py", line 98, in sample
    sampler = fcbh.samplers.KSampler(real_model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=denoise, model_options=model.model_options)
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\backend\headless\fcbh\samplers.py", line 664, in __init__
    self.set_steps(steps, denoise)
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\backend\headless\fcbh\samplers.py", line 685, in set_steps
    self.sigmas = self.calculate_sigmas(steps).to(self.device)
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\backend\headless\fcbh\samplers.py", line 676, in calculate_sigmas
    sigmas = calculate_sigmas_scheduler(self.model, self.scheduler, steps)
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\backend\headless\fcbh\samplers.py", line 625, in calculate_sigmas_scheduler
    sigmas = k_diffusion_sampling.get_sigmas_karras(n=steps, sigma_min=float(model.model_sampling.sigma_min), sigma_max=float(model.model_sampling.sigma_max))
  File "E:\AI\Fooocus\Fooocus21791\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 18, in get_sigmas_karras    ramp = torch.linspace(0, 1, n, device=device)
RuntimeError: number of steps must be non-negative
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 34.59 seconds
[Fooocus Model Management] Moving model(s) has taken 0.58 seconds

**Comment by xhoxye** [comment]
When the number of custom steps is greater than the number of steps preset by the performance model, the timing of refiner switching is not intuitive.
Performance: Quality 30
Refiner Switch At: 0.7
Forced Overwrite of Sampling Step: 40
30 * 0.7 = 21 , Refiner Switch At 19 ?

**Comment by mashb1t** [comment]
Fixed in https://github.com/lllyasviel/Fooocus/pull/2165
