### ISSUE TITLE
Inpaint Error. FileNotFoundError: \\upscale_models\\fooocus_upscaler_s409985e5.bin'

### ISSUE THREAD

**Issue by domrique** [lllyasviel/Fooocus#1045]
I'm trying to inpaint face and error occurs

**Full Console Log**
[Fooocus] Image processing ...
Upscaling image with shape (75, 75, 3) ...
Traceback (most recent call last):
  File "D:\Neuro\Fooocus_win64_1-1-10\Fooocus\modules\patch.py", line 512, in loader
    result = original_loader(*args, **kwargs)
  File "D:\Neuro\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Neuro\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Neuro\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Neuro\\Fooocus_win64_1-1-10\\Fooocus\\models\\upscale_models\\fooocus_upscaler_s409985e5.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Neuro\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\Neuro\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Neuro\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Neuro\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 552, in handler
    inpaint_worker.current_task = inpaint_worker.InpaintWorker(
  File "D:\Neuro\Fooocus_win64_1-1-10\Fooocus\modules\inpaint_worker.py", line 155, in __init__
    self.interested_image = perform_upscale(self.interested_image)
  File "D:\Neuro\Fooocus_win64_1-1-10\Fooocus\modules\upscaler.py", line 21, in perform_upscale
    sd = torch.load(model_filename)
  File "D:\Neuro\Fooocus_win64_1-1-10\Fooocus\modules\patch.py", line 528, in loader
    raise ValueError(exp)
ValueError: [Errno 2] No such file or directory: 'D:\\Neuro\\Fooocus_win64_1-1-10\\Fooocus\\models\\upscale_models\\fooocus_upscaler_s409985e5.bin'

**Comment by notha99y** [comment]
you can download it here https://huggingface.co/lllyasviel/misc/blob/main/fooocus_upscaler_s409985e5.bin

**Comment by IPv6** [comment]
Having the same error, running in Colab.

@notha99y it tried to download and put model into place, but it is still not working. 

Now Fooocus can not load it, claiming file corrupted. butit was loaded with aria2, no chance for real corruption here

```

Upscaling image with shape (765, 700, 3) ...
Traceback (most recent call last):
  File "/content/Fooocus/modules/patch.py", line 512, in loader
    result = original_loader(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Fooocus/modules/async_worker.py", line 803, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 552, in handler
    inpaint_worker.current_task = inpaint_worker.InpaintWorker(
  File "/content/Fooocus/modules/inpaint_worker.py", line 155, in __init__
    self.interested_image = perform_upscale(self.interested_image)
  File "/content/Fooocus/modules/upscaler.py", line 21, in perform_upscale
    sd = torch.load(model_filename)
  File "/content/Fooocus/modules/patch.py", line 528, in loader
    raise ValueError(exp)
ValueError: invalid load key, '<'.
File corrupted: /content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin 
Fooocus has tried to move the corrupted file to /content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin.corrupted 
You may try again now and Fooocus will download models again. 
```

**Comment by notha99y** [comment]
Did you wget click into link and click the download button? ![image](https://github.com/lllyasviel/Fooocus/assets/29172421/6054b5dc-5bb0-4846-a541-e2c8a7770b3b)

If you wget the link directly, the file will be corrupted.

**Comment by Armen-Jean-Andreasian** [comment]
downlaod from https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin?download=true and paste in 
`...\Fooocus\models\upscale_models\ folder`

**Comment by adumont** [comment]
You can change the cell in the notebook to that, and relaunch, it will find the model afterwards.

```
!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git

%cd /content/Fooocus/models/upscale_models/
!wget -O fooocus_upscaler_s409985e5.bin https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin?download=true

%cd /content/Fooocus
# !python entry_with_update.py  --preset realistic --share
!python entry_with_update.py  --shar
```e

**Comment by hydra213** [comment]
Same issue here, downloading it directly and pasting it results in a corrupted file as well.

Likewise adding below code results in the same corrupted file error:

`%cd /content/Fooocus/models/upscale_models/
!wget -O fooocus_upscaler_s409985e5.bin https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin?download=true
`

Any solutions to this? I'm not really sure what this means or what causes it: `ValueError: BINBYTES exceeds system's maximum size of 9223372036854775807 bytes`

`Traceback (most recent call last):
  File "/content/Fooocus/modules/async_worker.py", line 803, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 552, in handler
    inpaint_worker.current_task = inpaint_worker.InpaintWorker(
  File "/content/Fooocus/modules/inpaint_worker.py", line 155, in __init__
    self.interested_image = perform_upscale(self.interested_image)
  File "/content/Fooocus/modules/upscaler.py", line 21, in perform_upscale
    sd = torch.load(model_filename)
  File "/content/Fooocus/modules/patch.py", line 528, in loader
    raise ValueError(exp)
ValueError: BINBYTES exceeds system's maximum size of 9223372036854775807 bytes
File corrupted: /content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin 
Fooocus has tried to move the corrupted file to /content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin.corrupted 
You may try again now and Fooocus will download models again. `

**Comment by adumont** [comment]
> Same issue here, downloading it directly and pasting it results in a corrupted file as well.
> 
> Likewise adding below code results in the same corrupted file error:
> 
> `%cd /content/Fooocus/models/upscale_models/ !wget -O fooocus_upscaler_s409985e5.bin https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_upscaler_s409985e5.bin?download=true `
> 
> Any solutions to this? I'm not really sure what this means or what causes it: `ValueError: BINBYTES exceeds system's maximum size of 9223372036854775807 bytes`
> 
> `Traceback (most recent call last): File "/content/Fooocus/modules/async_worker.py", line 803, in worker handler(task) File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/content/Fooocus/modules/async_worker.py", line 552, in handler inpaint_worker.current_task = inpaint_worker.InpaintWorker( File "/content/Fooocus/modules/inpaint_worker.py", line 155, in __init__ self.interested_image = perform_upscale(self.interested_image) File "/content/Fooocus/modules/upscaler.py", line 21, in perform_upscale sd = torch.load(model_filename) File "/content/Fooocus/modules/patch.py", line 528, in loader raise ValueError(exp) ValueError: BINBYTES exceeds system's maximum size of 9223372036854775807 bytes File corrupted: /content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin Fooocus has tried to move the corrupted file to /content/Fooocus/models/upscale_models/fooocus_upscaler_s409985e5.bin.corrupted You may try again now and Fooocus will download models again. `

i wonder why, it's working fine for me

**Comment by hydra213** [comment]
Thanks @adumont, turns out I didn't properly restart the runtime to remove the corrupted file. It works now, thanks for your help :)

**Comment by mashb1t** [comment]
Please find more information for Colab here: https://github.com/lllyasviel/Fooocus/issues/1149
