### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by pawelfloryan** [lllyasviel/Fooocus#1046]
**The problem**
I tried to run Foocus on AMD GPU. I've installed the latest rocm driver but it still tries to use cuda.
Even when I install torch from AMD package index it also installs some Nvidia packages:

```bash
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cublas-cu12==12.1.3.1
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvtx-cu12==12.1.105
```

**Full Console Log**
```bash
(venv) pawel@pawelGAMING:~/Projekty/Fooocus$ python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Otwieram w istniejącej sesji przeglądarki.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pawel/Projekty/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/home/pawel/Projekty/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/home/pawel/Projekty/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/home/pawel/Projekty/Fooocus/modules/patch.py", line 6, in <module>
    import fcbh.model_base
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/ldm/modules/diffusionmodules/openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/ldm/modules/attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/pawel/Projekty/Fooocus/webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/pawel/Projekty/Fooocus/backend/headless/fcbh/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/home/pawel/Projekty/Fooocus/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by pawelfloryan** [comment]
> Update your run.bat file https://github.com/lllyasviel/Fooocus#windowsamd-gpus

Sorry but I'm not using windows. Here I'm using Ubuntu 20.04 based ZorinOS

**Comment by mashb1t** [comment]
@pawelfloryan closing this issue for now, feel free to reopen if the instructed steps are not working for you.
Plus, keep in mind

> AMD is not intensively tested, however. The AMD support is in beta.
