### ISSUE TITLE
RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

### ISSUE THREAD

**Issue by jamo2011** [lllyasviel/Fooocus#1069]
I am on windows using amd. It is giving an error.

Enter LCM mode.
[Fooocus] Downloading LCM components ...
[Parameters] Adaptive CFG = 1.0
[Parameters] Sharpness = 0.0
[Parameters] ADM Scale = 1.0 : 1.0 : 0.0
[Parameters] CFG = 1.0
[Parameters] Seed = 4480460156234904860
[Parameters] Sampler = lcm - lcm
[Parameters] Steps = 8 - 8
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] a black cat walking across a street, futuristic, surreal, dramatic light, magic, sharp focus, extremely detailed, beautiful, stunning, winning, symmetry, highly educated, innocent, peaceful, cute, depicted, intricate, elegant, complex, amazing detail, color, enhanced, elaborate, colorful, illuminated, shiny, fashionable, clear, artistic, professional, wonderful, pure
[Fooocus] Encoding positive #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1280, 768)
Preparation time: 18.14 seconds
Using lcm scheduler.
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.39970144629478455, sigma_max = 14.614640235900879
Traceback (most recent call last):
  File "C:\Users\james\focus\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "C:\Users\james\focus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\james\focus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\james\focus\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\james\focus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\james\focus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\james\focus\Fooocus\modules\default_pipeline.py", line 355, in process_diffusion
    initial_latent['samples'].to(fcbh.model_management.get_torch_device()),
RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
Total time: 18.23 seconds

**Comment by mashb1t** [comment]
Please make sure your conputer meets the minimal requirements and you followed the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
Does this issue still exist? If yes, provide the FULL terminal output incl. call to command etc. without discarding anything.

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information.
