### ISSUE TITLE
locale.Error: locale query failed (when running run.bat)

### ISSUE THREAD

**Issue by Joakimpe** [lllyasviel/Fooocus#1073]
When I run any of the rub.bat files, this comes up. My system is in Norwegian, is this the issue? 

C:\Users\peder\Downloads\Fooocus_win64_2-1-791>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Traceback (most recent call last):
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\Fooocus\launch.py", line 107, in <module>
    from webui import *
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 1, in <module>
    import gradio as gr
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\components\__init__.py", line 3, in <module>
    from gradio.components.bar_plot import BarPlot
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\components\bar_plot.py", line 7, in <module>
    import altair as alt
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\altair\__init__.py", line 607, in <module>
    from .vegalite import *
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\altair\vegalite\__init__.py", line 2, in <module>
    from .v5 import *
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\altair\vegalite\v5\__init__.py", line 2, in <module>
    from .schema import *
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\altair\vegalite\v5\schema\__init__.py", line 2, in <module>
    from .core import *
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\altair\vegalite\v5\schema\core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\altair\utils\__init__.py", line 1, in <module>
    from .core import (
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\altair\utils\core.py", line 15, in <module>
    import pandas as pd
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\pandas\compat\__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
  File "pandas\_libs\hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas\_libs\missing.pyx", line 1, in init pandas._libs.missing
  File "C:\Users\peder\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\pandas\_libs\tslibs\__init__.py", line 39, in <module>
    from pandas._libs.tslibs.conversion import localize_pydatetime
  File "pandas\_libs\tslibs\conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas\_libs\tslibs\offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas\_libs\tslibs\timestamps.pyx", line 1, in init pandas._libs.tslibs.timestamps
  File "pandas\_libs\tslibs\timedeltas.pyx", line 81, in init pandas._libs.tslibs.timedeltas
  File "pandas\_libs\tslibs\fields.pyx", line 7, in init pandas._libs.tslibs.fields
  File "_strptime.py", line 268, in <module>
  File "_strptime.py", line 182, in __init__
  File "_strptime.py", line 69, in __init__
  File "_strptime.py", line 28, in _getlang
  File "locale.py", line 600, in getlocale
locale.Error: locale query failed

C:\Users\peder\Downloads\Fooocus_win64_2-1-791>pause
Press any key to continue . . .

**Comment by Joakimpe** [comment]
I can add that I tried to changing my system language to English (US), but it did not change anything

**Comment by mashb1t** [comment]
@Joakimpecan you please confirm if it is still not working with the latest version of Fooocus?

**Comment by mashb1t** [comment]
Closing as stale, feel free to reopen when providing new information.
