### ISSUE TITLE
RuntimeError: No HIP GPUs are available (Linux/AMD)

### ISSUE THREAD

**Issue by gc-octopis** [lllyasviel/Fooocus#1079]
System: Ubuntu 22.04
CPU: i5-6400
GPU: RX 570 8G
Environment: Anaconda
Python: 3.10.13

I installed with the commands in `readme.md` (both Linux anaconda and Linux AMD)

but it shows this error log:

```
Traceback (most recent call last):
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/octopis/Fooocus/webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "/home/octopis/Fooocus/backend/headless/fcbh/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/octopis/Fooocus/backend/headless/fcbh/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/octopis/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```

I saw someone is discussing the same error log in [ComfyUI](https://github.com/comfyanonymous/ComfyUI/issues/650) and I tried what they said: downgrade Pytorch, ROCm to 5.4.2. but still got the same error.

EDIT: forgot to mention, the Web UI does appear, but the error message just print out after trying to generate things. I don't know if this information helps, but I'll leave it here.

**Comment by wocif** [comment]
System: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
CPU: AMD Ryzen 7 2700
GPU: AMD RX 590
Python: 3.10.12

Same error here.

**Comment by Rayl11** [comment]
Same error.

System: Ubuntu 22.04.3 LTS in WSL2
CPU: AMD Ryzen 5 2600
GPU: AMD RX 6700XT 12GB
Python: 3.10.12
Environment: Venv

**Comment by EduartePaiva** [comment]
Same problem, I hope some solution can arrive 

System: Linux Mint 21.2 Cinnamon
CPU: AMD Ryzen 5 5500
GPU: AMD RX 6600M.
Python: 3.10.12
Environment: Venv

**Comment by ThomasMW** [comment]
> Facing the same issue
> System: Pop!_OS 22.04
> CPU: Ryzen 5 7600
> GPU: RX6800XT
> Python: Python 3.10.12
> Environment: venv
> 
> > Ran into the same issue, fixed it by doing the following.
> > 
> > 1 - https://docs.amd.com/en/latest/deploy/linux/quick_start.html and then setting the correct env variables for your GPU. You can check these using rocminfo. 2 - https://www.reddit.com/r/AMDHelp/comments/11l8wox/rocm_under_linux_running_on_cpu_by_default/
> 
> Unfortunately, amdgpu-dkms doesn't seem to support kernel version 6.5 (https://github.com/RadeonOpenCompute/ROCm/issues/2458) so I was not able to install it as I'm on 6.5.6. A workaround was provided but I'll have try it out.

My apologies. I should have specified that I fixed this on Ubuntu 22.04.

**Comment by EduartePaiva** [comment]
> Ran into the same issue, fixed it by doing the following.
> 
> 1 - https://docs.amd.com/en/latest/deploy/linux/quick_start.html and then setting the correct env variables for your GPU. You can check these using rocminfo. 2 - https://www.reddit.com/r/AMDHelp/comments/11l8wox/rocm_under_linux_running_on_cpu_by_default/

I tried doing that, the 1 installed alright, but Idk how to setup the env variables, neither my rocminfo worked, neither I don't know anything anymore 🙃

**Comment by ThomasMW** [comment]
What's the output when you run rocminfo?

**Comment by EduartePaiva** [comment]
> What's the output when you run rocminfo.

it says command 'rocminfo' not found, but it can be installed with: sudo apt install rocminfo. Then I install it but it's always the same message

**Comment by ThomasMW** [comment]
In that case I assume you tried to install rocminfo with 'sudo apt install rocminfo'. This pulls it from the Ubuntu repo. You need to prioritize the rocm repo.

Which is done here

```# Kernel driver repository for jammy
sudo tee /etc/apt/sources.list.d/amdgpu.list <<'EOF'
deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/5.7.1/ubuntu jammy main
EOF
# ROCm repository for jammy
sudo tee /etc/apt/sources.list.d/rocm.list <<'EOF'
deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/debian jammy main
EOF
# Prefer packages from the rocm repository over system packages
echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600```

**Comment by EduartePaiva** [comment]
> In that case I assume you tried to install rocminfo with 'sudo apt install rocminfo'. This pulls it from the system repo. You need to prioritize the rocm repo. Since you're on Mint I would assume it would also work since it's basically Ubuntu / Debian.
> 
> ```
> sudo tee /etc/apt/sources.list.d/amdgpu.list <<'EOF'
> deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/5.7.1/ubuntu jammy main
> EOF
> # ROCm repository for jammy
> sudo tee /etc/apt/sources.list.d/rocm.list <<'EOF'
> deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/debian jammy main
> EOF
> # Prefer packages from the rocm repository over system packages
> echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600```
> 
> then install it with
> 
> sudo apt update
> sudo apt install amdgpu-dkms
> sudo apt install rocm-hip-libraries
> ```

Thanks, I may have done something wrong but the rocminfo now works fine, I think the only thing left is changing the env variables.

what I found with the rocminfo command:

```
Agent 2                  
*******                  
  Name:                    gfx1032                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 6600M                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU
```

**Comment by ThomasMW** [comment]
In that case you set your env variables as;

HSA_OVERRIDE_GFX_VERSION=10.3.0
HCC_AMDGPU_TARGET=gfx1032

I would advise you to do this in the terminal from where you are running your environment first by;
`export HSA_OVERRIDE_GFX_VERSION=10.3.0` and `export HCC_AMDGPU_TARGET=gfx1032` and then run the application.

If it works you can set the variables by adding them to your `.bashrc`

**Comment by EduartePaiva** [comment]
> In that case you set your env variables as;
> 
> HSA_OVERRIDE_GFX_VERSION=10.3.0 HCC_AMDGPU_TARGET=gfx1032
> 
> I would advise you to do this in the terminal from where you are running your environment first by; `export HSA_OVERRIDE_GFX_VERSION=10.3.0` and `export HCC_AMDGPU_TARGET=gfx1032` and then run the application.
> 
> If it works you can set the variables by adding them to your `.bashrc`

I think everything went right but the error RuntimeError: No HIP GPUs are available still persists, but it was worth the try. Thanks for your time and let's wait to see if someone else can make it work

**Comment by ThomasMW** [comment]
You can test for compatibility using the following Python script. Run it in your activated environment and see what it outputs.

```
import torch, grp, pwd, os, subprocess
devices = []
try:
	print("\n\nChecking ROCM support...")
	result = subprocess.run(['rocminfo'], stdout=subprocess.PIPE)
	cmd_str = result.stdout.decode('utf-8')
	cmd_split = cmd_str.split('Agent ')
	for part in cmd_split:
		item_single = part[0:1]
		item_double = part[0:2]
		if item_single.isnumeric() or item_double.isnumeric():
			new_split = cmd_str.split('Agent '+item_double)
			device = new_split[1].split('Marketing Name:')[0].replace('  Name:                    ', '').replace('\n','').replace('                  ','').split('Uuid:')[0].split('*******')[1]
			devices.append(device)
	if len(devices) > 0:
		print('GOOD: ROCM devices found: ', len(devices))
	else:
		print('BAD: No ROCM devices found.')

	print("Checking PyTorch...")
	x = torch.rand(5, 3)
	has_torch = False
	len_x = len(x)
	if len_x == 5:
		has_torch = True
		for i in x:
			if len(i) == 3:
				has_torch = True
			else:
				has_torch = False
	if has_torch:
		print('GOOD: PyTorch is working fine.')
	else:
		print('BAD: PyTorch is NOT working.')


	print("Checking user groups...")
	user = os.getlogin()
	groups = [g.gr_name for g in grp.getgrall() if user in g.gr_mem]
	gid = pwd.getpwnam(user).pw_gid
	groups.append(grp.getgrgid(gid).gr_name)
	if 'render' in groups and 'video' in groups:
		print('GOOD: The user', user, 'is in RENDER and VIDEO groups.')
	else:
		print('BAD: The user', user, 'is NOT in RENDER and VIDEO groups. This is necessary in order to PyTorch use HIP resources')

	if torch.cuda.is_available():
		print("GOOD: PyTorch ROCM support found.")
		t = torch.tensor([5, 5, 5], dtype=torch.int64, device='cuda')
		print('Testing PyTorch ROCM support...')
		if str(t) == "tensor([5, 5, 5], device='cuda:0')":
			print('Everything fine! You can run PyTorch code inside of: ')
			for device in devices:
				print('---> ', device)
	else:
		print("BAD: PyTorch ROCM support NOT found.")
except:
	print('Cannot find rocminfo command information. Unable to determine if AMDGPU drivers with ROCM support were installed.')

**Comment by ThomasMW** [comment]
In that case add your user to those groups.

`sudo usermod -a -G render eduarte`
`sudo usermod -a -G video eduarte`

Check if the user was added.
`sudo grep eduarte /etc/group`

Make sure you do a full reboot after, not just a logout and login.

**Comment by EduartePaiva** [comment]
> In that case add your user to those groups.
> 
> `sudo usermod -a -G render eduarte` `sudo usermod -a -G video eduarte`
> 
> Check if the user was added. `sudo grep eduarte /etc/group`
> 
> Then do a full reboot, not just a logout and login.

Omg it really worked, it took quite a time but it worked!!
I think if this worked on my pc with an rx6600m it can pretty much work anywhere 

![Screenshot 2023-12-04 at 20-18-27 Fooocus 2 1 824](https://github.com/lllyasviel/Fooocus/assets/74308809/5275a9ad-6843-4095-8895-b77070319ec8)

**Comment by ThomasMW** [comment]
> > In that case add your user to those groups.
> > 
> > `sudo usermod -a -G render eduarte` `sudo usermod -a -G video eduarte`
> > 
> > Check if the user was added. `sudo grep eduarte /etc/group`
> > 
> > Then do a full reboot, not just a logout and login.
> 
> Omg it really worked, it took quite a time but it worked!!
> I think if this worked on my pc with an rx6600m it can pretty much work anywhere 
> Thanks a lot for the help.
> These images took 5 minutes to generate but now I believe it's just low specs
> 
> ![Screenshot 2023-12-04 at 20-18-27 Fooocus 2 1 824](https://github.com/lllyasviel/Fooocus/assets/74308809/5275a9ad-6843-4095-8895-b77070319ec8)
> 

Glad to hear it, enjoy ✌️

**Comment by EduartePaiva** [comment]
I think that I can help but first what's your system specification @wocif , and export HSA_OVERRIDE_GFX_VERSION=10.3.0 and export HCC_AMDGPU_TARGET=gfx1030 if based on your own gpu if your gpu is not an rx6600M the values is different

**Comment by wocif** [comment]
> I think that I can help but first what's your system specification @wocif , and export HSA_OVERRIDE_GFX_VERSION=10.3.0 and export HCC_AMDGPU_TARGET=gfx1030 if based on your own gpu if your gpu is not an rx6600M the values is different

System: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
CPU: AMD Ryzen 7 2700
GPU: AMD RX 590 8gb
Python: 3.10.12
Environment: venv

I'm not certain about the HSA_OVERRIDE_GFX_VERSION, but as I tried to mentioned, the gpu actually is gfx803, but when I run rocminfo inside the venv it outputs me gfx1030. Should I use the output from inside or outside the venv?
And how can I find the correct gfx-version for my gpu?

**Comment by EduartePaiva** [comment]
> > I think that I can help but first what's your system specification @wocif , and export HSA_OVERRIDE_GFX_VERSION=10.3.0 and export HCC_AMDGPU_TARGET=gfx1030 if based on your own gpu if your gpu is not an rx6600M the values is different
> 
> System: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy CPU: AMD Ryzen 7 2700 GPU: AMD RX 590 8gb Python: 3.10.12 Environment: venv
> 
> I'm not certain about the HSA_OVERRIDE_GFX_VERSION, but as I tried to mentioned, the gpu actually is gfx803, but when I run rocminfo inside the venv it outputs me gfx1030. Should I use the output from inside or outside the venv? And how can I find the correct gfx-version for my gpu?

HCC_AMDGPU_TARGET=gfx803 based on https://www.techpowerup.com/gpu-specs/radeon-rx-590.c3322
HSA_OVERRIDE_GFX_VERSION=10.3.0 I think it's the same. 
and rocminfo technically you can use anywhere it was just a way to look for the gfx803 instead of techpowerup. but if rocminfo is not working the application won't work too

**Comment by ric2b** [comment]
## Please be very careful with which OS/kernel version you have before trying to install amdgpu-dkms from the rocm repo!

My installation failed with a compilation error (I suspect an incompatibility with my kernel version, 6.5) and upon reboot my system was failing to boot GDM and so I only had a black screen with a blinking cursor. Took me quite a while in a TTY and several reboots until I got it booting correctly again.

[Check for supported versions here](https://docs.amd.com/en/latest/release/gpu_os_support.html)

**Comment by demaseme** [comment]
For future reference...I had the same issue on a FRESH installation of OpenSuse TW.
But fixed it:
![imagen](https://github.com/lllyasviel/Fooocus/assets/5651996/2460ff70-6471-4cae-bcf7-fd15b08fc314)
What I did from a fresh installation was: 

1. Install ROCm following[ these instructions.](: https://docs.amd.com/en/latest/deploy/linux/quick_start.html)
1.1. Here I ran into an issue regarding a library that wasn't provided by TW. [So I installed the component with OBS. ](https://software.opensuse.org/download.html?project=home%3Ainterstar001%3ACentreon&package=perl-URI-Encode)
3. Add my user to the render group:
    > In that case add your user to those groups.
    > 
    > `sudo usermod -a -G render eduarte` `sudo usermod -a -G video eduarte`
    > 
    > Check if the user was added. `sudo grep eduarte /etc/group`
    > 
    > Then do a full reboot, not just a logout and login.
4.  Run with HSA_OVERRIDE_GFX_VERSION=10.3.0 python entry_with_update.py

**Comment by led0nk** [comment]
I'm trying to run this inside a Docker-Container, but i cannot get it to work.
I got the same issues as you guys with telling me 
`RuntimeError: No HIP GPUs are available
`

So i tried your way installing ROCM:
[https://github.com/lllyasviel/Fooocus/issues/1079#issuecomment-1839145629](url)
But this didnt went well for me,too. The repos aren't signed and i coulnd't get an updated repo-list, so i tried it this way:

[https://rocm.docs.amd.com/projects/install-on-linux/en/latest/tutorial/quick-start.html#amdgpu-installer](url)

On top of that it seems like there are some deleted links in one of your first workarounds [https://github.com/lllyasviel/Fooocus/issues/1079#issuecomment-1837597622](url)

Post-installation i added root to both user groups (problem here, i cannot restart docker container and also cannot implement it into the containerfile) but trying the `rocminfo` command i ran into another issue:
`Unable to open /dev/kfd read-write: Permission denied
`
So now i'm kinda clueless how to fix this since i cannot progress towards the next step..

P.S.: I'm running the container based on Ubuntu 22.04

**Comment by wocif** [comment]
> I'm trying to run this inside a Docker-Container, but i cannot get it to work.
> I got the same issues as you guys with telling me 
> `RuntimeError: No HIP GPUs are available
> `
> 
> So i tried your way installing ROCM:
> [https://github.com/lllyasviel/Fooocus/issues/1079#issuecomment-1839145629](url)
> But this didnt went well for me,too. The repos aren't signed and i coulnd't get an updated repo-list, so i tried it this way:
> 
> [https://rocm.docs.amd.com/projects/install-on-linux/en/latest/tutorial/quick-start.html#amdgpu-installer](url)
> 
> On top of that it seems like there are some deleted links in one of your first workarounds [https://github.com/lllyasviel/Fooocus/issues/1079#issuecomment-1837597622](url)
> 
> Post-installation i added root to both user groups (problem here, i cannot restart docker container and also cannot implement it into the containerfile) but trying the `rocminfo` command i ran into another issue:
> `Unable to open /dev/kfd read-write: Permission denied
> `
> So now i'm kinda clueless how to fix this since i cannot progress towards the next step..
> 
> P.S.: I'm running the container based on Ubuntu 22.04

I'm also clueless the moment, but will try it on docker too next month ig, since it's the better way to do stuff like that. Haven't had time to try yet

**Comment by infinity0** [comment]
Working on:

~~~~
Device: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.54, 6.6.15-amd64) (0x747e)
~~~~

**Comment by infinity0** [comment]
Confirming working with:

~~~~
export HSA_OVERRIDE_GFX_VERSION=11.0.0
export HCC_AMDGPU_TARGET=gfx1101
python3 entry_with_update.py
~~~~

on

~~~~
Device: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.54, 6.6.15-amd64) (0x747e)
~~~~

Funnily enough, it doesn't show up on `rocminfo` even when I set the envvars, but Fooocus itself works. Hope this helps someone.

**Comment by aidanhorn** [comment]
From @led0nk on [2023-12-26](#issuecomment-1869183873):

> The repos aren't signed and i coulnd't get an updated repo-list, so i tried it this way:

Yes, I confirm this. The ROCm installation guide is now at https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html but when following the instructions, the repo does not have a public key signature.

```
W: GPG error: https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51716619E084DAB9
E: The repository 'https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by max-huster** [comment]
I fixed mine after updating my system and adding my user to the `render` group.
RX 5700, Ubuntu 22.04.4

Many thanks to all the comments which helped me finding a solution!

**Comment by qwertjkl57** [comment]
> In that case I assume you tried to install rocminfo with 'sudo apt install rocminfo'. This pulls it from the system repo. You need to prioritize the rocm repo. Since you're on Mint I would assume it would also work since it's basically Ubuntu / Debian.
> 
> ```
> sudo tee /etc/apt/sources.list.d/amdgpu.list <<'EOF'
> deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/5.7.1/ubuntu jammy main
> EOF
> # ROCm repository for jammy
> sudo tee /etc/apt/sources.list.d/rocm.list <<'EOF'
> deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/debian jammy main
> EOF
> # Prefer packages from the rocm repository over system packages
> echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600```
> 
> then install it with
> 
> sudo apt update
> sudo apt install amdgpu-dkms
> sudo apt install rocm-hip-libraries
> ```

entering in the first part in bash gives me:
deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/5.7.1/ubuntu jammy main
deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/debian jammy main
& the prompt turns into a single ">". then, when i enter the install commands it does nothing.
