### ISSUE TITLE
NixOS - Nvidia driver not found

### ISSUE THREAD

**Issue by Adamekka** [lllyasviel/Fooocus#1080]
**Describe the problem**
Fooocus cannot find Nvidia drivers installed on my system, I'm using NixOS unstable and my GPU is Nvidia GTX 1650
I have drivers them installed on my system
Here is part of my config that contains that they are installed:
```nix
    xserver = {
      enable = true;
      displayManager = {
        gdm = {
          enable = true;
          wayland = true;
        };
        sessionPackages = with pkgs; [
          hyprland
        ];
      };
      layout = "us";
      libinput.enable = true;
      videoDrivers = [ "nvidia" ];
    };

  hardware = {
    nvidia = {
      modesetting.enable = true;
      nvidiaSettings = true;
      open = false;
      package = config.boot.kernelPackages.nvidiaPackages.stable;
    };
    opengl = {
      driSupport = true;
      driSupport32Bit = true;
      enable = true;
    };
    pulseaudio.support32Bit = true;
  };
```

**Full Console Log**
```sh
[nix-shell:~/Coding/Fooocus]$ python entry_with_update.py
Update failed.
libz.so.1: cannot open shared object file: No such file or directory
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [GCC 12.3.0]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Opening in existing browser session.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/run/current-system/sw/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/run/current-system/sw/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adamekka/Coding/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/home/adamekka/Coding/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/home/adamekka/Coding/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/home/adamekka/Coding/Fooocus/modules/patch.py", line 6, in <module>
    import fcbh.model_base
  File "/home/adamekka/Coding/Fooocus/backend/headless/fcbh/model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "/home/adamekka/Coding/Fooocus/backend/headless/fcbh/ldm/modules/diffusionmodules/openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "/home/adamekka/Coding/Fooocus/backend/headless/fcbh/ldm/modules/attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/home/adamekka/Coding/Fooocus/backend/headless/fcbh/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "/home/adamekka/Coding/Fooocus/backend/headless/fcbh/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/adamekka/Coding/Fooocus/backend/headless/fcbh/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adamekka/Coding/Fooocus/fooocus_env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/home/adamekka/Coding/Fooocus/fooocus_env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
^CKeyboard interruption in main thread... closing server.
(fooocus_env)
[nix-shell:~/Coding/Fooocus]$
```

**Comment by Hassan0Kamel** [comment]
I have the same problem, my laptop: Toshiba Satelite C50-A570 and my nvidia card is 710M
I even installed Anaconda and via it I installed PyTorch, same issue happen

**Comment by lorenzo-frittoli** [comment]
Try and execute the `nvidia-smi` command to check for drivers maybe

**Comment by Hassan0Kamel** [comment]
> Try and execute the `nvidia-smi` command to check for drivers maybe

Sat Dec 02 15:40:02 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 376.54                 Driver Version: 376.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 710M       WDDM  | 0000:01:00.0     N/A |                  N/A |
| N/A   57C    P0    N/A /  N/A |     48MiB /  2048MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+


this showed after executing the command, what does it mean? do I have cuda 8 installed? can I still install Fooocus?

**Comment by Adamekka** [comment]
> Try and execute the `nvidia-smi` command to check for drivers maybe

I have them installed, nvidia-smi works

**Comment by cnnrro** [comment]
Found this issue while searching for a solution as I've been having a similar problem since upgrading NixOS 23.05 -> 23.11.

Created a ticket in the nixpkgs repo: https://github.com/NixOS/nixpkgs/issues/272413

**Comment by Adamekka** [comment]
> @Adamekka, see if the solution to my problem works for you: [NixOS/nixpkgs#272413 (comment)](https://github.com/NixOS/nixpkgs/issues/272413#issuecomment-1844778154)

still won't work

**Comment by Nebucatnetzer** [comment]
This flake works for me:
https://github.com/Nebucatnetzer/Fooocus/blob/flake/flake.nix

**Comment by duncanam** [comment]
+1 on this issue. I have tried both fixes mentioned by @cnnrro without success. `nvidia-smi` returns a driver version that shows CUDA 12.3 for me.

**Comment by mashb1t** [comment]
> I have the same problem, my laptop: Toshiba Satelite C50-A570 and my nvidia card is 710M I even installed Anaconda and via it I installed PyTorch, same issue happen

@Hassan0Kamel Please make sure you meet the minimal requirements listed here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement.

As @Nebucatnetzer provided a (seemingly) working version i assume this issue can be closed. Feel free to comment if you still have problems with the solution mentioned in https://github.com/lllyasviel/Fooocus/issues/1080#issuecomment-1849059036

**Comment by duncanam** [comment]
@mashb1t I also attempted that solution and was still getting errors.

**Comment by mashb1t** [comment]
@duncanam is this still an issue or have you found a solution in the meantime?

**Comment by duncanam** [comment]
> @duncanam is this still an issue or have you found a solution in the meantime?

Still an issue :(

**Comment by nimeshvspl** [comment]
Gettig this error anyone can help ? 
running on windows earlier it was working fine but now i am getting this error.

File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by luxus** [comment]
the flake is not available anymore :(

**Comment by Arthurdw** [comment]
Hi there, I had the same issue but was able to resolve it with #3937. Try that and let me know there if it has resolved your issues. (add a 👍🏻 if it works, if it doesn't please send your error)

Lets spread some Nix happiness 😄

**Comment by Phylliida** [comment]
First I use fix-python --venv ~/.venv

Then

export NIXPKGS_ALLOW_UNFREE=1 

export CUDA_PATH=$(nix eval --raw --expr 'let pkgs = import <nixpkgs> {}; in "${pkgs.cudatoolkit}"' --impure --extra-experimental-features "nix-command flakes")

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(nix eval --raw --expr 'let pkgs = import <nixpkgs> {}; in pkgs.lib.makeLibraryPath [
  "/run/opengl-driver"
  pkgs.cudatoolkit
  pkgs.cudaPackages.cudnn
  pkgs.stdenv.cc.cc
]' --impure --extra-experimental-features 'nix-command flakes')"

Or for the full experience 

```bash
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(nix eval --raw --expr '
  let pkgs = import <nixpkgs> {};
      cuda = pkgs.cudaPackages;
  in pkgs.lib.makeLibraryPath [
    "/run/opengl-driver"
    pkgs.cudatoolkit
    cuda.cudnn
    pkgs.stdenv.cc.cc
    cuda.libnvjitlink
    cuda.cuda_cccl
    cuda.cuda_cudart
    cuda.cuda_cupti
    cuda.cuda_nvcc
    cuda.cuda_nvml_dev
    cuda.cuda_nvrtc
    cuda.cuda_nvtx
    cuda.cusparselt
    cuda.libcublas
    cuda.libcufft
    cuda.libcufile
    cuda.libcurand
    cuda.libcusolver
    cuda.libcusparse
    cuda.cudatoolkit
    cuda.cutensor
    cuda.cuda_opencl
  ]' --impure --extra-experimental-features "nix-command flakes")"
```
