### ISSUE TITLE
issue with my graphics card, and cuda version 8000

### ISSUE THREAD

**Issue by Hassan0Kamel** [lllyasviel/Fooocus#1083]
To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "F:\Factory\Foocus\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "F:\Factory\Foocus\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "F:\Factory\Foocus\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "F:\Factory\Foocus\Fooocus\modules\patch.py", line 6, in <module>
    import fcbh.model_base
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\ldm\modules\attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device    return torch.device(torch.cuda.current_device())
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 8000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
Traceback (most recent call last):
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "F:\Factory\Foocus\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "F:\Factory\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device    return torch.device(torch.cuda.current_device())
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "F:\Factory\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 8000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

laptop: Toshiba Satelite C50 - A570
python --version:
3.11.5

Cuda Version: 8.0.0
I'm new to this if there're any missed info plz tell me so I can provide you with all necessary info.

**Comment by mashb1t** [comment]
Your Laptop seems to not be compatible with the requierements of Fooocus. You need
* CUDA > 11.X (11.8 / 12.X do work)
* Python = 3.10

> The NVIDIA driver on your system is too old

Please make sure to update your driver.
