### ISSUE TITLE
RuntimeError with allocating gpu video memory - There is not enough GPU video memory available (AMD)

### ISSUE THREAD

**Issue by GroupXyz1** [lllyasviel/Fooocus#1088]
**When generating more than one picture after starting, i get memory issues at the end of the generation process and it gets cancelled.**

SYSTEM SPECS:

AMD GPU
AMD CPU
Windows
32 GB Ram
~ 16 GB VRam ig

ERROR:

Traceback (most recent call last):
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 59, in forward
    x = torch.nn.functional.interpolate(x, scale_factor=2.0, mode="nearest")
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: Could not allocate tensor with 2123366400 bytes. There is not enough GPU video memory available!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\default_pipeline.py", line 378, in process_diffusion
    decoded_latent = core.decode_vae(vae=target_vae, latent_image=sampled_latent, tiled=tiled)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\core.py", line 169, in decode_vae
    return opVAEDecode.decode(samples=latent_image, vae=vae)[0]
  File "D:\Fooocus\Fooocus\backend\headless\nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\sd.py", line 225, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples).cpu().float() + 1.0) / 2.0, min=0.0, max=1.0)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\models\autoencoder.py", line 201, in decode
    dec = self.decoder(dec, **decoder_kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 638, in forward
    h = self.up[i_level].upsample(h)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 62, in forward
    out = torch.empty((b, c, h*2, w*2), dtype=x.dtype, layout=x.layout, device=x.device)
RuntimeError: Could not allocate tensor with 2123366400 bytes. There is not enough GPU video memory available!
Total time: 551.26 seconds

FULL CONSOLE LOG:

D:\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--directml']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Using directml with device:
Total VRAM 1024 MB, total RAM 32677 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Refiner unloaded.
model_type EPS
adm 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra keys {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: D:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [D:\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 2039124207989579973
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] test, dramatic, cinematic, detailed, transparent background, professional, highly coherent, colorful, deep colors, surreal, open atmosphere, amazing, symmetry, perfect, artistic, beautiful, sharp focus, pretty, intricate, fine, complex, extremely elegant, creative, color spread, enhanced light, ambient, thought, iconic, great composition, clear, futuristic, epic, grand
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] test, epic composition, joyful, unique, elegant, intricate, highly detailed, dramatic light, illuminated background, sharp focus, cinematic, fine detail, colorful, surreal, beautiful, striking, rich deep colors, winning new creative atmosphere, professional, fascinating, amazing, artistic, positive, pure, emotional, pretty, attractive, cute, best, lovely, perfect, coherent
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 10.33 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 5.19 seconds
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]D:\Fooocus\Fooocus\modules\anisotropic.py:132: UserWarning: The operator 'aten::std_mean.correction' is not currently supported on the DML backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\dml\dml_cpu_fallback.cpp:17.)
  s, m = torch.std_mean(g, dim=(1, 2, 3), keepdim=True)
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [02:58<00:00,  5.95s/it]
Image generated with private log at: D:\Fooocus\Fooocus\outputs\2023-11-30\log.html
Generating and saving time: 186.85 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.15 seconds
 37%|██████████████████████████████                                                    | 11/30 [01:10<02:00,  6.37s/it]
User stopped
Total time: 271.22 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 1577997771226251594
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] test, extremely detailed, beautiful, intricate detail, cinematic, stunning light, inspired, fiery, colorful, symmetry, fine balanced composition, innocent, glowing, aesthetic, joyful, pure, very inspirational, clear, epic, fantastic, full color, artistic, sharp, amazing, cool, awesome, inspiring, highly relaxed, creative, wonderful, bright, marvelous, shiny, vibrant
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] test, detailed, creative, winning, shiny, handsome, glossy, majestic, glorious, light, wonderful, pretty, charming, marvelous, flowing, intricate, highly, extremely detail, cinematic, artistic, color, fine, surreal, polished, beautiful, atmosphere, amazing, full, very coherent, colorful, epic, brilliant, complimentary colors, perfect composition, aesthetic, great
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Image processing ...
[Fooocus] VAE encoding ...
Traceback (most recent call last):
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 453, in handler
    initial_latent = core.encode_vae(vae=candidate_vae, pixels=initial_pixels)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\core.py", line 178, in encode_vae
    return opVAEEncode.encode(pixels=pixels, vae=vae)[0]
  File "D:\Fooocus\Fooocus\backend\headless\nodes.py", line 304, in encode
    t = vae.encode(pixels[:,:,:,:3])
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\sd.py", line 252, in encode
    samples[x:x+batch_number] = self.first_stage_model.encode(pixels_in).cpu().float()
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\models\autoencoder.py", line 180, in encode
    z = self.encoder(x)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 522, in forward
    h = self.down[i_level].block[i_block](h, temb)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 149, in forward
    h = self.conv2(h)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Could not allocate tensor with 1061683200 bytes. There is not enough GPU video memory available!
Total time: 13.40 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 3410712026276241265
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] minecraft skin, beautiful, marvelous artistic, cinematic composition, dramatic exotic, elegant, highly detailed, sharp focus, graceful, epic, stunning, amazing detail, gorgeous, flowing, intricate, fantastic, perfect, colorful, lovely, cute, coherent, cheerful, complex, vibrant color background, iconic, fine, elaborate, focused, professional, sublime, wonderful, brilliant, expressive
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] minecraft skin, full beautiful, detailed intricate, elegant, light glowing, sharp focus, radiant, highly coherent, symmetry, fine detail, cinematic, pristine, enhanced, unique, creative, wonderful colors, positive, cute, attractive, pure, determined, friendly, best, confident, pretty, calm, relaxed, passionate, extremely, futuristic, color, illuminated, brilliant, shiny
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Image processing ...
[Fooocus] VAE encoding ...
Final resolution is (1080, 1920).
[Parameters] Denoising Strength = 0.85
[Parameters] Initial Latent shape: torch.Size([1, 4, 135, 240])
Preparation time: 15.25 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 7.754775524139404
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.24 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [08:50<00:00, 17.68s/it]
Traceback (most recent call last):
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 59, in forward
    x = torch.nn.functional.interpolate(x, scale_factor=2.0, mode="nearest")
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: Could not allocate tensor with 2123366400 bytes. There is not enough GPU video memory available!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\default_pipeline.py", line 378, in process_diffusion
    decoded_latent = core.decode_vae(vae=target_vae, latent_image=sampled_latent, tiled=tiled)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus\Fooocus\modules\core.py", line 169, in decode_vae
    return opVAEDecode.decode(samples=latent_image, vae=vae)[0]
  File "D:\Fooocus\Fooocus\backend\headless\nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\sd.py", line 225, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples).cpu().float() + 1.0) / 2.0, min=0.0, max=1.0)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\models\autoencoder.py", line 201, in decode
    dec = self.decoder(dec, **decoder_kwargs)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 638, in forward
    h = self.up[i_level].upsample(h)
  File "D:\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Fooocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\model.py", line 62, in forward
    out = torch.empty((b, c, h*2, w*2), dtype=x.dtype, layout=x.layout, device=x.device)
RuntimeError: Could not allocate tensor with 2123366400 bytes. There is not enough GPU video memory available!
Total time: 551.26 seconds

Would appreciate help!

**Comment by MrDakCol** [comment]
https://github.com/lllyasviel/Fooocus/issues/1078 Same issue described there.

**Comment by GroupXyz1** [comment]
@MrDakCol Thank you for notifying, didnt scroll down that far, gonna close this so we dont have that much duplicates
