### ISSUE TITLE
RuntimeError: Device type privateuseone is not supported for torch.Generator() api.

### ISSUE THREAD

**Issue by IdentifiedBody** [lllyasviel/Fooocus#1111]
**Describe the problem**
When trying to generate an image it gives that runtimeErrror, im on windows running and AMD GPU.

**Full Console Log**
**Traceback (most recent call last):
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\default_pipeline.py", line 354, in process_diffusion
    modules.patch.BrownianTreeNoiseSamplerPatched.global_init(
  File "D:\AITOOLbusiness\Tool\Fooocus\modules\patch.py", line 173, in global_init
    BrownianTreeNoiseSamplerPatched.tree = BatchedBrownianTree(x, t0, t1, seed, cpu=cpu)
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in __init__
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "D:\AITOOLbusiness\Tool\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in <listcomp>
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torchsde\_brownian\derived.py", line 155, in __init__
    self._interval = brownian_interval.BrownianInterval(t0=t0,
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 540, in __init__
    W = self._randn(initial_W_seed) * math.sqrt(t1 - t0)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 234, in _randn
    return _randn(size, self._top._dtype, self._top._device, seed)
  File "D:\AITOOLbusiness\Tool\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 32, in _randn
    generator = torch.Generator(device).manual_seed(int(seed))
RuntimeError: Device type privateuseone is not supported for torch.Generator() api.
Total time: 211.94 seconds**

**Comment by sergiueth** [comment]
same error here, have you fixed it?

**Comment by IdentifiedBody** [comment]
> same error here, have you fixed it?

Nope, trying out various things, but i assume this is 100% related to the usage of an AMD GPU

**Comment by IdentifiedBody** [comment]
> same error here, have you fixed it?

https://github.com/lllyasviel/Fooocus/issues/624#issuecomment-1757327660

found a fix

**Comment by IdentifiedBody** [comment]
But now it says "There is not enough GPU video memory available!"

even though im allocating like 4GB of VRAM
