### ISSUE TITLE
为啥我的m1 pro 32g

### ISSUE THREAD

**Issue by wang1024it** [lllyasviel/Fooocus#1168]
**Describe the problem**

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/torch/
Collecting torch==2.1.0
  Downloading torch-2.1.0-cp310-none-macosx_10_9_x86_64.whl (147.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.0/147.0 MB 8.4 MB/s eta 0:00:00
Collecting torchvision==0.16.0
  Downloading torchvision-0.16.0-cp310-cp310-macosx_10_13_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 16.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torch==2.1.0) (4.8.0)
Requirement already satisfied: jinja2 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torch==2.1.0) (3.1.2)
Requirement already satisfied: networkx in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torch==2.1.0) (3.2.1)
Requirement already satisfied: filelock in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torch==2.1.0) (3.13.1)
Requirement already satisfied: sympy in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torch==2.1.0) (1.12)
Requirement already satisfied: fsspec in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torch==2.1.0) (2023.12.0)
Requirement already satisfied: requests in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torchvision==0.16.0) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torchvision==0.16.0) (9.2.0)
Requirement already satisfied: numpy in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from torchvision==0.16.0) (1.23.5)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from jinja2->torch==2.1.0) (2.1.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from requests->torchvision==0.16.0) (2023.11.17)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from requests->torchvision==0.16.0) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from requests->torchvision==0.16.0) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from requests->torchvision==0.16.0) (3.6)
Requirement already satisfied: mpmath>=0.19 in /Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages (from sympy->torch==2.1.0) (1.3.0)
Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.1.1
    Uninstalling torch-2.1.1:
      Successfully uninstalled torch-2.1.1
Successfully installed torch-2.1.0 torchvision-0.16.0
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors" to /Users/king/python_work/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors

Traceback (most recent call last):
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/king/python_work/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/king/python_work/Fooocus/launch.py", line 105, in <module>
    download_models()
  File "/Users/king/python_work/Fooocus/launch.py", line 73, in download_models
    load_file_from_url(url=url, model_dir=path_checkpoints, file_name=file_name)
  File "/Users/king/python_work/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>
(fooocus) king@kingdeMacBook-Pro Fooocus % python entry_with_update.py --listen
Update failed.
error sending data: Broken pipe
Update succeeded.
[System ARGV] ['entry_with_update.py', '--listen']
Python 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
Fooocus version: 2.1.824
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors" to /Users/king/python_work/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors

Traceback (most recent call last):
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/king/product/anaconda3/path/anaconda3/envs/fooocus/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/king/python_work/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/king/python_work/Fooocus/launch.py", line 105, in <module>
    download_models()
  File "/Users/king/python_work/Fooocus/launch.py", line 73, in download_models
    load_file_from_url(url=url, model_dir=path_checkpoints, file_name=file_name)

**Comment by mashb1t** [comment]
See https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#ssl-certificate_verify_failed
