### ISSUE TITLE
Getting error on AMD RX 550

### ISSUE THREAD

**Issue by tohedul** [lllyasviel/Fooocus#1190]
I'm unable to run this properly on my AMD RX 550 GPU-powered PC. It's getting the issue "Found no NVIDIA  driver on your system. How can I use this with my AMD GPU?

H:\AGI\Fooocus_win64_2-1-791>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\modules\patch.py", line 6, in <module>
    import fcbh.model_base
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\ldm\modules\attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "H:\AGI\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "H:\AGI\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "H:\AGI\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by Stimmenhotel** [comment]
You have not changed the windows+amd specific run.bat settings.

**Comment by mashb1t** [comment]
@tohedul please find the instructions here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windowsamd-gpus
