### ISSUE TITLE
getting this error while running "python entry_with_update.py"

### ISSUE THREAD

**Issue by gitvishal96** [lllyasviel/Fooocus#1192]
i am getting this error -""
(fooocus_env) PS D:\Brave downloads\Fooocus-main\Fooocus-main> python entry_with_update.py
Update failed.
No module named 'pygit2'
Update succeeded.
[System ARGV] ['entry_with_update.py']
Traceback (most recent call last):
  File "D:\Brave downloads\Fooocus-main\Fooocus-main\entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\Brave downloads\Fooocus-main\Fooocus-main\launch.py", line 22, in <module>
    from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
  File "D:\Brave downloads\Fooocus-main\Fooocus-main\modules\config.py", line 7, in <module>
    import modules.sdxl_styles
  File "D:\Brave downloads\Fooocus-main\Fooocus-main\modules\sdxl_styles.py", line 5, in <module>
    from modules.util import get_files_from_folder
  File "D:\Brave downloads\Fooocus-main\Fooocus-main\modules\util.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
"

**Comment by cberry31** [comment]
I would try running `pip3 install -r requirements_versions.txt` if you haven't yet. It appears there might be some missing packages, and this step should ensure that all necessary dependencies are installed properly.

**Comment by haab1001** [comment]
(fooocus_env) PS D:\AI_code\Fooocus> python entry_with_update.py
Update failed.
No module named 'pygit2'
Update succeeded.
[System ARGV] ['entry_with_update.py']
Traceback (most recent call last):
  File "entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\AI_code\Fooocus\launch.py", line 22, in <module>
    from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
  File "D:\AI_code\Fooocus\modules\config.py", line 7, in <module>
    import modules.sdxl_styles
  File "D:\AI_code\Fooocus\modules\sdxl_styles.py", line 5, in <module>
    from modules.util import get_files_from_folder
  File "D:\AI_code\Fooocus\modules\util.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by gitvishal96** [comment]
I am running this code in windows system. And also I have a 1GB AMD GPU!
Maybe that is causing the problem!

**Comment by random9brat** [comment]
Im having the same issue... even tho my python3 --version is ok in cmd

**Comment by random9brat** [comment]
fixed it with installing python3 with env variables and deleting the old unzipped folder (unzipped it again)

**Comment by mashb1t** [comment]
See also https://github.com/lllyasviel/Fooocus/issues/1665
