### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### ISSUE THREAD

**Issue by JagreetDasgupta** [lllyasviel/Fooocus#1204]
**Describe the problem**
Giving prompt and clicking generate but keeps saying error.

**Full Console Log**

C:\Users\jagre\Downloads\Fooocus_win64_2-1-791>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\modules\patch.py", line 6, in <module>
    import fcbh.model_base
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\ldm\modules\attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 122, in skip_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\jagre\Downloads\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

![image](https://github.com/lllyasviel/Fooocus/assets/128155116/7e283abd-2dd4-403e-9f5d-89875a997294)

**Comment by hkup859** [comment]
I'm getting the same issue. I don't have an Nvidia GPU, but do have AMD integrated graphics (AMD 6900HX), running on Windows. Is there any way to utilize the onboard AMD graphics or use CPU only? I understand that the performance will likely be horrible, but I don't have a machine with a dedicated GPU.

**Comment by Abyss-chan** [comment]
are you running it on colab?, if it is, check what gpu you are using.

**Comment by hkup859** [comment]
> are you running it on colab?, if it is, check what gpu you are using.

I tested on Colab and was able to run without issue, however I was looking to run it locally. Is there a way to do this with the amd integrated graphics and or cpu only?

**Comment by MadChipmunk03** [comment]
yeah AMD is just not supported - but there is a workaround: [Stable Diffusion on AMD GPUs](https://www.youtube.com/watch?v=8xR0vms0e0U&ab_channel=TrentKingdom)

**Comment by Amit30swgoh** [comment]
My problem .gradio.live  i get this error:

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

https://colab.research.google.com/drive

!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus
!python entry_with_update.py --share

I dont understand why and if i need driver for google colab how i download what to write and where please?

.gradio.live

**Comment by mashb1t** [comment]
> Is there a way to do this with the amd integrated graphics and or cpu only?

Most likely nit, please check the minimal requirements in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement

> > having the same error when I instal, running a AMD Radeon RX 7900 XTX not NVIDIA
> 
> Just to double check, did you run the amd specific steps found [here](https://github.com/lllyasviel/Fooocus#windowsamd-gpus)?
> 
> I haven't gotten mine working yet, but wanted to make you aware as I think it checks for nvidia by default.

This is completely true, default is Nvidia GPU support.

AMD GPUs are supported, but honestly still behind in performance/stability compared to Nvidia GPUs.
Please follow the official installation guide and use DirectML on Windows and ROCm on Linux, see https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windowsamd-gpus.
If you need further assistance we can reopen this issue.

@Amit30swgoh make sure you use a T4 instance in Colab. It works out of the box.

**Comment by BABury** [comment]
Is it possible to run this on a macbook with the computing power of a NVIDIA GPU? If not, maybe on an external server?

**Comment by mashb1t** [comment]
@BABury https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac 👀

**Comment by artem174a-dev** [comment]
I ran into the same problem with cuda drivers installed. I searched all the forms for a similar problem and nothing. Here are the proofs of the driver and the error:

```
torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
ⅹ Model setup failed
root@UbuntuTest:/home/user/cog-whisper# nvidia-smi
Mon Apr 15 09:15:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti     Off | 00000000:01:00.0 Off |                  N/A |
|  0%   37C    P8               7W / 165W |      8MiB / 16380MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```
