### ISSUE TITLE
RuntimeError: The GPU device instance has been suspended

### ISSUE THREAD

**Issue by DosenSuppe** [lllyasviel/Fooocus#1230]
**Describe the problem**
I am encountering the same error as in bug-report #1069 but under a different Traceback:

My specs: 
Windows 11 
AMD (integrated graphics)
16GB RAM DDR4

**Full Console Log**
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] tree, intricate, elegant, highly detailed, wonderful perfect cute pretty, sharp focus, joyful, dramatic, elaborate, charming, expressive, sweet, adorable, background, ambient light, dynamic composition, magic, vivid colors, colorful, imposing, epic, best, fine detail, professional, fair, true artistic, romantic, unique, vibrant, beautiful, creative, positive, attractive
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] tree, colorful, precious, wonderful, elegant, breathtaking, highly detailed, dramatic light, sharp focus, fine detail, intricate, beautiful, epic, coherent, radiant colors, enhanced quality, artistic, perfect, very inspirational, color, complex, inspired, amazing composition, professional, winning, illuminated, scientific, elite, decorated, clear, outstanding, stunning, gorgeous, cinematic
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 24.04 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Traceback (most recent call last):
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\default_pipeline.py", line 355, in process_diffusion
    initial_latent['samples'].to(fcbh.model_management.get_torch_device()),
RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
Total time: 24.11 seconds

**Comment by DosenSuppe** [comment]
After I restarted my Laptop because of a Bluescreen, I now get this RuntimeError:

[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 1989772549598418531
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] tree, romantic, flowing, detailed, lucid, intricate, highly, beautiful, dramatic, modern, color, cinematic, artistic, complex, surreal, joyful, marvelous, symmetry, colorful, light, striking, wonderful, pretty, inspiring, extremely, focused, brilliant, epic, fantastic, awesome, singular, enormous, fine, very elegant, fancy, professional, creative
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] tree, surreal, dramatic, intricate detail, elegant, sharp focus, incredible fine quality, highly detailed, professional, cinematic, singular, symmetry, epic, iconic, imposing, superior, best, light, quiet, pristine, vibrant, perfect, peaceful, balanced, lovely, innocent, beautiful, illuminated, color, pretty, clear, coherent, great, magnificent, futuristic
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 24.75 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
Traceback (most recent call last):
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\core.py", line 315, in ksampler
    samples = fcbh.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\backend\headless\fcbh\sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\backend\headless\fcbh\sample.py", line 86, in prepare_sampling
    fcbh.model_management.load_models_gpu([model] + models, model.memory_required(noise_shape) + inference_memory)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\modules\patch.py", line 494, in patched_load_models_gpu
    y = fcbh.model_management.load_models_gpu_origin(*args, **kwargs)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\backend\headless\fcbh\model_management.py", line 410, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\backend\headless\fcbh\model_management.py", line 293, in model_load
    raise e
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\backend\headless\fcbh\model_management.py", line 289, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\backend\headless\fcbh\model_patcher.py", line 191, in patch_model
    temp_weight = fcbh.model_management.cast_to_device(weight, device_to, torch.float32, copy=True)
  File "C:\Users\Niklas\Desktop\ImageAi\Main\Fooocus\backend\headless\fcbh\model_management.py", line 532, in cast_to_device
    return tensor.to(device, copy=copy).to(dtype)
RuntimeError: The GPU will not respond to more commands, most likely because some other application submitted invalid commands.
The calling application should re-create the device and continue.
Total time: 80.77 seconds

**Comment by mashb1t** [comment]
Please make sure your Laptop meets the minimal requirements and you followed the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
