### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_parameters'

### ISSUE THREAD

**Issue by Greczy** [lllyasviel/Fooocus#1243]
**Describe the problem**
Hello there and thanks for the help. I am currently trying FaceSwap and there is this error i quite often get. It always crashes close to its finish and then i get the "AttributeError: 'NoneType' object has no attribute '_parameters'" Error. I cant get behind how to fix that. If anyone has an idea please let me know.
Thanks

**Full Console Log**

D:\julia\Documents\Fooocus_win64_2-1-791>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Loaded preset: D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\presets\realistic.json
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.824
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16304 MB
Set vram state to: NORMAL_VRAM
Disabling smart memory management
Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra keys {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors
Request to load LoRAs [['SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors', 0.25], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors].
Loaded LoRA [D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for UNet [D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 788 keys at weight 0.25.
Loaded LoRA [D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\models\loras\SDXL_FILM_PHOTOGRAPHY_STYLE_BetaV0.4.safetensors] for CLIP [D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\models\checkpoints\realisticStockPhoto_v10.safetensors] with 264 keys at weight 0.25.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 3.42 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 4894843950776289088
[Fooocus] Downloading control models ...
[Fooocus] Loading control models ...
extra keys clip vision: ['vision_model.embeddings.position_ids']
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 60 - 30
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] doing yoga, dynamic composition, dramatic cinematic light, epic background, colorful, highly detailed, professional quality, elegant, best, sincere, cute, innocent, imagined, beautiful, scientific, sharp focus, futuristic, thought, magic, mystical, majestic, enhanced, pretty, illuminated, glowing, celestial, radiant, bright, hopeful, vibrant, elite, designed, deep color
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] doing yoga, beautiful detailed intricate elegant highly detail complex lovely surreal sharp focus mystical flowing atmosphere background, iconic great composition, cinematic, fine balance, aesthetic, very inspirational, stunning, ambient light, dynamic dramatic professional colors, magic, vibrant, pristine, unique, cute, creative, positive, wonderful, pure, perfect, focused, thought, extremely inspiring, vivid, fantastic
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.29 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Image processing ...
Detected 1 faces
Requested to load CLIPVisionModelWithProjection
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.11 seconds
Requested to load Resampler
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.98 seconds
Requested to load To_KV
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.94 seconds
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1152, 896)
Preparation time: 25.74 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 3194.4163160324097
Traceback (most recent call last):
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\core.py", line 315, in ksampler
    samples = fcbh.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\sample.py", line 86, in prepare_sampling
    fcbh.model_management.load_models_gpu([model] + models, model.memory_required(noise_shape) + inference_memory)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\patch.py", line 494, in patched_load_models_gpu
    y = fcbh.model_management.load_models_gpu_origin(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 410, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 298, in model_load
    accelerate.dispatch_model(self.real_model, device_map=device_map, main_device=self.device)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\big_modeling.py", line 371, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 536, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 536, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 536, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 506, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\utils\modeling.py", line 292, in set_module_tensor_to_device
    new_value = old_value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 2.06 GiB is free. Of the allocated memory 2.87 GiB is allocated by PyTorch, and 140.70 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 108.57 seconds
loading in lowvram mode 940.539737701416
loading in lowvram mode 256.0
[Fooocus Model Management] Moving model(s) has taken 9.87 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 3.0
[Parameters] Seed = 7721481881066475785
[Fooocus] Downloading control models ...
[Fooocus] Loading control models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 60 - 30
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
Fooocus Expansion loaded by itself.
[Fooocus Model Management] Moving model(s) has taken 1.42 seconds
[Prompt Expansion] doing yoga, color, intricate, elegant, highly detailed, focused, sharp focus, beautiful light, epic composition, cinematic, pristine, new classic, clear background, inspired, attractive, artistic, illuminated, deep colors, amazing, surreal, fascinating, very inspirational, inspiring, novel, perfect, best, futuristic, stunning, cute, smart, thought, professional, creative
[Fooocus] Preparing Fooocus text #2 ...
Fooocus Expansion loaded by itself.
[Prompt Expansion] doing yoga, elegant intricate, highly detailed, sharp focus, colorful, cinematic, fine scenic background, professional, thought, iconic, beautiful, imposing, epic, singular, great, complex, elaborate, amazing, lucid, symmetry, illuminated, shiny, shining, bright, fancy, brilliant, colossal, enormous, spiritual, radiant, complimentary colors, perfect, marvelous, luxury
[Fooocus] Encoding positive #1 ...
Requested to load SDXLClipModel
Loading 1 new model
loading in lowvram mode 940.539737701416
[Fooocus Model Management] Moving model(s) has taken 3.07 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Image processing ...
Detected 1 faces
Requested to load CLIPVisionModelWithProjection
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 4.75 seconds
Requested to load Resampler
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 2.68 seconds
Requested to load To_KV
Loading 1 new model
loading in lowvram mode 901.9219493865967
[Fooocus Model Management] Moving model(s) has taken 4.05 seconds
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1152, 896)
Preparation time: 57.33 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 940.1611328125
[Fooocus Model Management] Moving model(s) has taken 23.43 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [08:30<00:00,  8.50s/it]
Traceback (most recent call last):
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\default_pipeline.py", line 378, in process_diffusion
    decoded_latent = core.decode_vae(vae=target_vae, latent_image=sampled_latent, tiled=tiled)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\modules\core.py", line 169, in decode_vae
    return opVAEDecode.decode(samples=latent_image, vae=vae)[0]
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\sd.py", line 217, in decode
    model_management.free_memory(memory_used, self.device)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 340, in free_memory
    m.model_unload()
  File "D:\julia\Documents\Fooocus_win64_2-1-791\Fooocus\backend\headless\fcbh\model_management.py", line 308, in model_unload
    accelerate.hooks.remove_hook_from_submodules(self.real_model)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 435, in remove_hook_from_submodules
    remove_hook_from_submodules(child)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 435, in remove_hook_from_submodules
    remove_hook_from_submodules(child)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 435, in remove_hook_from_submodules
    remove_hook_from_submodules(child)
  [Previous line repeated 3 more times]
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 433, in remove_hook_from_submodules
    remove_hook_from_module(module)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 186, in remove_hook_from_module
    module._hf_hook.detach_hook(module)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 114, in detach_hook
    module = hook.detach_hook(module)
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\hooks.py", line 313, in detach_hook
    set_module_tensor_to_device(module, name, device, value=self.weights_map.get(name, None))
  File "D:\julia\Documents\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\accelerate\utils\modeling.py", line 261, in set_module_tensor_to_device
    if tensor_name not in module._parameters and tensor_name not in module._buffers:
AttributeError: 'NoneType' object has no attribute '_parameters'

**Comment by mashb1t** [comment]
Please check if this issue still occurs in the latest version of Fooocus.
As of your logs, you have also encountered OutOfMemoryError. Please provide some information about what you were doing before you got the OutOfMemoryError and NoneType error.
Thanks!

**Comment by Greczy** [comment]
I think it might be the lowvram. At least in stable diffusion it works with low vram. I am currently not at home so I can’t test it, but I will report my tests as soon as possible. Both happened with face swap. The face I used was generated days before. Normal generation works fine and I also tried it on a better setup with more computing power and there I had no issues.

**Comment by mashb1t** [comment]
alright, feel free to reopen when providing new information
