### ISSUE TITLE
Stuck 20 batch image number on colab - memory exceed

### ISSUE THREAD

**Issue by putuoka** [lllyasviel/Fooocus#133]
![image](https://github.com/lllyasviel/Fooocus/assets/20880839/d0db5653-ede0-46d3-8745-8dd3bd159731)

```

Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 89, in worker
    handler(task)
  File "/content/Fooocus/modules/async_worker.py", line 72, in handler
    imgs = pipeline.process(p_txt, n_txt, steps, switch, width, height, seed, callback=callback)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/default_pipeline.py", line 141, in process
    sampled_latent = core.ksampler_with_refiner(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/core.py", line 225, in ksampler_with_refiner
    samples = sampler.sample(noise, positive_copy, negative_copy, refiner_positive=refiner_positive_copy,
  File "/content/Fooocus/modules/samplers_advanced.py", line 236, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/k_diffusion/sampling.py", line 644, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/k_diffusion/sampling.py", line 615, in sample_dpmpp_2m_sde
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "/content/Fooocus/modules/samplers_advanced.py", line 223, in <lambda>
    k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)
  File "/content/Fooocus/modules/samplers_advanced.py", line 168, in callback
    callback_function(step, x0, x, total_steps)
  File "/content/Fooocus/modules/core.py", line 197, in callback
    y = previewer.preview(x0, step, total_steps)
  File "/content/Fooocus/modules/core.py", line 84, in preview_function
    x_sample = taesd.decoder(torch.nn.functional.avg_pool2d(x0, kernel_size=(2, 2))).detach() * 255.0
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/taesd/taesd.py", line 23, in forward
    return self.fuse(self.conv(x) + self.skip(x))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/activation.py", line 103, in forward
    return F.relu(input, inplace=self.inplace)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 1457, in relu
    result = torch.relu(input)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 14.09 GiB
Requested               : 63.00 MiB
Device limit            : 14.75 GiB
Free (according to CUDA): 2.81 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
```

**Comment by mashb1t** [comment]
We haven't experienced this kind of error since the last 3 months. Please try again with the latest version of Fooocus on colab and feel free to reopen if still relevant..
