### ISSUE TITLE
Using MacOS with 8 GB of RAM

### ISSUE THREAD

**Issue by gabcode1712** [lllyasviel/Fooocus#1341]
Hello using MacOS M1 with 8 GB of RAM even using smart memory and split cross attention, yet I always get the same error saying that not enough RAM is available, how can I fix this issue? 

ERROR diffusion_model.output_blocks.2.0.in_layers.2.weight MPS backend out of memory (MPS allocated: 8.76 GB, other allocations: 289.91 MB, max allowed: 9.07 GB). Tried to allocate 84.38 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
ERROR diffusion_model.output_blocks.2.0.out_layers.3.weight MPS backend out of memory (MPS allocated: 8.79 GB, other allocations: 257.96 MB, max allowed: 9.07 GB). Tried to allocate 56.25 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Traceback (most recent call last):
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/modules/async_worker.py", line 803, in worker
    handler(task)
  File "/Users/gabriel/PycharmProjects/stablediff/fooocus_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/gabriel/PycharmProjects/stablediff/fooocus_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/modules/async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "/Users/gabriel/PycharmProjects/stablediff/fooocus_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/gabriel/PycharmProjects/stablediff/fooocus_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/modules/default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "/Users/gabriel/PycharmProjects/stablediff/fooocus_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/gabriel/PycharmProjects/stablediff/fooocus_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/modules/core.py", line 315, in ksampler
    samples = fcbh.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/backend/headless/fcbh/sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/backend/headless/fcbh/sample.py", line 86, in prepare_sampling
    fcbh.model_management.load_models_gpu([model] + models, model.memory_required(noise_shape) + inference_memory)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/modules/patch.py", line 494, in patched_load_models_gpu
    y = fcbh.model_management.load_models_gpu_origin(*args, **kwargs)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/backend/headless/fcbh/model_management.py", line 410, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/backend/headless/fcbh/model_management.py", line 293, in model_load
    raise e
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/backend/headless/fcbh/model_management.py", line 289, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/backend/headless/fcbh/model_patcher.py", line 191, in patch_model
    temp_weight = fcbh.model_management.cast_to_device(weight, device_to, torch.float32, copy=True)
  File "/Users/gabriel/PycharmProjects/stablediff/Fooocus/backend/headless/fcbh/model_management.py", line 532, in cast_to_device
    return tensor.to(device, copy=copy).to(dtype)
RuntimeError: MPS backend out of memory (MPS allocated: 8.78 GB, other allocations: 268.90 MB, max allowed: 9.07 GB). Tried to allocate 50.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
Total time: 84.61 seconds

**Comment by lllyasviel** [comment]
I put a temp and try 2.1.825

**Comment by Ucoz3000** [comment]
To edit launch.py And add: os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0" ![ Снимок экрана 2023-12-06 в 02 08 45](https://github.com/lllyasviel/Fooocus/assets/61644275/5b174463-4912-4c41-b0eb-7188b542541b)

**Comment by Ucoz3000** [comment]
you need approximately 30 GB of free disk space
