### ISSUE TITLE
RuntimeError: The NVIDIA driver on your system is too old (found version 9010)

### ISSUE THREAD

**Issue by SannanOfficial** [lllyasviel/Fooocus#1348]
**Read Troubleshoot**

[✅] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I am trying to run Fooocus on a Windows 10 system after installing it using `run.bat`. And I receive the attached error. I did review some similar issues on here but to no avail. Can someone help out?

**Full Console Log**
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.825
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\webui.py", line 25, in generate_clicked
    import fcbh.model_management as model_management
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\modules\patch.py", line 6, in <module>
    import fcbh.model_base
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\ldm\modules\attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\Hassan\Documents\Foocus\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\Hassan\Documents\Foocus\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by SannanOfficial** [comment]
Also, my graphics card is NVIDIA GT 630 with 2 GB of VRAM.

**Comment by mashb1t** [comment]
The error says it all, your driver is too old + the minimum required VRAM is 4GB. You're sadly out of luck and have to upgrade your GPU in order to be able to use Fooocus.
See https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md (which you already read)

**Comment by SannanOfficial** [comment]
Yes but the thing is that my driver is at the latest version ATM. I downloaded it from the nvidia website. And my bad for not reading that part, shouldn't have opened the issue without properly reading it.
