### ISSUE TITLE
No module named 'timm'

### ISSUE THREAD

**Issue by linker666** [lllyasviel/Fooocus#1387]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
when I use describe function, I got the error  No module named 'timm', but I can import timm at that enviroment.

**Full Console Log**
Traceback (most recent call last):
  File "D:\app\fooocus\python_embeded\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\app\fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "D:\app\fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\app\fooocus\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\app\fooocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\app\fooocus\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\app\fooocus\python_embeded\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "D:\app\fooocus\Fooocus\webui.py", line 527, in trigger_describe
    from extras.interrogate import default_interrogator as default_interrogator_photo
  File "D:\app\fooocus\Fooocus\extras\interrogate.py", line 10, in <module>
    from extras.BLIP.models.blip import blip_decoder
  File "D:\app\fooocus\Fooocus\extras\BLIP\models\blip.py", line 11, in <module>
    from extras.BLIP.models.vit import VisionTransformer, interpolate_pos_embed
  File "D:\app\fooocus\Fooocus\extras\BLIP\models\vit.py", line 15, in <module>
    import timm
ModuleNotFoundError: No module named 'timm'

**Comment by linker666** [comment]
by the way, I have installed timm==0.9.2

**Comment by lllyasviel** [comment]
But there is no `import timm` at `Fooocus\extras\BLIP\models\vit.py`

https://github.com/lllyasviel/Fooocus/blob/main/extras/BLIP/models/vit.py#L15

**Comment by linker666** [comment]
yes , line 15 is I added,  for test

**Comment by linker666** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/19565497/ba387b4b-fb52-4563-9b45-de8878cfdf59)

**Comment by linker666** [comment]
我就是奇怪， 为什么在这个环境下导入timm没有问题， 可在应用中就会报错

**Comment by linker666** [comment]
ok,  I got it!

**Comment by littler287** [comment]
> ok, I got it!

hi linker, how did you fix this issue?

**Comment by patricker** [comment]
I'm still seeing this error.
