### ISSUE TITLE
SD1.5 & Failsafe

### ISSUE THREAD

**Issue by NekoNyanners** [lllyasviel/Fooocus#1392]
Since a ton of models on civitai.com are based on SD1.5, is support for those models still planned? 

And one other thing: 

Often I just like to test new models but I'm not sure anymore whether those are SDXL or not, and if I happen to select a SD1.5, Fooocus just crashes. Like, selecting another model and re-running doesn't work. I have to completely close and restart fooocus. I'm not sure if a fix for that is as simple as a try/catch but would be cool if it doesn't just hard-crash

**Comment by lllyasviel** [comment]
Currently the only way to use SD1.5 in Fooocus is using Fooocus's unique swap algrithom to combine SDXL and SD1.5. You can use SD1.5 as a refiner and set switch to number like 0.4. 

This swap sampling algrithom only exists in Fooocus and other software do not have it.

Model mismatch will not crash. Check if you are using official and latest version.

**Comment by NekoNyanners** [comment]
Thanks for the heads up with the SD1.5 models! 

Regarding the crash: I'm on the latest release `Fooocus_win64_2-1-831` but when I try to use an unsupported model I get

```
NotImplementedError: You have selected base model other than SDXL. This is not supported yet.
Exception in thread Thread-3 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\neko\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 809, in worker
    pipeline.prepare_text_encoder(async_call=True)
  File "C:\Users\neko\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\neko\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\neko\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 210, in prepare_text_encoder
    assert_model_integrity()
  File "C:\Users\neko\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\neko\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\neko\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 53, in assert_model_integrity
    raise NotImplementedError(error_message)
NotImplementedError: You have selected base model other than SDXL. This is not supported yet.
```

And the UI becomes unresponsive. If I then select a working model such as the default one, nothing happens. Neither in the terminal nor in the UI

**Comment by mashb1t** [comment]
same for me, also using the refiner as base model causes the app to crash and stay in a non-recoverable state.

**Comment by lllyasviel** [comment]
nice catch

**Comment by lllyasviel** [comment]
and fixed

**Comment by vanguard-bit** [comment]
thanks....had the same problem
