### ISSUE TITLE
Dependency conflicts between numpy and onnxruntime

### ISSUE THREAD

**Issue by dominickp** [lllyasviel/Fooocus#1413]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
There is a dependency conflicts between numpy and onnxruntime that seems to occur when I install Fooocus now.

Note: I'm not using the official installer, I'm using https://hub.docker.com/r/holaflenain/stable-diffusion. But I don't think that really matters in this case.

**Full Console Log**
```
fooocus  | INFO: pip is looking at multiple versions of onnxruntime to determine which version is compatible with other requirements. This could take a while.
fooocus  | ERROR: Cannot install -r requirements_versions.txt (line 1), -r requirements_versions.txt (line 12), -r requirements_versions.txt (line 14), -r requirements_versions.txt (line 16), -r requirements_versions.txt (line 18), -r requirements_versions.txt (line 3), -r requirements_versions.txt (line 5), -r requirements_versions.txt (line 8) and numpy==1.23.5 because these package versions have conflicting dependencies.
fooocus  |
fooocus  | The conflict is caused by:
fooocus  |     The user requested numpy==1.23.5
fooocus  |     torchsde 0.2.5 depends on numpy>=1.19.*; python_version >= "3.7"
fooocus  |     transformers 4.30.2 depends on numpy>=1.17
fooocus  |     accelerate 0.21.0 depends on numpy>=1.17
fooocus  |     scipy 1.9.3 depends on numpy<1.26.0 and >=1.18.5
fooocus  |     pytorch-lightning 1.9.4 depends on numpy>=1.17.2
fooocus  |     gradio 3.41.2 depends on numpy~=1.0
fooocus  |     opencv-contrib-python 4.8.0.74 depends on numpy>=1.21.2; python_version >= "3.10"
fooocus  |     opencv-contrib-python 4.8.0.74 depends on numpy>=1.23.5; python_version >= "3.11"
fooocus  |     opencv-contrib-python 4.8.0.74 depends on numpy>=1.17.0; python_version >= "3.7"
fooocus  |     opencv-contrib-python 4.8.0.74 depends on numpy>=1.17.3; python_version >= "3.8"
fooocus  |     opencv-contrib-python 4.8.0.74 depends on numpy>=1.19.3; python_version >= "3.9"
fooocus  |     onnxruntime 1.16.3 depends on numpy>=1.24.2
fooocus  |
fooocus  | To fix this you could try to:
fooocus  | 1. loosen the range of package versions you've specified
fooocus  | 2. remove package versions to allow pip attempt to solve the dependency conflict
fooocus  |
fooocus  | ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
fooocus  | [System ARGV] ['launch.py', '--listen', '0.0.0.0', '--port', '9000']
fooocus  | Traceback (most recent call last):
fooocus  |   File "/opt/stable-diffusion/06-Fooocus/Fooocus/launch.py", line 24, in <module>
fooocus  |     from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
fooocus  |   File "/opt/stable-diffusion/06-Fooocus/Fooocus/modules/config.py", line 7, in <module>
fooocus  |     import modules.sdxl_styles
fooocus  |   File "/opt/stable-diffusion/06-Fooocus/Fooocus/modules/sdxl_styles.py", line 5, in <module>
fooocus  |     from modules.util import get_files_from_folder
fooocus  |   File "/opt/stable-diffusion/06-Fooocus/Fooocus/modules/util.py", line 1, in <module>
fooocus  |     import numpy as np
fooocus  | ModuleNotFoundError: No module named 'numpy'
fooocus exited with code 1
```

**Comment by mashb1t** [comment]
related to https://forums.unraid.net/topic/143645-support-stable-diffusion-advanced/page/5/

Please check your python version and make sure it's 3.10 and not 3.11.

numpy==1.21.6 ; python_version < '3.11'
numpy==1.24.2 ; python_version >= '3.11'
https://github.com/search?q=repo%3Amicrosoft%2Fonnxruntime%201.24.2&type=code

It works locally for me even after removing and adding onnxruntime 1.16.3 again with numpy 1.23.5

**Comment by lllyasviel** [comment]
let me know what version should be "correct" version
never have a problem in all my tests on 6 different devices of different windows and linux and colab

**Comment by dominickp** [comment]
Thanks guys, it was using Python 3.11 and switching to Python 3.10 resolved it.
