### ISSUE TITLE
Crashing / Memory allocation error

### ISSUE THREAD

**Issue by Sandboxieh** [lllyasviel/Fooocus#1447]
I freshly Installed but I'm getting some crazy lag when in Moving to GPU phase then it crashes, no errors I couldn't get it to work, I tried with --always-gpu and now i'm getting  a cuda error, log is below please help.

CPU: Ryzen 7 4800H
Ram: 16GB
GPU: GTX 1660 TI

Is it a VRAM problem? I don't understand what's the issue, now I can't start any generation, "Waiting for task to start ...", while I have these errors in console.

Please help, many thanks!

Log:
C:\Users\sandb\Downloads\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --always-gpu
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--always-gpu']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.843
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16253 MB
Set vram state to: HIGH_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 253, in <module>
    refresh_everything(
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 233, in refresh_everything
    refresh_base_model(base_model_name)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 69, in refresh_base_model
    model_base = core.load_model(filename)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\core.py", line 151, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sd.py", line 457, in load_checkpoint_guess_config
    model = model_config.get_model(sd, "model.diffusion_model.", device=inital_load_device)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\supported_models.py", line 173, in get_model
    out = model_base.SDXL(self, model_type=self.model_type(state_dict, prefix), device=device)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_base.py", line 264, in __init__
    super().__init__(model_config, model_type, device=device)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_base.py", line 52, in __init__
    self.diffusion_model = UNetModel(**unet_config, device=device, operations=operations)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 780, in __init__
    get_attention_layer(
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 563, in get_attention_layer
    return SpatialTransformer(
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\attention.py", line 577, in __init__
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim[d],
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\attention.py", line 577, in <listcomp>
    [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim[d],
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\attention.py", line 407, in __init__
    self.ff = FeedForward(inner_dim, dim_out=dim, dropout=dropout, glu=gated_ff, dtype=dtype, device=device, operations=operations)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\attention.py", line 81, in __init__
    operations.Linear(inner_dim, dim_out, dtype=dtype, device=device)
  File "C:\Users\sandb\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free. Of the allocated memory 5.19 GiB is allocated by PyTorch, and 126.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by mashb1t** [comment]
see https://github.com/lllyasviel/Fooocus/issues/1426#issuecomment-1858254306 + https://github.com/lllyasviel/Fooocus/tree/main?tab=readme-ov-file#minimal-requirement
What is the exact error when not using `--always-gpu`? This way we're able to identify if we can remove `(* 6GB uncertain)` from the list.
