### ISSUE TITLE
1.0.31 seems have some problem

### ISSUE THREAD

**Issue by Phrixus2023** [lllyasviel/Fooocus#145]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 16175 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2070 with Max-Q Design : cudaMallocAsync
Using xformers cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 15, in worker
    import modules.default_pipeline as pipeline
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\Fooocus\modules\default_pipeline.py", line 101, in <module>
    refresh_base_model(modules.path.default_base_model_name)
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\Fooocus\modules\default_pipeline.py", line 30, in refresh_base_model
    xl_base = core.load_model(filename)
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\BaiduNetdiskDownload\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by zidannab** [comment]
up, need some solution

**Comment by mashb1t** [comment]
Solution: see https://github.com/lllyasviel/Fooocus/issues/147 (https://github.com/lllyasviel/Fooocus/issues/147#issuecomment-1680449987)
