### ISSUE TITLE
  ModuleNotFoundError: No module named 'ffmpy'

### ISSUE THREAD

**Issue by Tigwin** [lllyasviel/Fooocus#15]
Any idea what needs to be done?

C:\StableDiffusion>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 1.0.15
Inference Engine exists.
Inference Engine checkout finished.
Installing requirements
Traceback (most recent call last):
  File "C:\StableDiffusion\Fooocus\entry_with_update.py", line 45, in <module>
    from launch import *
  File "C:\StableDiffusion\Fooocus\launch.py", line 75, in <module>
    prepare_environment()
  File "C:\StableDiffusion\Fooocus\launch.py", line 49, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements")
  File "C:\StableDiffusion\Fooocus\modules\launch_util.py", line 94, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}",
  File "C:\StableDiffusion\Fooocus\modules\launch_util.py", line 87, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements.
Command: "C:\StableDiffusion\python_embeded\python.exe" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Requirement already satisfied: torchsde==0.2.5 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from -r requirements_versions.txt (line 1)) (0.2.5)
Collecting einops==0.4.1 (from -r requirements_versions.txt (line 2))
  Using cached einops-0.4.1-py3-none-any.whl (28 kB)
Collecting transformers==4.30.2 (from -r requirements_versions.txt (line 3))
  Obtaining dependency information for transformers==4.30.2 from https://files.pythonhosted.org/packages/5b/0b/e45d26ccd28568013523e04f325432ea88a442b4e3020b757cf4361f0120/transformers-4.30.2-py3-none-any.whl.metadata
  Using cached transformers-4.30.2-py3-none-any.whl.metadata (113 kB)
Requirement already satisfied: safetensors==0.3.1 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from -r requirements_versions.txt (line 4)) (0.3.1)
Collecting accelerate==0.21.0 (from -r requirements_versions.txt (line 5))
  Obtaining dependency information for accelerate==0.21.0 from https://files.pythonhosted.org/packages/70/f9/c381bcdd0c3829d723aa14eec8e75c6c377b4ca61ec68b8093d9f35fc7a7/accelerate-0.21.0-py3-none-any.whl.metadata
  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: pyyaml==6.0 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from -r requirements_versions.txt (line 6)) (6.0)
Collecting Pillow==9.2.0 (from -r requirements_versions.txt (line 7))
  Using cached Pillow-9.2.0-cp310-cp310-win_amd64.whl (3.3 MB)
Collecting scipy==1.9.3 (from -r requirements_versions.txt (line 8))
  Using cached scipy-1.9.3-cp310-cp310-win_amd64.whl (40.1 MB)
Collecting tqdm==4.64.1 (from -r requirements_versions.txt (line 9))
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting psutil==5.9.5 (from -r requirements_versions.txt (line 10))
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
Requirement already satisfied: opencv-python==4.7.0.72 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from -r requirements_versions.txt (line 11)) (4.7.0.72)
Requirement already satisfied: numpy==1.23.5 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from -r requirements_versions.txt (line 12)) (1.23.5)
Collecting pytorch_lightning==1.9.4 (from -r requirements_versions.txt (line 13))
  Using cached pytorch_lightning-1.9.4-py3-none-any.whl (827 kB)
Collecting omegaconf==2.2.3 (from -r requirements_versions.txt (line 14))
  Using cached omegaconf-2.2.3-py3-none-any.whl (79 kB)
Collecting gradio==3.39.0 (from -r requirements_versions.txt (line 15))
  Obtaining dependency information for gradio==3.39.0 from https://files.pythonhosted.org/packages/82/5f/c815ae438b63ca8b7418acf470369493bac5aa267192702c8601ca67966b/gradio-3.39.0-py3-none-any.whl.metadata
  Using cached gradio-3.39.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: boltons>=20.2.1 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (23.0.0)
Requirement already satisfied: torch>=1.6.0 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (2.0.1+cu118)
Requirement already satisfied: trampoline>=0.1.2 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (0.1.2)
Requirement already satisfied: filelock in c:\users\2700x\appdata\roaming\python\python310\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (0.16.4)
Requirement already satisfied: packaging>=20.0 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (23.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (2022.10.31)
Requirement already satisfied: requests in c:\users\2700x\appdata\roaming\python\python310\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (2.28.2)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (0.13.2)
Requirement already satisfied: colorama in c:\users\2700x\appdata\roaming\python\python310\site-packages (from tqdm==4.64.1->-r requirements_versions.txt (line 9)) (0.4.6)
Requirement already satisfied: fsspec[http]>2021.06.0 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 13)) (2023.6.0)
Requirement already satisfied: torchmetrics>=0.7.0 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 13)) (0.11.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 13)) (4.5.0)
Collecting lightning-utilities>=0.6.0.post0 (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 13))
  Obtaining dependency information for lightning-utilities>=0.6.0.post0 from https://files.pythonhosted.org/packages/46/ee/8641eeb6a062f383b7d6875604e1f3f83bd2c93a0b4dbcabd3150b32de6e/lightning_utilities-0.9.0-py3-none-any.whl.metadata
  Using cached lightning_utilities-0.9.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\users\2700x\appdata\roaming\python\python310\site-packages (from omegaconf==2.2.3->-r requirements_versions.txt (line 14)) (4.9.3)
Collecting aiofiles<24.0,>=22.0 (from gradio==3.39.0->-r requirements_versions.txt (line 15))
  Obtaining dependency information for aiofiles<24.0,>=22.0 from https://files.pythonhosted.org/packages/c5/19/5af6804c4cc0fed83f47bff6e413a98a36618e7d40185cd36e69737f3b0e/aiofiles-23.2.1-py3-none-any.whl.metadata
  Using cached aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: aiohttp~=3.0 in c:\users\2700x\appdata\roaming\python\python310\site-packages (from gradio==3.39.0->-r requirements_versions.txt (line 15)) (3.8.4)
Collecting altair<6.0,>=4.2.0 (from gradio==3.39.0->-r requirements_versions.txt (line 15))
  Obtaining dependency information for altair<6.0,>=4.2.0 from https://files.pythonhosted.org/packages/b2/20/5c3b89d6f8d9938325a9330793438389e0dc94c34d921f6da35ec62095f3/altair-5.0.1-py3-none-any.whl.metadata
  Using cached altair-5.0.1-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: fastapi in c:\users\2700x\appdata\roaming\python\python310\site-packages (from gradio==3.39.0->-r requirements_versions.txt (line 15)) (0.88.0)
Collecting ffmpy (from gradio==3.39.0->-r requirements_versions.txt (line 15))
  Using cached ffmpy-0.3.1.tar.gz (5.5 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "E:\tmp\pip-install-yqg7nw9y\ffmpy_5050bf8fc012433b9206adaf3d432812\setup.py", line 4, in <module>
      from ffmpy import __version__
  ModuleNotFoundError: No module named 'ffmpy'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Tigwin** [comment]
ahhh, nevermind. I had a different python_embeded/ installed in my stablediffusion folder, and the file versions must be different or something. Soon as I extracted your copy of python_embeded/, it proceeded. Leaving this issue up in case anyone else runs into the same problem.
