### ISSUE TITLE
Problems with installation and correct operation.

### ISSUE THREAD

**Issue by Mobian2388329** [lllyasviel/Fooocus#1508]
Hello, I had problems installing Fooocus on a GNU/Linux system, many errors occurred during the installation and they were all different.  I was not able to capture some of them, but in general terms the errors were as follows: "could not find versions of python packages that satisfy dependencies (error during installation)","(when clicking the "generate" button) "nvidia drivers were not available  found, make sure you have them installed "link to official website".

I managed to save the output of the following errors:

ERROR: Could not find a version that satisfies the requirement accelerate==0.21.0 (from -r requirements_versions.txt (line 5)) (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3)
ERROR: No matching distribution found for accelerate==0.21.0 (from -r requirements_versions.txt (line 5))

python entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Fooocus version: 2.1.853
Running on local URL:  http://127.0.0.1:7865

To create a public link, set share=True in launch().
Total VRAM 12006 MB, total RAM 31850 MB
xformers version: 0.0.16
Traceback (most recent call last):
  File "/home/dragon_flow/Fooocus/ldm_patched/modules/model_management.py", line 222, in <module>
    import accelerate
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 125, in evaluate_cuda_setup
    cuda_version_string = get_cuda_version(cuda, cudart_path)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 45, in get_cuda_version
    check_cuda_result(cuda, cudart.cudaRuntimeGetVersion(ctypes.byref(version)))
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/ctypes/__init__.py", line 387, in getattr
    func = self.getitem(name)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/ctypes/__init__.py", line 392, in getitem
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: cudaRuntimeGetVersion

ERROR: LOW VRAM MODE NEEDS accelerate.
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : 
VAE dtype: torch.float32
Using xformers cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.name)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/transformers/modeling_utils.py", line 85, in <module>
    from accelerate import version as accelerate_version
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)

File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 125, in evaluate_cuda_setup
    cuda_version_string = get_cuda_version(cuda, cudart_path)
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 45, in get_cuda_version
    check_cuda_result(cuda, cudart.cudaRuntimeGetVersion(ctypes.byref(version)))
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/ctypes/__init__.py", line 387, in getattr
    func = self.getitem(name)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/ctypes/__init__.py", line 392, in getitem
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: cudaRuntimeGetVersion

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dragon_flow/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/home/dragon_flow/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/home/dragon_flow/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/home/dragon_flow/Fooocus/modules/patch.py", line 29, in <module>
    from modules.patch_clip import patch_all_clip
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/dragon_flow/Fooocus/modules/patch_clip.py", line 23, in <module>
    from transformers import CLIPTextModel, CLIPTextConfig, modeling_utils, CLIPVisionConfig, CLIPVisionModelWithProjection
  File "/home/dragon_flow/.local/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1077, in getattr
    value = getattr(module, name)
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1076, in getattr
    module = self._get_module(self._class_to_module[name])
  File "/home/dragon_flow/anaconda3/envs/fooocus/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1088, in _get_module
    raise RuntimeError(

RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
python: undefined symbol: cudaRuntimeGetVersion

**Comment by mashb1t** [comment]
@Mobian2388329 Fooocus requires accelerate==0.21.0 (see https://github.com/lllyasviel/Fooocus/blob/main/requirements_versions.txt#L5). Please make sure this version is installed in the python venv.

You can always manually try to instal the package again by activating the venv and running `pip install accelerate==0.21.0`.
Make sure you're using an official installer though as we only support the ones mentioned in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#download

**Comment by Mobian2388329** [comment]
Unfortunately, it didn't work in my case. The error is as follows:




ERROR: The following versions requiring a different version of python are ignored: 0.21.0 Requires-Python >=3.8.0; 0.22.0 Requires-Python >=3.8.0; 0.23.0 Requires-Python >=3.8.0; 0.24.0 Requires-Python >=3.8.0; 0.24.1 Requires-Python >=3.8.0; 0.25.0 Requires-Python >=3.8.0
ERROR: Failed to find a version satisfying accelerate==0.21.0 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3)
ERROR: No suitable distribution found for accelerate==0.21.0
Переведено с помощью DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by Mobian2388329** [comment]
Unfortunately, it didn't work in my case. The error is as follows:




ERROR: The following versions requiring a different version of python are ignored: 0.21.0 Requires-Python >=3.8.0; 0.22.0 Requires-Python >=3.8.0; 0.23.0 Requires-Python >=3.8.0; 0.24.0 Requires-Python >=3.8.0; 0.24.1 Requires-Python >=3.8.0; 0.25.0 Requires-Python >=3.8.0
ERROR: Failed to find a version satisfying accelerate==0.21.0 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3)
ERROR: No suitable distribution found for accelerate==0.21.0

**Comment by mashb1t** [comment]
Make sure you're using Python 3.10, it seems like you're using < 3.8.0.
