### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled - Mac

### ISSUE THREAD

**Issue by ardamoin** [lllyasviel/Fooocus#1567]
I'm running the program on my Mac and didn't have any issues during installation. But when I try to prompt an image, the web ui returns an error. And I get the following message on the terminal: 

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ArdaMoin/repos/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/Users/ArdaMoin/repos/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/Users/ArdaMoin/repos/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/Users/ArdaMoin/repos/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 18, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/ldm/modules/attention.py", line 12, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/modules/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/modules/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/ArdaMoin/repos/Fooocus/webui.py", line 27, in generate_clicked
    import ldm_patched.modules.model_management as model_management
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/modules/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/Users/ArdaMoin/repos/Fooocus/ldm_patched/modules/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/Users/ArdaMoin/repos/Fooocus/fooocus_env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Any idea how I can fix this?

**Comment by Lilneo786** [comment]
1:)  Check whether your system has NVIDIA GPU hardware and CUDA drivers installed. 

2:) If you do not have a GPU or CUDA drivers installed, you can install a CPU-only version of PyTorch, which does not require GPU support. You can install it using pip:

`pip install torch==1.9.0+cpu torchvision==0.10.0+cpu torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`

If this doesn't work please let me know.

**Comment by devope** [comment]
Worked: `python3 entry_with_update.py --always-cpu`
But it is VERY slow
Macbook Air M1  (Virtual machine – Ubuntu 23.10)

**Comment by Lilneo786** [comment]
I'm sorry its slow. Consider another VM?

**Comment by ardamoin** [comment]
> Worked: `python3 entry_with_update.py --always-cpu` But it is VERY slow Macbook Air M1 (Virtual machine – Ubuntu 23.10)

Same here. Works when i run it with --always-cpu but super slow. Thanks a lot for the help anyways @Lilneo786 and @devope.

**Comment by Edion-Liu** [comment]
> > Worked: `python3 entry_with_update.py --always-cpu` But it is VERY slow Macbook Air M1 (Virtual machine – Ubuntu 23.10)
> 
> Same here. Works when i run it with --always-cpu but super slow. Thanks a lot for the help anyways @Lilneo786 and @devope.

有什么办法快点，我现在也是很慢，基于 MAC air intel
