### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by jwvanderbeck** [lllyasviel/Fooocus#1643]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

I did read the troubleshooting section and for this error it says to set System Swap to 40GB.  However it also says on Windows 11 if it is set to automanage, which mine is, then to leave it alone.

I have 64GB of system ram and 24GB of GPU ram. I don't see any indications of an out of memory condition, so this seems like a false flag.  

**Describe the problem**

**Full Console Log**
G:\_Applications\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.856
Running on local URL:  http://127.0.0.1:7866
Traceback (most recent call last):
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 705, in readinto
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7866): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\_Applications\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "G:\_Applications\Fooocus\Fooocus\launch.py", line 109, in <module>
    from webui import *
  File "G:\_Applications\Fooocus\Fooocus\webui.py", line 599, in <module>
    shared.gradio_root.launch(
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1968, in launch
    and not networking.url_ok(self.local_url)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\gradio\networking.py", line 202, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "G:\_Applications\Fooocus\python_embeded\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7866): Read timed out. (read timeout=3)

**Comment by jwvanderbeck** [comment]
My bad, closing this.  Turns out the problem was with my NAS
