### ISSUE TITLE
Cuda out of memory in high vram mode

### ISSUE THREAD

**Issue by docppp** [lllyasviel/Fooocus#1684]
Fooocus crashed due to low vram, but my rtx2060 should be enough due to minimal req. Is this some sort of bug or expected behavior? Note that i have added `--always-high-vram` option.

GPU:
Driver version: 531.18
Total memory: 14299 MB
Video memory: 6144 MB GDDR6
Shared memory: 8155 MB

RAM:
16 GB

```
C:\Users\docp\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --always-high-vram
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--always-high-vram']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.854
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 6144 MB, total RAM 16311 MB
Set vram state to: HIGH_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
ARGS
('dog', '', ['Fooocus V2', 'Fooocus Enhance', 'Fooocus Sharp'], 'Speed', '1152×896 <span style="color: grey;"> ∣ 9:7</span>', 2, '1807193655037735135', 2, 4, 'juggernautXL_version6Rundiffusion.safetensors', 'None', 0.5, 'sd_xl_offset_example-lora_1.0.safetensors', 0.1, 'None', 1, 'None', 1, 'None', 1, 'None', 1, False, 'uov', 'Disabled', None, [], None, '', None, 0.5, 0.6, 'ImagePrompt', None, 0.5, 0.6, 'ImagePrompt', None, 0.5, 0.6, 'ImagePrompt', None, 0.5, 0.6, 'ImagePrompt')
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Base model loaded: C:\Users\docp\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\docp\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [C:\Users\docp\Fooocus\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\docp\Fooocus\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\docp\Fooocus\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\docp\Fooocus\Fooocus\modules\default_pipeline.py", line 253, in <module>
    refresh_everything(
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\docp\Fooocus\Fooocus\modules\default_pipeline.py", line 248, in refresh_everything
    prepare_text_encoder(async_call=True)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\docp\Fooocus\Fooocus\modules\default_pipeline.py", line 211, in prepare_text_encoder
    ldm_patched.modules.model_management.load_models_gpu([final_clip.patcher, final_expansion.patcher])
  File "C:\Users\docp\Fooocus\Fooocus\modules\patch.py", line 441, in patched_load_models_gpu
    y = ldm_patched.modules.model_management.load_models_gpu_origin(*args, **kwargs)
  File "C:\Users\docp\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 414, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "C:\Users\docp\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 297, in model_load
    raise e
  File "C:\Users\docp\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 293, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
  File "C:\Users\docp\Fooocus\Fooocus\ldm_patched\modules\model_patcher.py", line 209, in patch_model
    self.model.to(device_to)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "C:\Users\docp\Fooocus\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free. Of the allocated memory 5.16 GiB is allocated by PyTorch, and 134.01 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by mashb1t** [comment]
Please remove `--always-high-vram` and follow the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md.
Feel free to reopen if the issue still persists after doing adjustments.
