### ISSUE TITLE
torch import error on freshly installed Fooocus with appropriate python and Nvidia driver version.

### ISSUE THREAD

**Issue by frederikjchristensen** [lllyasviel/Fooocus#1714]
I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

I've been getting an error for importing from the torch library and i don't understand why it persist.

**I'm on a Lenovo Legion 15, Nvidia RTX 3700 mobile.**
- I've ensured the swap set according to instructions.
- I've changed from python 3.12 to 3.10 as mentioned in trouble shooting.
- I've ran the requirements_versions.txt ensuring every library is installed and at the version required.
- I've tried also upgrading said libraries to the latest.
- I've ensured my NVidia driver was downgraded to 531 as mentioned in trouble shooting.

**FULL LOG**

D:\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.859
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 16236 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\transformers\modeling_utils.py", line 85, in <module>
    from accelerate import __version__ as accelerate_version
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\accelerate\utils\__init__.py", line 132, in <module>
    from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\accelerate\utils\fsdp_utils.py", line 24, in <module>
    import torch.distributed.checkpoint as dist_cp
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\distributed\checkpoint\__init__.py", line 7, in <module>
    from .state_dict_loader import load_state_dict
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\distributed\checkpoint\state_dict_loader.py", line 10, in <module>
    from .default_planner import DefaultLoadPlanner
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\distributed\checkpoint\default_planner.py", line 37, in <module>
    from torch.distributed.checkpoint.planner_helpers import (
ImportError: cannot import name '_create_read_items' from 'torch.distributed.checkpoint.planner_helpers' (D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\distributed\checkpoint\planner_helpers.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\patch.py", line 29, in <module>
    from modules.patch_clip import patch_all_clip
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\patch_clip.py", line 22, in <module>
    from transformers import CLIPTextModel, CLIPTextConfig, modeling_utils, CLIPVisionConfig, CLIPVisionModelWithProjection
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1077, in __getattr__
    value = getattr(module, name)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
cannot import name '_create_read_items' from 'torch.distributed.checkpoint.planner_helpers' (D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\distributed\checkpoint\planner_helpers.py)

**Comment by mashb1t** [comment]
For further analysis: Which version of torch are you using?

**Comment by frederikjchristensen** [comment]
> For further analysis: Which version of torch are you using?

2.1.2+cpu

**Comment by frederikjchristensen** [comment]
> For further analysis: Which version of torch are you using?
2.1.2+cpu

**Comment by lllyasviel** [comment]
We do not provide any support for unofficial ways to install the software, and this user is using wrong install method.

For windows users, we never provided any installation guide that requires users to install any python envs or packages.

If users think they are skilled enough to ignore official installation guide, then they should manage all errors themselves.

Feel free to reopen this issue if user have problems when following official installation guide.

official installation guide:
https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#windows
