### ISSUE TITLE
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7897/')

### ISSUE THREAD

**Issue by KaJ1L** [lllyasviel/Fooocus#1745]
**Read Troubleshoot**

I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I use RX6600 on Ubuntu 22.4.3. I installed fooocus and pytorch according to the instructions. No errors during installation.

**Full Console Log**
(fooocus) kaj1l@KAJ1L-PC:~/Fooocus$ python entry_with_update.py --listen
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--listen']
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Fooocus version: 2.1.860
Installing requirements
Traceback (most recent call last):
  File "/home/kaj1l/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/kaj1l/Fooocus/launch.py", line 109, in <module>
    from webui import *
  File "/home/kaj1l/Fooocus/webui.py", line 1, in <module>
    import gradio as gr
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 353, in <module>
    class AsyncRequest:
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/httpx/_client.py", line 1395, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/httpx/_client.py", line 216, in _get_proxy_map
    return {
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/httpx/_client.py", line 217, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/kaj1l/miniconda3/envs/fooocus/lib/python3.10/site-packages/httpx/_config.py", line 336, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7897/')

**Comment by KaJ1L** [comment]
Wait. I reboot system, then I run code“HF_ENDPOINT=https:hf-mirror.com python3 entry_with_update.py --listen", and then the problem is solved. Now, I can open Fooocus webui.

**Comment by tan-jiaqi** [comment]
just close vpn
