### ISSUE TITLE
error when generating 

### ISSUE THREAD

**Issue by Riccky39** [lllyasviel/Fooocus#1835]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I have downloaded everything and done the correct steps for system swap, when I run the software and type any promt and click generate, I instantly get error. Ive tried different browsers but the error is still there.
<img width="1128" alt="Screenshot 2024-01-09 140422" src="https://github.com/lllyasviel/Fooocus/assets/127784922/a52f754a-4709-4460-be4d-91b9f0031bb1">

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
> Paste full console log here. You will make our job easier if you give a full log.

Please provide the full terminal output after following the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md if still necessary

**Comment by Riccky39** [comment]
I dont have any issue on the terminal, it was all installed fine without trouble. Its just at the time of trying to use the software that I cant generate anything

**Comment by mashb1t** [comment]
please send the output when running the entrypoint command until to the point where you encounter the error (run.bat, entry_with_update.py, etc.). Only when providing this we're able to help you.

**Comment by Riccky39** [comment]
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] CAR\, confident, extremely detailed, artistic, cinematic, breathtaking, beautiful composition, dramatic, intricate, elegant, highly saturated colors, glowing, sharp focus, epic light, aesthetic, very inspirational, original, fine detail, clear, color, perfect background, colorful, inspiring, attractive, true, full, whole, joyful, thought, ambient, novel, atmosphere infinite
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] CAR\, highly detailed, excellent composition, dramatic atmosphere, dynamic cinematic light, precise perfect artistic color, aesthetic, very inspirational, vibrant colors, inspiring, brave, amazing, noble, fine detail, stunning, creative, winning new, novel, best, classic, modern, clear, crisp, sharp, inspired, futuristic, epic, fantastic, cute, lovely, ambient background
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 70.81 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 64.0
[Fooocus Model Management] Moving model(s) has taken 207.25 seconds
  0%|                                                                                           | 0/30 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\ricar\Downloads\Fooocus\modules\async_worker.py", line 823, in worker
    handler(task)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\async_worker.py", line 754, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\core.py", line 313, in ksampler
    samples = ldm_patched.modules.sample.sample(model,
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\sample.py", line 101, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\sample_hijack.py", line 157, in sample_hacked
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback_wrap, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 561, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\k_diffusion\sampling.py", line 701, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\k_diffusion\sampling.py", line 613, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\patch.py", line 314, in patched_KSamplerX0Inpaint_forward
    out = self.inner_model(x, sigma,
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "C:\Users\ricar\Downloads\Fooocus\modules\patch.py", line 229, in patched_sampling_function
    positive_x0, negative_x0 = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 226, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\patch.py", line 371, in patched_unet_forward
    self.current_step = 1.0 - timesteps.to(x) / 999.0
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\_tensor.py", line 40, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\_tensor.py", line 848, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: The GPU device does not support Double (Float64) operations!
Total time: 379.68 seconds

**Comment by mashb1t** [comment]
> Paste **full** console log here. You will make our job easier if you give a **full** log.

I assume you're running Fooocus with a non-supported GPU or with arguments. Please provide the FULL log, from line 1 incl. entrypoint etc.) so the system specs and arguments are visible. Thanks!

**Comment by Riccky39** [comment]
PS C:\Users\ricar\Downloads> .\python_embeded\python.exe -s Fooocus\entry_with_update.py --directml
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--directml']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Using directml with device:
Total VRAM 1024 MB, total RAM 15970 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --attention-split
Refiner unloaded.
model_type EPS
UNet ADM Dimension 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: C:\Users\ricar\Downloads\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\ricar\Downloads\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors].
Loaded LoRA [C:\Users\ricar\Downloads\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\ricar\Downloads\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.16 seconds
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 6841972988630782288
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] CAR\, confident, extremely detailed, artistic, cinematic, breathtaking, beautiful composition, dramatic, intricate, elegant, highly saturated colors, glowing, sharp focus, epic light, aesthetic, very inspirational, original, fine detail, clear, color, perfect background, colorful, inspiring, attractive, true, full, whole, joyful, thought, ambient, novel, atmosphere infinite
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] CAR\, highly detailed, excellent composition, dramatic atmosphere, dynamic cinematic light, precise perfect artistic color, aesthetic, very inspirational, vibrant colors, inspiring, brave, amazing, noble, fine detail, stunning, creative, winning new, novel, best, classic, modern, clear, crisp, sharp, inspired, futuristic, epic, fantastic, cute, lovely, ambient background
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (896, 1152)
Preparation time: 70.81 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 64.0
[Fooocus Model Management] Moving model(s) has taken 207.25 seconds
  0%|                                                                                           | 0/30 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\ricar\Downloads\Fooocus\modules\async_worker.py", line 823, in worker
    handler(task)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\async_worker.py", line 754, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\core.py", line 313, in ksampler
    samples = ldm_patched.modules.sample.sample(model,
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\sample.py", line 101, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\sample_hijack.py", line 157, in sample_hacked
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback_wrap, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 561, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\k_diffusion\sampling.py", line 701, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\k_diffusion\sampling.py", line 613, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\patch.py", line 314, in patched_KSamplerX0Inpaint_forward
    out = self.inner_model(x, sigma,
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "C:\Users\ricar\Downloads\Fooocus\modules\patch.py", line 229, in patched_sampling_function
    positive_x0, negative_x0 = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\samplers.py", line 226, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\Users\ricar\Downloads\Fooocus\ldm_patched\modules\model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ricar\Downloads\Fooocus\modules\patch.py", line 371, in patched_unet_forward
    self.current_step = 1.0 - timesteps.to(x) / 999.0
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\_tensor.py", line 40, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\ricar\Downloads\python_embeded\lib\site-packages\torch\_tensor.py", line 848, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: The GPU device does not support Double (Float64) operations!
Total time: 379.68 seconds

**Comment by mashb1t** [comment]
As of your log, the GPU you're using only offers

> Total VRAM 1024 MB

which is insufficient. Please provide the model of the GPU and check the minimal requirements [here](https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement).

**Comment by Riccky39** [comment]
<img width="573" alt="Screenshot 2024-01-09 152126" src="https://github.com/lllyasviel/Fooocus/assets/127784922/b860c880-33aa-467d-ad6c-9981ef47d470">

**Comment by mashb1t** [comment]
Sorry, but Fooocus currently doesn't support any Intel graphics cards (neither integrated nor ARC), also see https://github.com/lllyasviel/Fooocus/issues/141.
Closing this issue for now.

**Comment by vivekratr** [comment]
> can i use GTX-1650ti 4gb for using it?

**Comment by mashb1t** [comment]
@vivekratr please find the minimal requirements here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement
You might be able to run Fooocus with `--always-cpu` though.
