### ISSUE TITLE
RuntimeError: CUDA error: operation not supported & UserWarning: TypedStorage 

### ISSUE THREAD

**Issue by hanetyb** [lllyasviel/Fooocus#188]
Hi Lvmin
could you please take a look and advise the solution for below error msg? its failed to generate photos, thanks in advance.

===============env: OS：win10, VMware environment, SD run normally======
To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 24575 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 GRID P40-8Q : cudaMallocAsync
Using xformers cross attention
==============
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
**_missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}_**
Refiner model loaded: sd_xl_refiner_1.0_0.9vae.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
**_D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()_**
  return self.fget.__get__(instance, owner)()
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 104, in worker
    handler(task)
  File "D:\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 75, in handler
    imgs = pipeline.process(p_txt, n_txt, steps, switch, width, height, seed, callback=callback)
  File "D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_1-1-10\Fooocus\modules\default_pipeline.py", line 141, in process
    sampled_latent = core.ksampler_with_refiner(
  File "D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_1-1-10\Fooocus\modules\core.py", line 190, in ksampler_with_refiner
    previewer = get_previewer(device, model.model.latent_format)
  File "D:\Fooocus_win64_1-1-10\Fooocus\modules\core.py", line 79, in get_previewer
    taesd = TAESD(None, taesd_decoder_path).to(device)
  File "D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
_**RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.**_

**Comment by igorw765** [comment]
I have the same error message but on Linux

**Comment by corsmith** [comment]
I was able to workaround this issue by commenting out cuda_malloc() in launch.py.

It might have something to do with: https://github.com/comfyanonymous/ComfyUI/issues/940 

For reference I am running:
NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2
NVIDIA GeForce RTX 4070 Ti with 12G VRAM
FreeBSD 13.2-RELEASE-p2

**Comment by hanetyb** [comment]
Thanks for the sharing, i will find one machine to test.

**Comment by hanetyb** [comment]
> I was able to workaround this issue by commenting out cuda_malloc() in launch.py.
> 
> It might have something to do with: [comfyanonymous/ComfyUI#940](https://github.com/comfyanonymous/ComfyUI/issues/940)
> 
> For reference I am running: NVIDIA-SMI 535.98 Driver Version: 535.98 CUDA Version: 12.2 NVIDIA GeForce RTX 4070 Ti with 12G VRAM FreeBSD 13.2-RELEASE-p2

appreciate your sharing, i will find one machine to test.

**Comment by mashb1t** [comment]
Closing for now, initial issue can be solved by following the troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md (expecially swap section) after looking up the minimum requirements in https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement.
Please check again with the latest verrsion of Fooocus if this still relevant for you and feel free to reopen the issue. Thanks!
