### ISSUE TITLE
Error Generating 

### ISSUE THREAD

**Issue by danielewis1019** [lllyasviel/Fooocus#1898]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
Everything in terminal went smoothly and the new window opens. When I prompt the AI and ask it to generate an error appears in the area where the images should be generated. 

**Full Console Log**
Paste **full** console log here. You will make our job easier if you give a **full** log.

**Comment by mashb1t** [comment]
Please anyways provide the **full** console log and check your browser network tab for the error, as providing the HTTP error code + content of the request/response will also help narrowing down / determining the reason.
Do you use a cloud service or your local machine and what are your specs?

**Comment by danielewis1019** [comment]
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
Fooocus version: 2.1.862
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/danielewis/Fooocus/modules/async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "/Users/danielewis/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/Users/danielewis/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/Users/danielewis/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/Users/danielewis/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "/Users/danielewis/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 18, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/Users/danielewis/Fooocus/ldm_patched/ldm/modules/attention.py", line 12, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/Users/danielewis/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/Users/danielewis/Fooocus/ldm_patched/modules/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/Users/danielewis/Fooocus/ldm_patched/modules/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/danielewis/Fooocus/webui.py", line 27, in generate_clicked
    import ldm_patched.modules.model_management as model_management
  File "/Users/danielewis/Fooocus/ldm_patched/modules/model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/Users/danielewis/Fooocus/ldm_patched/modules/model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/Users/danielewis/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by mashb1t** [comment]
Make sure to enable your conda venv by running conda activate fooocus before starting the command.
See official installation instructions + https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#torch-not-compiled-with-cuda-enabled

**Comment by danielewis1019** [comment]
mashb1t no luck

<img width="948" alt="Screen Shot 2024-01-12 at 3 21 16 PM" src="https://github.com/lllyasviel/Fooocus/assets/69665314/bbf5de86-3ae4-4f78-b6a1-4e3f01bb710d">

**Comment by mashb1t** [comment]
In this case, browser screenshots are not helpful as the root cause of the error is in the console output.
Make sure you've installed the official requirements of https://github.com/lllyasviel/Fooocus/blob/main/requirements_versions.txt and please provide your torch + cuda version in anaconda3 site-packages.

**Comment by mashb1t** [comment]
Is this still relevant?

**Comment by mashb1t** [comment]
Feel free to shoot your answers at any time to reopen the issue.
