### ISSUE TITLE
Issue with downloading inpainter

### ISSUE THREAD

**Issue by abhinayperala** [lllyasviel/Fooocus#1942]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
I have recently downloaded foocus and when i try to download the inpainter i always get the error as described below. I have tried to change the network but i am still unable to download the inpaint model. It says that an existing connection was forcibly closed by remote host.

**Full Console Log**
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 2578034069333281530
[Fooocus] Downloading upscale models ...
[Fooocus] Downloading inpainter ...
Downloading: "https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/fooocus_inpaint_head.pth" to C:\Users\Abhinay Reddy Perala\Dropbox\PC (2)\Downloads\Fooocus_win64_2-1-831\Fooocus\models\inpaint\fooocus_inpaint_head.pth

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1454, in connect
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Abhinay Reddy Perala\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 823, in worker
    handler(task)
  File "C:\Users\Abhinay Reddy Perala\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Abhinay Reddy Perala\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Abhinay Reddy Perala\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 301, in handler
    inpaint_head_model_path, inpaint_patch_model_path = modules.config.downloading_inpaint_models(
  File "C:\Users\Abhinay Reddy Perala\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\config.py", line 401, in downloading_inpaint_models
    load_file_from_url(
  File "C:\Users\Abhinay Reddy Perala\OneDrive\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "C:\Users\Abhinay Reddy Perala\OneDrive\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>
Total time: 0.78 seconds

**Comment by f0n51** [comment]
Have you tried downloading the file manually? Just copy & paste the url into your browser:
[https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/fooocus_inpaint_head.pth](url)

Just to make sure, there are no firewall or proxy restrictions on your side?

**Comment by parrydigm** [comment]
Can confirm a manual download/copy to destination is a good workaround. I had similar problems (my bogus file challenge wasn't fooocus_inpaint_head.pth, but rather https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/inpaint_v26.fooocus.patch). Thanks for suggestion, @f0n51.

**Comment by Ripon19** [comment]
![Uploading IMG-20240601-WA0076.jpg…]()
