### ISSUE TITLE
API fn_index=0 KeyError: 'data'

### ISSUE THREAD

**Issue by ghj1976** [lllyasviel/Fooocus#1949]
code：
``` python
from gradio_client import Client

client = Client("http://192.168.1.17:7865/")
result = client.predict(
				fn_index=0
)
print(result)
```
error:
``` bash
% python fooocus.py
Loaded as API: http://192.168.1.17:7865/ ✔
Traceback (most recent call last):
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/site-packages/gradio_client/client.py", line 1282, in _predict
    output = result["data"]
KeyError: 'data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ghj1976/Documents/MyCodes/tanghai/PromoteBot2/fooocus.py", line 4, in <module>
    result = client.predict(
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/site-packages/gradio_client/client.py", line 392, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/site-packages/gradio_client/client.py", line 1573, in result
    return super().result(timeout=timeout)
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/site-packages/gradio_client/client.py", line 1245, in _inner
    predictions = _predict(*data)
  File "/Users/ghj1976/opt/anaconda3/envs/fbt/lib/python3.10/site-packages/gradio_client/client.py", line 1296, in _predict
    raise KeyError(
KeyError: 'Could not find \'data\' key in response. Response received: {\'detail\': [{\'type\': \'model_attributes_type\', \'loc\': [\'body\'], \'msg\': \'Input should be a valid dictionary or object to extract fields from\', \'input\': \'{"data": [], "fn_index": 0, "session_hash": "5dcfa627-c74c-4d8e-add5-b80fecb0671e"}\', \'url\': \'https://errors.pydantic.dev/2.5/v/model_attributes_type\'}]}'

```

**Comment by ghj1976** [comment]
Fooocus currently uses gradio==3.41.2. 
This version corresponds to gradio_client version: 0.5. 
The latest version I use here is 0.8, which is incompatible.

Solution: 
pip install gradient_client==0.5.3

**Comment by YellowTigerr** [comment]
Why the same error, I lowered 0.5.3 or 0.5.0 version  and it didn't work
