### ISSUE TITLE
model selection is getting ignored

### ISSUE THREAD

**Issue by alectprasad** [lllyasviel/Fooocus#2003]
![image](https://github.com/lllyasviel/Fooocus/assets/22129443/6f3f2d82-27ec-4b30-a255-1137580f2e0e)

**Comment by mashb1t** [comment]
Please provide the full console log output, much appreciated.
Furthermore, are you certain that OpenDalleV1.1.safetensors is located in the models folder?
Could you please also check if renaming `OpenDalleV1.1.safetensors` to OpenDalleV1_1.safetensors` works (removing the dot, maybe recognized as file extension)? Thank you for checking!

**Comment by alectprasad** [comment]
no I think juggernautv6 is hard coded and it can't use any other model
![image](https://github.com/lllyasviel/Fooocus/assets/22129443/3a3e6781-2129-4e36-8c07-0627538a31b5)
```
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\patch.py", line 459, in loader
    result = original_loader(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError: No such file or directory: "D:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\juggernautXL_version6Rundiffusion.safetensors"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 253, in <module>
    refresh_everything(
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 233, in refresh_everything
    refresh_base_model(base_model_name)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 69, in refresh_base_model
    model_base = core.load_model(filename)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\core.py", line 151, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings)
  File "D:\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sd.py", line 427, in load_checkpoint_guess_config
    sd = ldm_patched.modules.utils.load_torch_file(ckpt_path)
  File "D:\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\patch.py", line 475, in loader
    raise ValueError(exp)
ValueError: No such file or directory: "D:\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints\\juggernautXL_version6Rundiffusion.safetensors"
```

**Comment by mashb1t** [comment]
> Please provide the full console log output, much appreciated. 
> Furthermore, are you certain that OpenDalleV1.1.safetensors is located in the models folder?

This is most likely not the full console log, please copy & paste the full log from starting Fooocus (incl. line of startup command) to last line of the log.
Make sure you're including the process of initial startup, changing the default model and clicking the generate button in the log.

**Comment by mashb1t** [comment]
@alectprasad Is this still relevant or can the issue be closed?

**Comment by mashb1t** [comment]
Closing as stale
