### ISSUE TITLE
run.bat and run_anime.bat won't start. [WinError 10054] "existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by Norby123** [lllyasviel/Fooocus#2054]
**FAQ and troubleshooting: yeah, says nothing about my problem**

**Describe the problem**
I can't run the basic run.bat and neither the anime.bat files. Realistic.bat runs fine, it opens up and works. The error I got says  [WinError 10054] and that an "existing connection was forcibly closed by the remote host." 

**What I've tried so far**: I installed the latest LAN and Wireless LAN drivers from my mobo's website (it's a z790 PG Riptide Wifi - with Killer ethernet adapter). That didn't help. I set DNS to Google's 8.8.8.8 and 8.8.4.4. , I did a reset to netsh winsock, netsh int ip, then did ipconfig /release, ipconfig /renew, ipconfig /flushdns. Restarted the PC. Then I restarted my router, in Win 10 adapter setting I disabled the old network and the Wifi (even though it was turned off, and not connected) and set up the new network2. Nothing. Tried running it as admin, didn't even work. I turned off the Firewall, I tried adding it to the exceptions. Nothing. I installed Eset and turned on / off its (yet another) firewall. Nothing.

I googled the error code and some said it might be an SSL problem, but I don't know what it means, or how to solve it. Or if it's a peer, and not a host issue to begin with....

Do I need to install some python stuff manually? 

Is the problem that I can't download from Huggingface?

I'm not an IT professional, so please be gentle with me.

**Full Console Log**
C:\Sajat\StableDiffusion\APP\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.862
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_version6Rundiffusion.safetensors" to C:\Sajat\StableDiffusion\Models\BaseModels\SDXL\juggernautXL_version6Rundiffusion.safetensors

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1454, in connect
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ConnectionResetError: [WinError 10054] A létező kapcsolatot a távoli állomás kényszerítetten bezárta

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Sajat\StableDiffusion\APP\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Sajat\StableDiffusion\APP\Fooocus\Fooocus\launch.py", line 107, in <module>
    download_models()
  File "C:\Sajat\StableDiffusion\APP\Fooocus\Fooocus\launch.py", line 75, in download_models
    load_file_from_url(url=url, model_dir=path_checkpoints, file_name=file_name)
  File "C:\Sajat\StableDiffusion\APP\Fooocus\Fooocus\modules\model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "C:\Sajat\StableDiffusion\APP\Fooocus\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] A létező kapcsolatot a távoli állomás kényszerítetten bezárta>

C:\Sajat\StableDiffusion\APP\Fooocus>pause

**Comment by Norby123** [comment]
Okay, after many hours of trying to figure this one out, resetting network option didn't work, however disabling IPv6 seems to solve this issue for me.

**Comment by Diegonuncer** [comment]
Thank you for this!!!

**Comment by escmaster** [comment]
Wasen't logged and I'm login just to say thank you, wasn't working and after change the ipv6 starts working, you save me, thank you so much for posting that!!!!

**Comment by KuntaoDaChump** [comment]
Worked for me, thank you
