### ISSUE TITLE
Fooocus Inpaint/Input Image showing Attribute Error

### ISSUE THREAD

**Issue by trialsnabhi** [lllyasviel/Fooocus#2155]
**Read Troubleshoot**

[x] I admit that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) before making this issue.

**Describe the problem**
When I use Inpainting on Fooocus, Iam getting this error offlate. Hence unable to use inpaint on Fooocus at all !

**Full Console Log**

Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/gradio_hijack.py", line 278, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3288, in open
    """
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3274, in _open_core
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 799, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/ImageFile.py", line 116, in __init__
    self._open()
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 380, in _open
    handler(self, i)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 211, in SOF
    self.mode = "RGB"
AttributeError: can't set attribute 'mode'
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/studio-lab-user/Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/gradio_hijack.py", line 278, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3288, in open
    """
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3274, in _open_core
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 799, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/ImageFile.py", line 116, in __init__
    self._open()
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 380, in _open
    handler(self, i)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/JpegImagePlugin.py", line 211, in SOF
    self.mode = "RGB"
AttributeError: can't set attribute 'mode'

**Comment by trialsnabhi** [comment]
It happens when there is any sort of Input Image .. Whether an inpaint/outpaint or ImagePrompt too

**Comment by mashb1t** [comment]
@trialsnabhi i've checked inpainting in all modes with various jpg images and have not been able to reproduce the issue.
The issue occurs in `def SOF(self, marker)` of PIL JpegImagePlugin.py, where the layers are mapped and the Start of frame marker can not set the mode accordingly as in your case the object doesn't have such a property. 

This is not an issue of Fooocus but most likely a parsing problem of your specific image through PIL.
Can you please attach your source jpg image to debug the layers and / or type of jpg? Thanks!

**Comment by trialsnabhi** [comment]
oh this happens with any image tat I use in the image prompt/inpatinting source.. either generated image or any jpg/png . Thats why I posted.
To give you more info, I use fooocus on amazonsagemaker labs and kaggle. Both are getting into a similar issue.

**Comment by mashb1t** [comment]
Interesting... I don't have access to those services, maybe somebody else can support here.

**Comment by dhruvchandel** [comment]
Facing Similar Issue. I was also using Sagemaker notebook to run Fooocus.

**Comment by trialsnabhi** [comment]
> This may be caused by an indirect early import of `PIL` in `launch.py`. The import preceds an installation of `Pillow==9.2.0` and remains cached.
> 
> If Pillow has been downgraded in this way from a version `>=10.1.0`, the mixture of modules is obviously incompatible: [python-pillow/Pillow#7307](https://github.com/python-pillow/Pillow/pull/7307)

can you help me with a solution ?

**Comment by sehajbenipal** [comment]
Similar Issue. I was also using Sagemaker and kaggle notebook to run Fooocus.

**Comment by mashb1t** [comment]
I think the matter has been more or less resolved,. The solution is to either use a notebook without loading libraries before loading Fooocus or restarting the instance afterwards.
Closing for now, but still feel free to provide your feedback.

**Comment by mashb1t** [comment]
@rsl8 sure, feel free
