### ISSUE TITLE
torch.baddbmm - RuntimeError

### ISSUE THREAD

**Issue by charliekayaker** [lllyasviel/Fooocus#2279]
**Read Troubleshoot**

[Yes] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

Hi guys, i am trying to generate an image but i can't.  At the first time i fix two issues with the help here, but now, I can't understand the message well.

My hardware is:

![image](https://github.com/lllyasviel/Fooocus/assets/53378855/600bcb95-97e6-43ed-86c8-dce470322cf3)

I get the next message when i wanna try get an image... I couldn't generate one at the moment.

Traceback (most recent call last):
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\async_worker.py", line 822, in worker
    handler(task)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\async_worker.py", line 753, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\core.py", line 313, in ksampler
    samples = ldm_patched.modules.sample.sample(model,
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\modules\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\modules\samplers.py", line 712, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\sample_hijack.py", line 157, in sample_hacked
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback_wrap, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\modules\samplers.py", line 557, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\k_diffusion\sampling.py", line 701, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\k_diffusion\sampling.py", line 613, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\patch.py", line 314, in patched_KSamplerX0Inpaint_forward
    out = self.inner_model(x, sigma,
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\modules\samplers.py", line 271, in forward
    return self.apply_model(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\modules\samplers.py", line 268, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\patch.py", line 229, in patched_sampling_function
    positive_x0, negative_x0 = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\modules\samplers.py", line 222, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\modules\model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\modules\patch.py", line 398, in patched_unet_forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 43, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\attention.py", line 613, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\attention.py", line 440, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\diffusionmodules\util.py", line 189, in checkpoint
    return func(*inputs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\attention.py", line 540, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\attention.py", line 392, in forward
    out = optimized_attention(q, k, v, self.heads)
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\attention.py", line 168, in attention_sub_quad
    hidden_states = efficient_dot_product_attention(
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 256, in efficient_dot_product_attention
    return compute_query_chunk_attn(
  File "C:\Users\charlie\Documents\Fooocus_windows_instrucciones\Fooocus\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 159, in _get_attention_scores_no_kv_chunking
    attn_scores = torch.baddbmm(
RuntimeError
Total time: 246.86 seconds

I will grateful if you could help me.

**Comment by charliekayaker** [comment]
Sorry, At the moment i will try to debug it again because i got different message [W D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_heap_allocator.cc:120] DML allocator out of memory! and I think there are topics about it.
