### ISSUE TITLE
2 errors 

### ISSUE THREAD

**Issue by Khaos1221** [lllyasviel/Fooocus#2365]
**Read Troubleshoot**

 I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
tried 2 times with a gap

**Full Console Log**
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.865
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to C:\Users\blood\Downloads\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1447, in connect
  File "http\client.py", line 941, in connect
  File "socket.py", line 824, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\blood\Downloads\Fooocus_win64_2-1-831\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\blood\Downloads\Fooocus_win64_2-1-831\Fooocus\launch.py", line 125, in <module>
    download_models()
  File "C:\Users\blood\Downloads\Fooocus_win64_2-1-831\Fooocus\launch.py", line 116, in download_models
    load_file_from_url(url=url, model_dir=config.path_checkpoints, file_name=file_name)
  File "C:\Users\blood\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "C:\Users\blood\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>

C:\Users\blood\Downloads\Fooocus_win64_2-1-831>pause

**Comment by mashb1t** [comment]
@Khaos1221 make sure your computer can access https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors.
This could have many reasons: using a VPN with restricted access, firewall settings, eouter settings, DNS issues, etc.
Please try to manually download the file and put it in models > checkpoints, then restart Fooocus.

Closing this issue as this is not a problem of Fooocus. Feel free to nevertheless post your feedback.

**Comment by Khaos1221** [comment]
Yeah bro FLushed my dns and used DNS of Cloudware
