### ISSUE TITLE
Getting a bunch of errors when attempting to launch on macOS (M2 Max - Ventura)

### ISSUE THREAD

**Issue by vgjenks** [lllyasviel/Fooocus#2386]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
Followed all instructions here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#mac

I get all the way through the process for Mac but get a bunch of Python errors when trying to run it.

**Full Console Log**
```
(fooocus) vgjenks@VGJ-MBP-M2X Fooocus % python entry_with_update.py
Update failed.
authentication required but no callback set
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.13 (main, Feb 28 2024, 19:17:17) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Fooocus version: 2.1.865
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /Users/vgjenks/Documents/Projects/Learning/ai/Fooocus/models/vae_approx/xlvaeapp.pth

Traceback (most recent call last):
  File "/Users/vgjenks/Documents/Projects/Learning/ai/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/Users/vgjenks/Documents/Projects/Learning/ai/Fooocus/launch.py", line 125, in <module>
    download_models()
  File "/Users/vgjenks/Documents/Projects/Learning/ai/Fooocus/launch.py", line 91, in download_models
    load_file_from_url(url=url, model_dir=config.path_vae_approx, file_name=file_name)
  File "/Users/vgjenks/Documents/Projects/Learning/ai/Fooocus/modules/model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/Users/vgjenks/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/Users/vgjenks/.pyenv/versions/3.10.13/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/vgjenks/.pyenv/versions/3.10.13/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Users/vgjenks/.pyenv/versions/3.10.13/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Users/vgjenks/.pyenv/versions/3.10.13/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Users/vgjenks/.pyenv/versions/3.10.13/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/vgjenks/.pyenv/versions/3.10.13/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 501: Not Implemented
```

**Comment by eddyizm** [comment]
Looks like an 501 error, although in this instance, I can only guess there was an issue with huggingface. Try again later and see if you have the same issue. 
Once this initial downloads, you don't have to keep downloading them in future launches.

**Comment by mashb1t** [comment]
@vgjenks This issue is caused by a 501 HTTP response code.
Please retry or manually download the model(s) and move them in their corresponding directory, then restart Fooocus.

**Comment by vgjenks** [comment]
Gotcha, thanks all. Seems to be dl'ing now.

**Comment by whhkhaled** [comment]
please i need help

i can't download requirements versions.txt for fooocus on my mac.

My device is MAC Apple M2 Max
and python is 3.12.1

i am facing this issue:
![image](https://github.com/lllyasviel/Fooocus/assets/60566610/4a028c15-dc8a-4777-a72e-110311788a50)

please help me thank you
