### ISSUE TITLE
Error when using the key --vae-in-fp16 and --vae-in-bf16

### ISSUE THREAD

**Issue by poor7** [lllyasviel/Fooocus#2387]
Error when using the key --vae-in-fp16   The preview shows the image, but after the last step it displays a black image.
```
/content/Fooocus/modules/core.py:334: RuntimeWarning: invalid value encountered in cast
  return [np.clip(255. * y.cpu().numpy(), 0, 255).astype(np.uint8) for y in x]
```
Error when using the key --vae-in-bf16
`Traceback (most recent call last):
  File "/content/Fooocus/modules/async_worker.py", line 822, in worker
    handler(task)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 753, in handler
    imgs = pipeline.process_diffusion(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/default_pipeline.py", line 378, in process_diffusion
    decoded_latent = core.decode_vae(vae=target_vae, latent_image=sampled_latent, tiled=tiled)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/core.py", line 167, in decode_vae
    return opVAEDecode.decode(samples=latent_image, vae=vae)[0]
  File "/content/Fooocus/ldm_patched/contrib/external.py", line 269, in decode
    return (vae.decode(samples["samples"]), )
  File "/content/Fooocus/ldm_patched/modules/sd.py", line 241, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples).to(self.output_device).float() + 1.0) / 2.0, min=0.0, max=1.0)
  File "/content/Fooocus/ldm_patched/ldm/models/autoencoder.py", line 202, in decode
    dec = self.decoder(dec, **decoder_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Fooocus/ldm_patched/ldm/modules/diffusionmodules/model.py", line 629, in forward
    h = self.mid.attn_1(h, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Fooocus/ldm_patched/ldm/modules/diffusionmodules/model.py", line 287, in forward
    h_ = self.optimized_attention(q, k, v)
  File "/content/Fooocus/ldm_patched/ldm/modules/diffusionmodules/model.py", line 235, in pytorch_attention
    out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0.0, is_causal=False)
RuntimeError: cutlassF: no kernel found to launch!`

**Comment by mashb1t** [comment]
@poor7 please check which pytorch version you're using and try to also use the `--all-in-fp16` or `--unet-in-fp16` args.
Also see https://github.com/huggingface/transformers/issues/28731 (https://github.com/huggingface/transformers/issues/28731#issuecomment-1912350270)

**Comment by poor7** [comment]
Standart pytorch in Colab.  With `--all-in-fp16` or `--unet-in-fp16` works, but VAE uses fp32.

```
Total VRAM 15102 MB, total RAM 12979 MB
Forcing FP16.
Set vram state to: HIGH_VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float32
Using pytorch cross attention

**Comment by mashb1t** [comment]
@poor7 it seems that you have to manually also set `--vae-in-fp16` and `--all-in-fp16` does not include VAE.

See https://github.com/lllyasviel/Fooocus/blob/main/ldm_patched/modules/model_management.py#L192-L193

**Comment by poor7** [comment]
@mashb1t  I would like to. Because at 16 it should work faster than at 32.

**Comment by mashb1t** [comment]
[As of my last comment](https://github.com/lllyasviel/Fooocus/issues/2387#issuecomment-1971342668), did you set `--vae-in-fp16` and `--all-in-fp16` and check afterwards?

**Comment by poor7** [comment]
Works. 
`!python entry_with_update.py --theme=dark --share`  35,8 s 
`!python entry_with_update.py --disable-offload-from-vram --always-high-vram --vae-in-fp16 --all-in-fp16 --theme=dark --share` 30,5 s
At the beginning I see strange errors that do not affect the work:
```
[System ARGV] ['entry_with_update.py', '--disable-offload-from-vram', '--always-high-vram', '--vae-in-fp16', '--all-in-fp16', '--theme=dark', '--share']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.2.1
Total VRAM 15102 MB, total RAM 12979 MB
Forcing FP16.
Set vram state to: HIGH_VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float16
Using pytorch cross attention
2024-03-13 17:13:13.049541: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-13 17:13:13.049589: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-13 17:13:13.059146: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-13 17:13:15.247868: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865/
model_type EPS
UNet ADM Dimension 2816
Running on public URL: https://c67f487d31ba95d255.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 375, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 98, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 96, in app
    await func(session)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 604, in join_queue
    session_info = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 139, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 111, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"], message.get("reason"))
starlette.websockets.WebSocketDisconnect: (1001, None)
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
loaded straight to GPU
Requested to load SDXL
Loading 1 new model
Base model loaded: /content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.66 seconds
Started worker with PID 6661
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865 or https://c67f487d31ba95d255.gradio.live/
```

**Comment by poor7** [comment]
> Error when using the key --vae-in-fp16 The preview shows the image, but after the last step it displays a black image.

ADD: This issue is related to a bug vae fp16 in the juggernautXL_version6Rundiffusion.safetensors. The problem has been fixed since version 7.
