### ISSUE TITLE
Linux - PopOs - Torch complains NVIDIA driver is too old,  when I have a driver that was released last week, [includes works for me fix]

### ISSUE THREAD

**Issue by zeonglow** [lllyasviel/Fooocus#2391]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

When I start up Fooocus I get an error about my NVIDIA driver being too old,   (see log below) 
however,  `nvidia-detector` shows that I have `nvidia-driver-550` ,  which is the latest driver at time of writing.

After trying a few things unsuccessfully,  I tried

`pip install -r  requirements_docker.txt`,  inside the normal fooocus_venv not using Docker.

This installed the newer version of Torch along with a few other things and now Fooocus works perfectly again!

My guess is `requirements_versions.txt` is out of date

```
 git log -s

commit 4f4d23f4e3e6896daeb16025b483f9de50f8cdc6 (HEAD -> develop, origin/develop)
Author: Manuel Schmid <dev@mash1t.de>
Date:   Mon Feb 26 21:14:11 2024 +0100

    fix: use filename instead of download function call for lcm lora
    
    do not require lcm lora to be downloaded for metadata parsing


```

**Full Console Log**
```
Already up-to-date
Update succeeded.
[System ARGV] ['update_and_go.py', '--always-download-new-model', '--listen', '--port', '9420']
Python 3.10.13 (main, Dec 25 2023, 09:05:58) [GCC 11.4.0]
Fooocus version: 2.2.0-rc1
Traceback (most recent call last):
  File "/home/chrishuang-leaver/fooocus/update_and_go.py", line 46, in <module>
    from launch import *
  File "/home/chrishuang-leaver/fooocus/launch.py", line 127, in <module>
    from webui import *
  File "/home/chrishuang-leaver/fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/home/chrishuang-leaver/fooocus/modules/async_worker.py", line 2, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/home/chrishuang-leaver/fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/home/chrishuang-leaver/fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/home/chrishuang-leaver/fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/home/chrishuang-leaver/fooocus/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/home/chrishuang-leaver/fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/home/chrishuang-leaver/fooocus/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/chrishuang-leaver/fooocus/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/chrishuang-leaver/fooocus/fooocus_venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/home/chrishuang-leaver/fooocus/fooocus_venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL:  http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
```

**Comment by mashb1t** [comment]
Thank you for testing and your hint.
It simply may be possible that PopOS is not compatible with the latest Torch version or there are some different errors as PopOS is not officially tested, only Debian/Ubuntu. Both systems work perfectly fine with the normal package versions, which, btw, haven't been updated in a while now but docker is a feature using torch 2.0.1 and non-docker uses 2.1.x AFAIK.
Glad this is working for you, may reference on similar issues with PopOS to this issue.
