### ISSUE TITLE
Error when first opening

### ISSUE THREAD

**Issue by oussome10** [lllyasviel/Fooocus#2398]
**Read Troubleshoot**

[x] I confirm that I have read the [Troubleshoot](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md) guide before making this issue.

**Describe the problem**
Error when the first opening of Fooocus , I have 4GB Ram Nvidia Quadro K4100m

**Full Console Log**

C:\Users\DELL\Downloads\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.865
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 25, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\modules\patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\webui.py", line 27, in generate_clicked
    import ldm_patched.modules.model_management as model_management
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\webui.py", line 27, in generate_clicked
    import ldm_patched.modules.model_management as model_management
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\DELL\Downloads\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by mashb1t** [comment]
> The NVIDIA driver on your system is too old (found version 10010)

Your GPU driver is too old and Nvidia Quadro K4100m is not officially supported. Please try to update the driver and check again.
