### ISSUE TITLE
[Bug]: Version 2.2.0 upscale (fast 2x)

### ISSUE THREAD

**Issue by Cil20KLV** [lllyasviel/Fooocus#2422]
### Checklist

- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Error for Upscale fast 2x

### Steps to reproduce the problem

1. create a picture
2. select input image
3. upscale (1.5x) or upscale (2x) or not
4. upscale (fast 2x)

### What should have happened?

A new picture upscale

### What browsers do you use to access Fooocus?

Mozilla Firefox, Microsoft Edge

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
E:\Sources\AI\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Update failed.
Repository not found at E:\Sources\AI\Fooocus\Fooocus
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.2.0
Total VRAM 12282 MB, total RAM 16232 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.logit_scale'}
Base model loaded: E:\Sources\AI\Fooocus\Fooocus\models\checkpoints\juggernautXL_v9Rundiffusionphoto2.safetensors
Request to load LoRAs [['None', 1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [E:\Sources\AI\Fooocus\Fooocus\models\checkpoints\juggernautXL_v9Rundiffusionphoto2.safetensors].
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.73 seconds
Started worker with PID 2648
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 7886244266080795613
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
Request to load LoRAs [['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [E:\Sources\AI\Fooocus\Fooocus\models\checkpoints\juggernautXL_v9Rundiffusionphoto2.safetensors].
Requested to load SDXLClipModel
Loading 1 new model
unload clone 1
[Fooocus Model Management] Moving model(s) has taken 0.81 seconds
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] space opera, elegant, highly detailed, sharp focus, sublime, radiant light, professional fine detail, cute, enhanced, intricate, complex, exquisite, cinematic composition, dramatic ambient background, full color, perfect, colorful, beautiful, pure, attractive, illuminated, deep vibrant, aesthetic, very inspirational, glowing, rich vivid colors, epic, stunning, magical, fascinating, marvelous
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] space opera, delicate, beautiful, elegant, highly detailed, sharp focus, colorful, sacred, dramatic ambient light, elaborate scenic background, atmosphere, thoughtful, thought, cinematic, professional, distinguished, pleasant, rich, unique, best, attractive, romantic, enhanced, novel, artistic, cute, perfect, charming, pretty, extremely coherent, creative, loving, peaceful, vibrant
[Fooocus] Preparing Fooocus text #3 ...
[Prompt Expansion] space opera, elegant, highly detailed, sharp focus, beautiful, intricate, fine detail, elaborate, complex, epic composition, joyful, amazing, cinematic, magical atmosphere, professional, thought, iconic, imposing, rich, marvelous, awesome, creative, wonderful, elite, winning, perfect, artistic, pure, fabulous, radiant light, vivid, shining, bright, brilliant
[Fooocus] Preparing Fooocus text #4 ...
[Prompt Expansion] space opera, delicate, beautiful, elegant, highly detailed, dramatic light, sharp focus, intricate, fine detail, elaborate complex, exquisite, rich colors, ambient background, colorful, pleasing color, symmetry, great composition, clear, coherent, dynamic, vibrant, attractive, shiny, pretty, enhanced, epic, best, creative, cinematic, thought, atmosphere, perfect, gorgeous
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.36 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding positive #3 ...
[Fooocus] Encoding positive #4 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Encoding negative #3 ...
[Fooocus] Encoding negative #4 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1216, 832)
Preparation time: 10.72 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 8.99 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:13<00:00,  2.30it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.84 seconds
Image generated with private log at: E:\Sources\AI\Fooocus\Fooocus\outputs\2024-03-03\log.html
Generating and saving time: 27.41 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.13 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:10<00:00,  2.93it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.35 seconds
Image generated with private log at: E:\Sources\AI\Fooocus\Fooocus\outputs\2024-03-03\log.html
Generating and saving time: 13.28 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.06 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:10<00:00,  2.88it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.29 seconds
Image generated with private log at: E:\Sources\AI\Fooocus\Fooocus\outputs\2024-03-03\log.html
Generating and saving time: 13.36 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.07 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:10<00:00,  2.88it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.33 seconds
Image generated with private log at: E:\Sources\AI\Fooocus\Fooocus\outputs\2024-03-03\log.html
Generating and saving time: 13.77 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 209.18 seconds
[Fooocus Model Management] Moving model(s) has taken 0.70 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 8597734831385677872
[Fooocus] Downloading upscale models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Image processing ...
[Fooocus] Upscaling image from (1216, 832) ...
Upscaling image with shape (1216, 832, 3) ...
Image upscaled.
Traceback (most recent call last):
  File "E:\Sources\AI\Fooocus\Fooocus\modules\async_worker.py", line 891, in worker
    handler(task)
  File "E:\Sources\AI\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Sources\AI\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Sources\AI\Fooocus\Fooocus\modules\async_worker.py", line 557, in handler
    uov_input_image_path = log(uov_input_image, d, output_format)
  File "E:\Sources\AI\Fooocus\Fooocus\modules\private_logger.py", line 29, in log
    parsed_parameters = metadata_parser.parse_string(metadata) if metadata_parser is not None else ''
AttributeError: 'str' object has no attribute 'parse_string'
Total time: 6.94 seconds
```

**Comment by mashb1t** [comment]
Already fixed in https://github.com/lllyasviel/Fooocus/pull/2411, will release patch 2.2.1 today/tomorrow.
You can already pull the latest commit in main to also get the update.
