### ISSUE TITLE
"File Not Found Errno 2"  Fooocus fails to write gen to disk, throws error, disables "Generate" controls

### ISSUE THREAD

**Issue by PeterMcLennan** [lllyasviel/Fooocus#2445]
### Checklist

- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

While generating series of images, Fooocus intermittently fails to write a file to disk, trigging this error.  

The "Generate/Skip/Stop" button becomes unresponsive, an "error" message appears in each of the preview windows and in the progress bar.  

Fooocus continues to render images until completion, but the progress bar indicates that generation is still underway,  even though no more images appear.  At this time, the "Generate" button returns to normal and a new series of gens can begin.

The missing file does not appear in the outputs directory or the HTML log file.

This error appeared after the recent 2.2 release and persists with today's release of 2.2.1

I'm using the JuggernautXL_v8Rundiffusion.safetensors model and the ClassipeintXL2.0.safetensors lora at a 1.0 setting.
I'm running with no styles selected.

I can't replicate this error.  It appears to be random.  Sometimes appearing in the first few images, sometimes much later in the run and sometimes not at all.

I have cold booted the machine with no change to the symptoms.

### Steps to reproduce the problem

I cannot reproduce this error.  It appears at random.

### What should have happened?

Not provide error message reporting missing file and simultaneously disable the GENERATE/SKIP/STOP button.

No recent changes made to system.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### Console logs

```Shell
[File Not Found Error Log.txt](https://github.com/lllyasviel/Fooocus/files/14488889/File.Not.Found.Error.Log.txt)

The error appears about halfway through this log

BEGIN 32 image generations run:


Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.22 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
Total time: 749.55 seconds
[Fooocus Model Management] Moving model(s) has taken 0.51 seconds
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 617062282088984635
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, James McIntosh Patrick
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Keith Parkinson
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Marlene Dumas
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, John Closterman
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Ethan Van Sciver
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Ed Roth
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, H.P. Lovecraft
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, M.W. Kaluta
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Mike Allred
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Qian Xuan
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Ettore Tito
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Vilhelm Hammershoi
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Kees Scherer
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Nicolas Poussin
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Hannah Hoch
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Philip McKay
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Franklin Booth
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, John Lurie
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Henry Fuseli
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Jody Bergsma
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Android Jones
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Rene Magritte
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Hieronymus Bosch
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Lesser Ury
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Mike Allred
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Joaquín Sorolla
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Théophile Steinlen
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Victoria Crowe
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Jan van Scorel
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Marc Lagrange
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, George Herriman
[Wildcards] processing: a long and dangerous journey, __artist__
[Wildcards] a long and dangerous journey, Philip McKay
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding positive #3 ...
[Fooocus] Encoding positive #4 ...
[Fooocus] Encoding positive #5 ...
[Fooocus] Encoding positive #6 ...
[Fooocus] Encoding positive #7 ...
[Fooocus] Encoding positive #8 ...
[Fooocus] Encoding positive #9 ...
[Fooocus] Encoding positive #10 ...
[Fooocus] Encoding positive #11 ...
[Fooocus] Encoding positive #12 ...
[Fooocus] Encoding positive #13 ...
[Fooocus] Encoding positive #14 ...
[Fooocus] Encoding positive #15 ...
[Fooocus] Encoding positive #16 ...
[Fooocus] Encoding positive #17 ...
[Fooocus] Encoding positive #18 ...
[Fooocus] Encoding positive #19 ...
[Fooocus] Encoding positive #20 ...
[Fooocus] Encoding positive #21 ...
[Fooocus] Encoding positive #22 ...
[Fooocus] Encoding positive #23 ...
[Fooocus] Encoding positive #24 ...
[Fooocus] Encoding positive #25 ...
[Fooocus] Encoding positive #26 ...
[Fooocus] Encoding positive #27 ...
[Fooocus] Encoding positive #28 ...
[Fooocus] Encoding positive #29 ...
[Fooocus] Encoding positive #30 ...
[Fooocus] Encoding positive #31 ...
[Fooocus] Encoding positive #32 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Fooocus] Encoding negative #3 ...
[Fooocus] Encoding negative #4 ...
[Fooocus] Encoding negative #5 ...
[Fooocus] Encoding negative #6 ...
[Fooocus] Encoding negative #7 ...
[Fooocus] Encoding negative #8 ...
[Fooocus] Encoding negative #9 ...
[Fooocus] Encoding negative #10 ...
[Fooocus] Encoding negative #11 ...
[Fooocus] Encoding negative #12 ...
[Fooocus] Encoding negative #13 ...
[Fooocus] Encoding negative #14 ...
[Fooocus] Encoding negative #15 ...
[Fooocus] Encoding negative #16 ...
[Fooocus] Encoding negative #17 ...
[Fooocus] Encoding negative #18 ...
[Fooocus] Encoding negative #19 ...
[Fooocus] Encoding negative #20 ...
[Fooocus] Encoding negative #21 ...
[Fooocus] Encoding negative #22 ...
[Fooocus] Encoding negative #23 ...
[Fooocus] Encoding negative #24 ...
[Fooocus] Encoding negative #25 ...
[Fooocus] Encoding negative #26 ...
[Fooocus] Encoding negative #27 ...
[Fooocus] Encoding negative #28 ...
[Fooocus] Encoding negative #29 ...
[Fooocus] Encoding negative #30 ...
[Fooocus] Encoding negative #31 ...
[Fooocus] Encoding negative #32 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (832, 1216)
Preparation time: 2.45 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.97 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:22<00:00,  1.35it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 25.53 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.41 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:22<00:00,  1.33it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 25.30 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.42 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:22<00:00,  1.33it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 25.33 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.40 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:22<00:00,  1.33it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 25.33 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.42 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.43it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.51 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.35 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.44it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.38 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.33 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.41it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.92 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.34 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.38it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.17 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.39 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.38it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.40 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.34 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.43it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.67 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
Traceback (most recent call last):
  File "D:\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 1326, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "D:\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\blocks.py", line 460, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "D:\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\components\gallery.py", line 203, in postprocess
    file_path = self.make_temp_copy_if_needed(img)
  File "D:\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\components\base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "D:\Fooocus_win64_2-1-791\python_embeded\lib\site-packages\gradio\components\base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Fooocus_win64_2-1-791\\Fooocus\\outputs\\2024-03-04\\2024-03-04_17-09-38_6564.png'
[Fooocus Model Management] Moving model(s) has taken 1.36 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.44it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.46 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.37 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.44it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.43 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.39 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.44it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.50 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.33 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.41it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.02 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.38 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:22<00:00,  1.33it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 25.21 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.39 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.38it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.37 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.40 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.44it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.35 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.33 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.44it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.43 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.34 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:20<00:00,  1.44it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.41 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.32 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.41it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.48 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.61 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:22<00:00,  1.31it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 25.73 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.37 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.36it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.65 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.33 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.41it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.93 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.42 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.40it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.21 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.32 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.40it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.07 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.38 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.40it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.02 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.35 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.40it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.18 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.11 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.41 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:22<00:00,  1.35it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.92 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.37 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.39it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.19 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.39 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.39it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.58 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.37 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.41it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.14 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 24.27 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 1.65 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:21<00:00,  1.42it/s]
Requested to load AutoencoderKL
Loading 1 new model
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Image generated with private log at: D:\Fooocus_win64_2-1-791\Fooocus\outputs\2024-03-04\log.html
Generating and saving time: 23.96 seconds
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.52 seconds
```

**Comment by PeterMcLennan** [comment]
OS is Windows 10 64.  Hardware is RTX 3060 12 GB.  Outputs disk is 2TB SSD 10% full.

**Comment by mashb1t** [comment]
Fooocus is now yielding the filepath to Gradio instead of the image numpy representation.
This may cause file lag but has never been observed to cause file not found errors, as the file is yielded after writing, but your drive might have had a lag or similar.
Files are saved synchronously, so not detached from the actual genrstion process, which ensures that files are written before accessing them again.

Closing this issue for now as not reproducible.
If you find a way to reliably make it debuggable please don't hesitate to let me know!

**Comment by PeterMcLennan** [comment]
OK. Thanks for the update.
Destination disk is an internal SSD so lag shouldn't be an issue.
The files are definitely not written to disk.
Problem is not disastrous, simply annoying.

Again, thanks.
Peter

**Comment by MoacirEduardo** [comment]
I think I have found a simple way to reproduce this bug. It seems to happen when you delete a file while generating other images.

**Comment by MoacirEduardo** [comment]
Clarifying further, it seems you can't delete any image in the generating sequence, from the output folder, without risking encountering this error.

**Comment by mashb1t** [comment]
@MoacirEduardo yes, please don't delete images in the outouts folder before the generation is done.
The latest version 2.2.0 introduced optional metadata saving and changes the return value to Gradio from numpy array to filepath for actual metadata download in the frontend. Without this no metadata would be visible in images downlaoded in the frontend, also the filename would be not consistent.

**Comment by MoacirEduardo** [comment]
That is okay. I wasn't aware of that. Thank you very much for the support.

**Comment by PeterMcLennan** [comment]
Interesting.  I may have been doing exactly that. I will test this.
Thank you for your keen eye, MoacirEduardo
