### ISSUE TITLE
[Bug]: IndexError: pop from empty list

### ISSUE THREAD

**Issue by shaye059** [lllyasviel/Fooocus#2527]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Program hangs when an improper image type is given as Image Prompt. I'm unable to skip or stop in the GUI and even killing the program from command prompt appears to not work.

### Steps to reproduce the problem

1. Open the 'Input Image' menu
2. Drop or upload an unsupported image type (.avif is what I tried)

### What should have happened?

An error should appear on the screen and the task should be dropped from the queue.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.2.1
Total VRAM 12288 MB, total RAM 31895 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors
Request to load LoRAs [['sd_xl_offset_example-lora_1.0.safetensors', 0.1], ['None', 1.0], ['None', 1.0], ['None', 1.0], ['None', 1.0]] for model [C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.24 seconds
Started worker with PID 29528
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
Traceback (most recent call last):
  File "C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\gradio_hijack.py", line 278, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\gradio\processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))
  File "C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001E893DBB880>
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\Spencer\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 897, in worker
    generate_image_grid = task.args.pop(0)
IndexError: pop from empty list
```

**Comment by shaye059** [comment]
I think this might actually be a good bug for me to jump on to get familiar with the codebase. I was able to bypass the hang by changing the following block in the async_worker.py
```
--- a/modules/async_worker.py
+++ b/modules/async_worker.py
@@ -894,9 +894,9 @@ def worker():
         time.sleep(0.01)
         if len(async_tasks) > 0:
             task = async_tasks.pop(0)
-            generate_image_grid = task.args.pop(0)

             try:
+                generate_image_grid = task.args.pop(0)
                 handler(task)
                 if generate_image_grid:
```

This doesn't trigger any error or warning in the GUI though and is just using the general `except` statement so it's not a long term solution. I've never coded with gradio before so I'll have to do some digging and may have some questions!

**Comment by shaye059** [comment]
I have a small fix for this, is there a contributing guide somewhere? A quick search of the Discussions section didn't yield any information. @mashb1t

**Comment by mashb1t** [comment]
Currently there isn't, feel free to create a PR with your changes.

**Comment by nadora35** [comment]
![Untitled](https://github.com/lllyasviel/Fooocus/assets/57017061/4296afc1-9e12-4687-97a3-7e440d2aac52)
