### ISSUE TITLE
[Bug]: Error when applying metadata (a1111) with LoRAs turned off.

### ISSUE THREAD

**Issue by poor7** [lllyasviel/Fooocus#2545]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Error when applying metadata (a1111) with LoRAs turned off.
![snap2](https://github.com/lllyasviel/Fooocus/assets/154618384/2d43ace2-6281-4b8a-9663-b5478094df4f)

### Steps to reproduce the problem

1. Turn off the LoRAs switch.
2. Create an image with metadata saved in a1111 format.
3. Save the image.
4. View metadata and apply it.
![snap](https://github.com/lllyasviel/Fooocus/assets/154618384/4948add9-72a4-4fe6-9a7e-95f17861a4c8)

### What should have happened?

Metadata had to be imported.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/content/Fooocus/webui.py", line 637, in trigger_metadata_import
    parsed_parameters = metadata_parser.parse_json(parameters)
  File "/content/Fooocus/modules/meta_parser.py", line 385, in parse_json
    lora_name, lora_hash, lora_weight = lora.split(': ')
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by mashb1t** [comment]
Fixed, thanks!
