### ISSUE TITLE
Not drawing for a long time

### ISSUE THREAD

**Issue by Clqcc** [lllyasviel/Fooocus#257]
To create a public link, set `share=True` in `launch()`.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Using xformers cross attention
Exception in thread Thread-3 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\Fooocus\modules\async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\Fooocus\modules\default_pipeline.py", line 101, in <module>
    refresh_base_model(modules.path.default_base_model_name)
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\Fooocus\modules\default_pipeline.py", line 30, in refresh_base_model
    xl_base = core.load_model(filename)
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "G:\aiaiaiai\fooocus\Fooocus_win64_1-1-1035_2\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by vantang** [comment]
你的大模型下载失败了，重新下载大模型

**Comment by lllyasviel** [comment]
see recent update in readme
