### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by viren3000** [lllyasviel/Fooocus#2570]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

i used foooocus befour on my laptop but now its not working let me show you error 

### Steps to reproduce the problem

i used foooocus befour on my laptop but now its not working let me show you error 

Requirement already satisfied: pygit2==1.12.2 in /usr/local/lib/python3.10/dist-packages (1.12.2)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.21)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.0
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/content/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/Fooocus/launch.py", line 136, in <module>
    from webui import *
  File "/content/Fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/content/Fooocus/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/content/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/content/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/content/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/content/Fooocus/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/content/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### What should have happened?

what should i do

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### What operating system are you using?

windows 11

### Console logs

```Shell
Requirement already satisfied: pygit2==1.12.2 in /usr/local/lib/python3.10/dist-packages (1.12.2)
Requirement already satisfied: cffi>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.12.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.9.1->pygit2==1.12.2) (2.21)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.0
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/content/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/Fooocus/launch.py", line 136, in <module>
    from webui import *
  File "/content/Fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/content/Fooocus/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/content/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/content/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/content/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/content/Fooocus/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/content/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/content/Fooocus/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 787, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

### Additional information

!pip install pygit2==1.12.2
%cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
%cd /content/Fooocus
!python entry_with_update.py --share --always-high-vram

**Comment by mashb1t** [comment]
Please select an instance which has a GPU, e.g. T4 (default) or V100.
