### ISSUE TITLE
[Bug]: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Ldoz13** [lllyasviel/Fooocus#2575]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [x] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [x] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I am getting this when launching entry_with_update.py

  File "/home/studio-lab-user/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/studio-lab-user/Fooocus/launch.py", line 83, in <module>
    from modules import config
  File "/home/studio-lab-user/Fooocus/modules/config.py", line 7, in <module>
    import modules.flags
  File "/home/studio-lab-user/Fooocus/modules/flags.py", line 119, in <module>
    class Performance(Enum):
  File "/home/studio-lab-user/Fooocus/modules/flags.py", line 135, in Performance
    def steps(self) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(studiolab) studio-lab-user@default:~$ 

### Steps to reproduce the problem

Just Run python Fooocus/entry_with_update.py

### What should have happened?

Fooocus should have run correctly

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (other)

### Console logs

```Shell
(studiolab) studio-lab-user@default:~$ python Fooocus/entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus/entry_with_update.py']
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0]
Fooocus version: 2.3.0
Traceback (most recent call last):
  File "/home/studio-lab-user/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/studio-lab-user/Fooocus/launch.py", line 83, in <module>
    from modules import config
  File "/home/studio-lab-user/Fooocus/modules/config.py", line 7, in <module>
    import modules.flags
  File "/home/studio-lab-user/Fooocus/modules/flags.py", line 119, in <module>
    class Performance(Enum):
  File "/home/studio-lab-user/Fooocus/modules/flags.py", line 135, in Performance
    def steps(self) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(studiolab) studio-lab-user@default:~$
```

**Comment by mashb1t** [comment]
@Ldoz13 please update to Python 3.10, so this type hint operand get's recognized correctly

**Comment by mashb1t** [comment]
More context: https://peps.python.org/pep-0604/
