### ISSUE TITLE
why?help me please

### ISSUE THREAD

**Issue by DHKnight8628** [lllyasviel/Fooocus#261]
D:\Fooocus_win64_1-1-1035>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 1.0.40
Inference Engine exists.
Inference Engine checkout finished.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 16197 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 : cudaMallocAsync
Using xformers cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 101, in <module>
    refresh_base_model(modules.path.default_base_model_name)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 30, in refresh_base_model
    xl_base = core.load_model(filename)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by DHKnight8628** [comment]
D:\Fooocus_win64_1-1-1035>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Update failed.
failed to send request: 操作超时

Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 1.0.40
Inference Engine exists.
Git clone failed for Inference Engine: failed to send request: 操作超时

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 16197 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 : cudaMallocAsync
Using xformers cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 101, in <module>
    refresh_base_model(modules.path.default_base_model_name)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 30, in refresh_base_model
    xl_base = core.load_model(filename)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by DHKnight8628** [comment]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 8192 MB, total RAM 16197 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 : cudaMallocAsync
Using xformers cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 101, in <module>
    refresh_base_model(modules.path.default_base_model_name)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 30, in refresh_base_model
    xl_base = core.load_model(filename)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "D:\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...hed result=46>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...hed result=46>)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 324, in _loop_reading
  File "asyncio\proactor_events.py", line 274, in _data_received
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 182, in data_received
    self.handle_events()
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 191, in handle_events
    self.send_400_response(msg)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 301, in send_400_response
    output = self.conn.send(event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_connection.py", line 537, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_connection.py", line 272, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_state.py", line 293, in process_event
    self._fire_event_triggered_transitions(role, _event_type)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_state.py", line 311, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type Response when role=SERVER and state=MUST_CLOSE
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...hed result=46>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...hed result=46>)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 324, in _loop_reading
  File "asyncio\proactor_events.py", line 274, in _data_received
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 182, in data_received
    self.handle_events()
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 191, in handle_events
    self.send_400_response(msg)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 301, in send_400_response
    output = self.conn.send(event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_connection.py", line 537, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_connection.py", line 272, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_state.py", line 293, in process_event
    self._fire_event_triggered_transitions(role, _event_type)
  File "D:\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\h11\_state.py", line 311, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type Response when role=SERVER and state=MUST_CLOSE

**Comment by lllyasviel** [comment]
internet problem
