### ISSUE TITLE
how to set vram state to: LOW_VRAM : )

### ISSUE THREAD

**Issue by kaliwell** [lllyasviel/Fooocus#263]
D:\vmiso\Fooocus_win64_1-1-1035>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 1.0.40
Inference Engine exists.
Inference Engine checkout finished.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Total VRAM 4096 MB, total RAM 16005 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
xformers version: 0.0.20
**Set vram state to: LOW_VRAM**
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
Using xformers cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\vmiso\Fooocus_win64_1-1-1035\Fooocus\modules\async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "D:\vmiso\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 101, in <module>
    refresh_base_model(modules.path.default_base_model_name)
  File "D:\vmiso\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 30, in refresh_base_model
    xl_base = core.load_model(filename)
  File "D:\vmiso\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\vmiso\Fooocus_win64_1-1-1035\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "D:\vmiso\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "D:\vmiso\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\vmiso\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/commit/0425ea487cf3f6b348dc239f1d0d1c712ea73d63
