### ISSUE TITLE
please help me！

### ISSUE THREAD

**Issue by clarinetsz** [lllyasviel/Fooocus#266]
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 2048 and using 10 heads.
model_type EPS
adm 2816
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\Application\Fooocus_win64_1-1-1035\Fooocus\modules\async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "D:\Application\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 102, in <module>
    refresh_refiner_model(modules.path.default_refiner_model_name)
  File "D:\Application\Fooocus_win64_1-1-1035\Fooocus\modules\default_pipeline.py", line 66, in refresh_refiner_model
    xl_refiner = core.load_model(filename)
  File "D:\Application\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Application\Fooocus_win64_1-1-1035\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "D:\Application\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "D:\Application\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\Application\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by lllyasviel** [comment]
see recent update in readme
