### ISSUE TITLE
[Bug]: error trying to install fooocus happening since the last day.

### ISSUE THREAD

**Issue by MoacirEduardo** [lllyasviel/Fooocus#2676]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Happens after it starts to download Juggernaut models 
![image](https://github.com/lllyasviel/Fooocus/assets/99088947/e46c52dd-3acc-4d3a-8a5b-787ca8924dc0)

### Steps to reproduce the problem

Starts a fresh new install

### What should have happened?

Starting the download of the models and completing the installation.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1447, in connect
  File "http\client.py", line 941, in connect
  File "socket.py", line 824, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\Fooocus\launch.py", line 132, in <module>
    config.default_base_model_name, config.checkpoint_downloads = download_models(
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\Fooocus\launch.py", line 123, in download_models
    load_file_from_url(url=url, model_dir=config.paths_checkpoints[0], file_name=file_name)
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\Fooocus\modules\model_loader.py", line 25, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "C:\Users\desua\OneDrive\Área de Trabalho\Fooocus\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>
```

**Comment by eddyizm** [comment]
Have you tried to download the model manually? Also if you could post your full log to text, that is always more helpful than a screenshot of said text.

**Comment by mashb1t** [comment]
Either HuggingFace has had an outage or your network configuration / firewall has changed to not permit downloads from this URL anymore.
Please try again, check your network and post the full log, thanks!

**Comment by MoacirEduardo** [comment]
I think there was a partial outage with HuggingFace, but now it seems to be back to normal, although the download is very slow and experiencing some interruptions. Thanks a lot for the response; it seems to be a problem with HuggingFace.

**Comment by MoacirEduardo** [comment]
Another question: if one module does not finish the installation and stops downloading, and I restart Fooocus, and it restarts the download, will it automatically erase the previously partially downloaded archives and not affect the functionality of Fooocus? Since I am experiencing constant interruptions while downloading materials from HuggingFace.

**Comment by mashb1t** [comment]
it will not remove the partially downloaded files but will also not impact the functionality as long as no corrupt file is used.

**Comment by MoacirEduardo** [comment]
Thanks.
