### ISSUE TITLE
unable to generate picture

### ISSUE THREAD

**Issue by franxis11088** [lllyasviel/Fooocus#268]
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Fooocus_win64_1-1-10\Fooocus\modules\async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "E:\Fooocus_win64_1-1-10\Fooocus\modules\default_pipeline.py", line 101, in <module>
    refresh_base_model(modules.path.default_base_model_name)
  File "E:\Fooocus_win64_1-1-10\Fooocus\modules\default_pipeline.py", line 30, in refresh_base_model
    xl_base = core.load_model(filename)
  File "E:\Fooocus_win64_1-1-10\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Fooocus_win64_1-1-10\Fooocus\modules\core.py", line 41, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "E:\Fooocus_win64_1-1-10\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1191, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", fp16)
  File "E:\Fooocus_win64_1-1-10\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_detection.py", line 119, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, use_fp16)
  File "E:\Fooocus_win64_1-1-10\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_detection.py", line 36, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'

**Comment by mashb1t** [comment]
Please make sure to only use SD1.5 models as base models and check if the model is corrupt.
