### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'rpds.rpds'

### ISSUE THREAD

**Issue by shomc-xxj** [lllyasviel/Fooocus#2705]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I've been using Fooocus for about two months and everything is ok,but suddenly,this morning  when I launched the "run.bat", or"the other two bats" was greeted with the error:
……
 File "F:\fooocus\python_embeded\lib\site-packages\referencing\_core.py", line 8, in <module>
    from rpds import HashTrieMap, HashTrieSet, List
  File "F:\fooocus\python_embeded\lib\site-packages\rpds\__init__.py", line 1, in <module>
    from .rpds import *
ModuleNotFoundError: No module named 'rpds.rpds'
F:\fooocus>pause
 So,I checked the pythonpath and the pile name,and all is ok.
i have no idea of it .

### Steps to reproduce the problem

I have checked  and they are  normal: the module package has been installed

### What should have happened?

fooocus should start normally

### What browsers do you use to access Fooocus?

Microsoft Edge

### Where are you running Fooocus?

Locally

### Console logs

```Shell
F:\fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset anime
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'anime']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.3.1
Loaded preset: F:\fooocus\Fooocus\presets\anime.json
[Cleanup] Attempting to delete content of temp dir C:\Users\chenhao\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "F:\fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "F:\fooocus\Fooocus\launch.py", line 136, in <module>
    from webui import *
  File "F:\fooocus\Fooocus\webui.py", line 1, in <module>
    import gradio as gr
  File "F:\fooocus\python_embeded\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "F:\fooocus\python_embeded\lib\site-packages\gradio\components\__init__.py", line 3, in <module>
    from gradio.components.bar_plot import BarPlot
  File "F:\fooocus\python_embeded\lib\site-packages\gradio\components\bar_plot.py", line 7, in <module>
    import altair as alt
  File "F:\fooocus\python_embeded\lib\site-packages\altair\__init__.py", line 607, in <module>
    from .vegalite import *
  File "F:\fooocus\python_embeded\lib\site-packages\altair\vegalite\__init__.py", line 2, in <module>
    from .v5 import *
  File "F:\fooocus\python_embeded\lib\site-packages\altair\vegalite\v5\__init__.py", line 2, in <module>
    from .schema import *
  File "F:\fooocus\python_embeded\lib\site-packages\altair\vegalite\v5\schema\__init__.py", line 2, in <module>
    from .core import *
  File "F:\fooocus\python_embeded\lib\site-packages\altair\vegalite\v5\schema\core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "F:\fooocus\python_embeded\lib\site-packages\altair\utils\__init__.py", line 1, in <module>
    from .core import (
  File "F:\fooocus\python_embeded\lib\site-packages\altair\utils\core.py", line 14, in <module>
    import jsonschema
  File "F:\fooocus\python_embeded\lib\site-packages\jsonschema\__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "F:\fooocus\python_embeded\lib\site-packages\jsonschema\_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "F:\fooocus\python_embeded\lib\site-packages\jsonschema\exceptions.py", line 15, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
  File "F:\fooocus\python_embeded\lib\site-packages\referencing\__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "F:\fooocus\python_embeded\lib\site-packages\referencing\_core.py", line 8, in <module>
    from rpds import HashTrieMap, HashTrieSet, List
  File "F:\fooocus\python_embeded\lib\site-packages\rpds\__init__.py", line 1, in <module>
    from .rpds import *
ModuleNotFoundError: No module named 'rpds.rpds'

F:\fooocus>pause
```

**Comment by shomc-xxj** [comment]
I found the reason. It was the 360 ​​software that automatically deleted the “rpds.cp310-win_amd64.pyd file in rpds”
