### ISSUE TITLE
error api client

### ISSUE THREAD

**Issue by StartHua** [lllyasviel/Fooocus#274]
Traceback (most recent call last):
  File "F:\AI\Fooocus_win64_1-1-1035\test.py", line 4, in <module>
    result = client.predict(
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\client.py", line 291, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\client.py", line 1120, in result
    return super().result(timeout=timeout)
  File "D:\python\Anaconda\envs\test\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "D:\python\Anaconda\envs\test\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\python\Anaconda\envs\test\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\client.py", line 794, in _inner
    predictions = self.process_predictions(*predictions)
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\client.py", line 984, in process_predictions
    predictions = self.deserialize(*predictions)
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\client.py", line 970, in deserialize
    [
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\client.py", line 971, in <listcomp>
    s.deserialize(
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\serializing.py", line 203, in deserialize
    file = utils.decode_base64_to_file(x, dir=save_dir)
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\utils.py", line 436, in decode_base64_to_file
    data, extension = decode_base64_to_binary(encoding)
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\utils.py", line 401, in decode_base64_to_binary
    extension = get_extension(encoding)
  File "D:\python\Anaconda\envs\test\lib\site-packages\gradio_client\utils.py", line 347, in get_extension
    encoding = encoding.replace("audio/wav", "audio/x-wav")
AttributeError: 'dict' object has no attribute 'replace'

**Comment by shirubei** [comment]
#172
