### ISSUE TITLE
[feat req / bug fix] Memory Leak in Colab T4: torch.cuda.OutOfMemoryError after few generations

### ISSUE THREAD

**Issue by mratanusarkar** [lllyasviel/Fooocus#288]
I have been trying out Fooocus in colab, (with default advance settings, 2 image gens)
but I have observed, that after a few runs (around 4th or 5th run) the UI hangs and in colab, the following error is thrown:
`torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)`

It's frustrating to restart and re-run the notebook every time.
It would be cool to get: 
- [feature request] a new button that can flash out the memory or the cache
- [bugfix] or get this memory issue identified and fixed

here is a full stack-trace for reference:
```bash
Image generated with private log at: /content/Fooocus/outputs/2023-08-29/log.html
  0% 0/30 [00:01<?, ?it/s]
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/Fooocus/modules/async_worker.py", line 104, in worker
    handler(task)
  File "/content/Fooocus/modules/async_worker.py", line 75, in handler
    imgs = pipeline.process(p_txt, n_txt, steps, switch, width, height, seed, callback=callback)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/default_pipeline.py", line 141, in process
    sampled_latent = core.ksampler_with_refiner(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/modules/core.py", line 225, in ksampler_with_refiner
    samples = sampler.sample(noise, positive_copy, negative_copy, refiner_positive=refiner_positive_copy,
  File "/content/Fooocus/modules/samplers_advanced.py", line 236, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/k_diffusion/sampling.py", line 644, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/k_diffusion/sampling.py", line 615, in sample_dpmpp_2m_sde
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "/content/Fooocus/modules/samplers_advanced.py", line 223, in <lambda>
    k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)
  File "/content/Fooocus/modules/samplers_advanced.py", line 168, in callback
    callback_function(step, x0, x, total_steps)
  File "/content/Fooocus/modules/core.py", line 197, in callback
    y = previewer.preview(x0, step, total_steps)
  File "/content/Fooocus/modules/core.py", line 84, in preview_function
    x_sample = taesd.decoder(torch.nn.functional.avg_pool2d(x0, kernel_size=(2, 2))).detach() * 255.0
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/taesd/taesd.py", line 23, in forward
    return self.fuse(self.conv(x) + self.skip(x))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/activation.py", line 103, in forward
    return F.relu(input, inplace=self.inplace)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 1457, in relu
    result = torch.relu(input)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 14.04 GiB
Requested               : 63.00 MiB
Device limit            : 14.75 GiB
Free (according to CUDA): 2.81 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
```

google colab resource stats after a few runs (4-5), when this issue occurs:
![Screenshot from 2023-08-29 10-06-05 crop](https://github.com/lllyasviel/Fooocus/assets/34891206/7131ff2b-4756-4c09-a51d-94cbf78d42aa)

>Note: I tried replicating it, and it happens every time on the 5th run for me, with this exact error stack

**Comment by joanorsky** [comment]
Yep... it does have a leak! Happens all the time..

**Comment by geeknjuice** [comment]
Same memory leak issue here, @MoonRide303 version seems to have fixed the issue on colab. Maybe he could help ?

**Comment by MoonRide303** [comment]
@lllyasviel Changes on [my fork](https://github.com/MoonRide303/Fooocus-MRE) related to memory management:
- I use updated Comfy (from master), and using related changes for loading models in core.py (load_models_gpu() calls),
- comfy.model_management.DISABLE_SMART_MEMORY = True in core (otherwise it tries to eat whole available VRAM - I prefer old approach)
- at the end of process() in default_pipeline.py:
```
    clean_prompt_cond_caches()
    gc.collect()
    soft_empty_cache()
```
prompt caches need to be cleared after each image in batch - otherwise every image beyond first one gets deformed (I tried to reach you on Discord about that, but I guess you were busy with CNs for SD web UI).

I had to disable loading refiner model on Colab, though - for some reason it stops working when trying to use refiner model (no idea why :/).

**Comment by lanyusan** [comment]
@MoonRide303 I have used a script to submit tasks to your fork. It crashed after around 33 generates continuously.

It seems the problem is still there.

The error message is pretty simple: ` 1709813 Killed  `, which mostly means out of memory.

**Comment by MoonRide303** [comment]
@lanyusan I am not observing that kind of problems on my machine, so we'd first need to figure out what might be causing it on yours:
1. Are you using full version of mine (that with bundled environment), or something of your own making? I did test yesterday with bigger number of images (increased limits yesterday on MRE - it makes sense now, after I've added possibility to stop Generation), and 128 of them generated just fine on my machine.
2. Do you have enough RAM (like 32 GB) and/or enabled virtual memory (with enough free disk space that could be used for swapping)?

**Comment by lanyusan** [comment]
I am using your standard version. 

I am using a PC of Ubuntu 22.04, with  32G RAM and a 3080 16G card. 

However I did have a lot of applications running competing for RAM. That might be the reason.

**Comment by MoonRide303** [comment]
@lanyusan You can check out how much free memory and swap you have before launching Fooocus with `free -h` command. To avoid runnning into memory issues you should have at least 20 GB of free RAM + swap before launching Fooocus.

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
