### ISSUE TITLE
error running Fooocus in Local Ubuntu system (ComfyUI Issues)

### ISSUE THREAD

**Issue by mratanusarkar** [lllyasviel/Fooocus#289]
I am having trouble running the setup in my local Ubuntu system.
OS: Ubuntu 20.04.6 LTS

on following the installation steps from the [readme #linux](https://github.com/lllyasviel/Fooocus#linux), I was getting the following error as mentioned in [issue #169 comment](https://github.com/lllyasviel/Fooocus/issues/169#issuecomment-1695476523) (see the thread for the error stack)

I tried resolving the same by following the suggestions from @maxchiron and @WangZhiqiang-academia,
and downloaded [ComfyUI](https://github.com/comfyanonymous/ComfyUI) manually, and put the whole repo files inside `/ComfyUI-from-StabilityAI-Official`.

I also see the `launch.py` script running successfully, and models getting downloaded,
but I end up with the following error:
```bash
(fooocus) atanu@mratanusarkar:~/Workspace/project-diffusers/Fooocus$ python launch.py
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Fooocus version: 1.0.41
Inference Engine exists.
Git clone failed for Inference Engine: failed to resolve address for github.com: Name or service not known
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0_0.9vae.safetensors" to /home/atanu/Workspace/project-diffusers/Fooocus/models/checkpoints/sd_xl_base_1.0_0.9vae.safetensors

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.46G/6.46G [04:38<00:00, 24.9MB/s]
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0_0.9vae.safetensors" to /home/atanu/Workspace/project-diffusers/Fooocus/models/checkpoints/sd_xl_refiner_1.0_0.9vae.safetensors

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.66G/5.66G [03:59<00:00, 25.4MB/s]
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors" to /home/atanu/Workspace/project-diffusers/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47.3M/47.3M [00:03<00:00, 15.2MB/s]
Total VRAM 24252 MB, total RAM 257467 MB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Exception in thread Thread-4 (worker):
Traceback (most recent call last):
  File "/home/atanu/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/atanu/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/atanu/Workspace/project-diffusers/Fooocus/modules/async_worker.py", line 14, in worker
    import modules.default_pipeline as pipeline
  File "/home/atanu/Workspace/project-diffusers/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/home/atanu/Workspace/project-diffusers/Fooocus/modules/core.py", line 12, in <module>
    from comfy.sample import prepare_mask, broadcast_cond, load_additional_models, cleanup_additional_models
ImportError: cannot import name 'load_additional_models' from 'comfy.sample' (/home/atanu/Workspace/project-diffusers/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/sample.py)
```

Somebody please help me out here. Any clue on what I am doing wrong?

**Comment by lllyasviel** [comment]
internet problem : 

Git clone failed for Inference Engine: failed to resolve address for github.com: Name or service not known
