### ISSUE TITLE
 CUDA out of memory.

### ISSUE THREAD

**Issue by 917017420** [lllyasviel/Fooocus#303]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [07:31<00:00, 15.06s/it]
Warning: Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "D:\fooocus\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 640, in decode
    pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(samples) + 1.0) / 2.0, min=0.0, max=1.0).cpu().float()
  File "D:\fooocus\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "D:\fooocus\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\fooocus\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\modules\diffusionmodules\model.py", line 727, in forward
    h = self.up[i_level].upsample(h)
  File "D:\fooocus\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\fooocus\Fooocus_win64_1-1-1035\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\ldm\modules\diffusionmodules\model.py", line 61, in forward
    x = self.conv(x)
  File "D:\fooocus\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\fooocus\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\fooocus\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1008.00 MiB (GPU 0; 4.00 GiB total capacity; 1.57 GiB already allocated; 522.64 MiB free; 1.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

GPU is GTX 1650
help me!

**Comment by wpl427** [comment]
4GB......

**Comment by 917017420** [comment]
> 4GB......

另外的 1050Ti都行

**Comment by mashb1t** [comment]
Please find the official minimal requirements here: https://github.com/lllyasviel/Fooocus?tab=readme-ov-file#minimal-requirement.
You need at least 8GB (* 6GB uncertain)  of VRAM + swap in order to be able to use Fooocus.

**Comment by saxash9** [comment]
Have been successfully running Fooocus with GTX 1650 (4gb VRAM, 8GB RAM) with PyTorch version 2.2.2 and adding "--unet-in-bf16 --vae-in-bf16 --clip-in-fp16" in run.bat
The generations take 4-5min per image.
(I do see 'Warning: Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding.' but no errors)
