### ISSUE TITLE
[Bug]: the turbo scheduler doesnt work 

### ISSUE THREAD

**Issue by astro1df** [lllyasviel/Fooocus#3060]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

it just errors out and doesnt generate image

### Steps to reproduce the problem

![image](https://github.com/lllyasviel/Fooocus/assets/112957642/d5124b15-a165-4e57-9772-d4291d83840a)

### What should have happened?

generate the image

### Where are you running Fooocus?

Locally

### What operating system are you using?

w11

### Console logs

```Shell
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1024, 1024)
Preparation time: 3.24 seconds
[Fooocus] Preparing task 1/1 ...
[Sampler] refiner_swap_method = joint
Traceback (most recent call last):
  File "c:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 979, in worker
    handler(task)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 869, in handler
    imgs = pipeline.process_diffusion(
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 366, in process_diffusion
    minmax_sigmas = calculate_sigmas(sampler=sampler_name, scheduler=scheduler_name, model=final_unet.model, steps=steps, denoise=denoise)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 309, in calculate_sigmas
    sigmas = calculate_sigmas_all(sampler, model, scheduler, steps)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 298, in calculate_sigmas_all
    sigmas = calculate_sigmas_scheduler(model, scheduler, steps)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\Fooocus\modules\sample_hijack.py", line 178, in calculate_sigmas_scheduler_hacked
    sigmas = SDTurboScheduler().get_sigmas(namedtuple('Patcher', ['model'])(model=model), steps=steps, denoise=1.0)[0]
  File "c:\Fooocus_win64_2-1-831\Fooocus\ldm_patched\contrib\external_custom_sampler.py", line 110, in get_sigmas
    ldm_patched.modules.model_management.load_models_gpu([model])
  File "c:\Fooocus_win64_2-1-831\Fooocus\modules\patch.py", line 447, in patched_load_models_gpu
    y = ldm_patched.modules.model_management.load_models_gpu_origin(*args, **kwargs)
  File "c:\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 388, in load_models_gpu
    loaded_model = LoadedModel(x)
  File "c:\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_management.py", line 280, in __init__
    self.device = model.load_device
AttributeError: 'Patcher' object has no attribute 'load_device'
```

**Comment by mashb1t** [comment]
@astro1df thank you for reporting, fixed in https://github.com/lllyasviel/Fooocus/pull/3065. Please pull main or restart Fooocus.
