### ISSUE TITLE
[Bug]:  Fooocus 2.4.2 TCD broken - not working

### ISSUE THREAD

**Issue by k8kiss** [lllyasviel/Fooocus#3099]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

It doesn't start the image generation

### Steps to reproduce the problem

[Fooocus Model Management] Moving model(s) has taken 1.14 seconds
Traceback (most recent call last):
  File "G:\foocus_OG\Fooocus\modules\async_worker.py", line 998, in worker
    handler(task)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\async_worker.py", line 888, in handler
    imgs = pipeline.process_diffusion(
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\default_pipeline.py", line 379, in process_diffusion
    sampled_latent = core.ksampler(
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\core.py", line 310, in ksampler
    samples = ldm_patched.modules.sample.sample(model,
  File "G:\foocus_OG\Fooocus\ldm_patched\modules\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\foocus_OG\Fooocus\ldm_patched\modules\samplers.py", line 712, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\sample_hijack.py", line 158, in sample_hacked
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback_wrap, noise, latent_image, denoise_mask, disable_pbar)
  File "G:\foocus_OG\Fooocus\ldm_patched\modules\samplers.py", line 557, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\ldm_patched\k_diffusion\sampling.py", line 821, in sample_tcd
    alpha_prod_s = model_sampling.alphas_cumprod[timesteps_s]
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ModelSampling' object has no attribute 'alphas_cumprod'

### What should have happened?

Generate image

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
[Fooocus Model Management] Moving model(s) has taken 1.14 seconds
Traceback (most recent call last):
  File "G:\foocus_OG\Fooocus\modules\async_worker.py", line 998, in worker
    handler(task)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\async_worker.py", line 888, in handler
    imgs = pipeline.process_diffusion(
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\default_pipeline.py", line 379, in process_diffusion
    sampled_latent = core.ksampler(
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\core.py", line 310, in ksampler
    samples = ldm_patched.modules.sample.sample(model,
  File "G:\foocus_OG\Fooocus\ldm_patched\modules\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\foocus_OG\Fooocus\ldm_patched\modules\samplers.py", line 712, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\modules\sample_hijack.py", line 158, in sample_hacked
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback_wrap, noise, latent_image, denoise_mask, disable_pbar)
  File "G:\foocus_OG\Fooocus\ldm_patched\modules\samplers.py", line 557, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\foocus_OG\Fooocus\ldm_patched\k_diffusion\sampling.py", line 821, in sample_tcd
    alpha_prod_s = model_sampling.alphas_cumprod[timesteps_s]
  File "G:\foocus_OG\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ModelSampling' object has no attribute 'alphas_cumprod'
```

### Additional information

no

**Comment by k8kiss** [comment]
Looks like this happens when choosing tcd sampler, I've been using it since 2.4.1 included it and really like it. I am not sure why is now broken.

Also this new version is super slow! Any way to go back to 2.41? I didn't back up.

**Comment by kurttu4** [comment]
add in .\Fooocus\modules\patch_precision.py
55            self.alphas_cumprod = alphas_cumprod

**Comment by k8kiss** [comment]
> add in .\Fooocus\modules\patch_precision.py 55 self.alphas_cumprod = alphas_cumprod

NameError: name 'alphas_cumprod' is not defined

**Comment by mashb1t** [comment]
> Looks like this happens when choosing tcd sampler, I've been using it since 2.4.1 included it and really like it. I am not sure why is now broken.
> 
> Also this new version is super slow! Any way to go back to 2.41? I didn't back up.

we really need more tests, it's hard to keep track of everything. Will check in a few hours again. Peobably it's only this one method being called for TCD, tested everything else and for speed nothing shzld have changed as there were no substantial changes for the  sampling and pipeline.

**Comment by mashb1t** [comment]
Fixed in main, please restart Fooocus.
See https://github.com/lllyasviel/Fooocus/pull/3106
