### ISSUE TITLE
[Installation bug]No module named 'comfy.cli_args'

### ISSUE THREAD

**Issue by tangyunlong** [lllyasviel/Fooocus#310]
I tried to deploy Fooocus on Ubuntu22.04, after I followed the installation instructions to complete the installation. Run python launch.py. There will be the following error:
Traceback (most recent call last):
  File "/home/tangyunlong/Fooocus/launch.py", line 88, in <module>
    clear_comfy_args()
  File "/home/tangyunlong/Fooocus/launch.py", line 78, in clear_comfy_args
    import comfy.cli_args
ModuleNotFoundError: No module named 'comfy.cli_args'
Comfy seems to be the library file of the ComfyUI project.（stable diffusion GUI and backend.）
I don't know how to combine the two projects.

**Comment by snakeninny** [comment]
You can refer to https://github.com/lllyasviel/Fooocus/issues/169#issuecomment-1694882475

**Comment by tangyunlong** [comment]
Thank you for your help:), I refer to your help to replace ComfyUI, the project seems to be able to run on Ubuntu, but in the process of generating pictures there will be errors, it seems that ComfyUI updated a lot of code, there are some bug, such as: function name is incorrect, or data type problems, I tried to fix it, but may not be successful.

**Comment by lllyasviel** [comment]
please follow official installation guidelines.
