### ISSUE TITLE
[Bug]: Cannot install Fooocus due to error when executing run.bat related to NVIDIA driver

### ISSUE THREAD

**Issue by hlong24399** [lllyasviel/Fooocus#3126]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I am trying to run a clean installation of Fooocus but the error is shown as below, this is the current state of the terminal after executing run.bat

```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Desktop\AI>pause
Press any key to continue . . .
```

However I am having AMD GPU and driver

![image](https://github.com/lllyasviel/Fooocus/assets/54257351/4e43d9a5-df81-4075-a9b4-c2271edba204)

### Steps to reproduce the problem

1. Double click run.bat script after extraction.

### What should have happened?

Fooocus should have installed the library successfully on windows 11.

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 11

### Console logs

```Shell
C:\Users\hlong\Desktop\AI_STUFF>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Fast-forward merge
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.4.3
[Cleanup] Attempting to delete content of temp dir C:\Users\hlong\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/mashb1t/misc/resolve/main/xl-to-v1_interposer-v4.0.safetensors" to C:\Users\hlong\Desktop\AI_STUFF\Fooocus\models\vae_approx\xl-to-v1_interposer-v4.0.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 5.40M/5.40M [00:00<00:00, 9.90MB/s]
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to C:\Users\hlong\Desktop\AI_STUFF\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 6.62G/6.62G [06:28<00:00, 18.3MB/s]
Traceback (most recent call last):
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\launch.py", line 140, in <module>
    from webui import *
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\modules\async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\modules\patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\ldm_patched\modules\model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\ldm_patched\ldm\modules\diffusionmodules\openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\ldm_patched\ldm\modules\attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\ldm_patched\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\ldm_patched\modules\model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\hlong\Desktop\AI_STUFF\Fooocus\ldm_patched\modules\model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\hlong\Desktop\AI_STUFF\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\hlong\Desktop\AI_STUFF\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

C:\Users\hlong\Desktop\AI_STUFF>pause
Press any key to continue . . .
```

**Comment by hlong24399** [comment]
Have been resolved by following official installation guide by editting run.bat.
