### ISSUE TITLE
[Bug]: Install Issue

### ISSUE THREAD

**Issue by thedarkknight197** [lllyasviel/Fooocus#3137]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Install dependencies not working in Fedora 40

### Steps to reproduce the problem

- git clone https://github.com/lllyasviel/Fooocus.git
- cd Fooocus
- pip3 install -r requirements_versions.txt

### What should have happened?

Install depencencies

### Where are you running Fooocus?

Locally

### What operating system are you using?

Fedora 40 - Linux 6.8.11-300.fc40.x86_64

### Console logs

```Shell
michele@DESKTOP-7A9KNPI:~/IdeaProjects/Fooocus$ pip3 install -r requirements_versions.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting torchsde==0.2.5 (from -r requirements_versions.txt (line 1))
  Using cached torchsde-0.2.5-py3-none-any.whl.metadata (748 bytes)
Collecting einops==0.4.1 (from -r requirements_versions.txt (line 2))
  Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting transformers==4.30.2 (from -r requirements_versions.txt (line 3))
  Using cached transformers-4.30.2-py3-none-any.whl.metadata (113 kB)
Collecting safetensors==0.3.1 (from -r requirements_versions.txt (line 4))
  Using cached safetensors-0.3.1.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting accelerate==0.21.0 (from -r requirements_versions.txt (line 5))
  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
Collecting pyyaml==6.0 (from -r requirements_versions.txt (line 6))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/michele/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/michele/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/michele/.local/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/tmp/pip-build-env-2s4taltd/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
michele@DESKTOP-7A9KNPI:~/IdeaProjects/Fooocus$
```

### Additional information

My hardware:
- AMD ryzen 9 7900x 12c/24t
- 32gb ram ddr5 Corsair Vegance 6000mhz
- RTX 4080 Super MSI Suprim X 

Nvidia Driver:
```
michele@DESKTOP-7A9KNPI:~$ inxi -G
Graphics:
  Device-1: NVIDIA AD103 [GeForce RTX 4080 SUPER] driver: nvidia v: 550.78
  Device-2: AMD Raphael driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 24.1 with: Xwayland v: 24.1.0
    compositor: gnome-shell v: 46.2 driver: X: loaded: nouveau
    gpu: nvidia,nvidia-nvswitch resolution: 2560x1440~165Hz
  API: OpenGL v: 4.6.0 vendor: nvidia v: 550.78 renderer: NVIDIA GeForce
    RTX 4080 SUPER/PCIe/SSE2
  API: EGL Message: EGL data requires eglinfo. Check --recommends.

```

**Comment by llagerlof** [comment]
Exactly same problem here. The only difference is that I am using venv, following README instructions:

```
git clone https://github.com/lllyasviel/Fooocus.git
cd Fooocus
python3 -m venv fooocus_env
source fooocus_env/bin/activate
pip install -r requirements_versions.txt
```

**Environment:**

OS: Updated EndeavourOS.
Python 3.12.3

Also tried to install `pyyaml 6.0` individually, inside the project venv. Same Error.

**Comment by shubhexists** [comment]
Getting the same issue on Ubuntu 20.04 using the venv method.

**Comment by mashb1t** [comment]
Python 3.12 is not supported, see https://github.com/lllyasviel/Fooocus/issues/2938. Please use python 3.10 (recommended) or 3.11.
