### ISSUE TITLE
TimeoutError after launching

### ISSUE THREAD

**Issue by younyokel** [lllyasviel/Fooocus#314]
I am seeing the following error:
```
Fast-forward merge
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 1.0.45
Inference Engine exists.
Inference Engine checkout finished.
Running on local URL:  http://127.0.0.1:7861
Traceback (most recent call last):
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 705, in readinto
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7861): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Stable Diffusion XL\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\Program Files\Stable Diffusion XL\Fooocus\launch.py", line 93, in <module>
    from webui import *
  File "D:\Program Files\Stable Diffusion XL\Fooocus\webui.py", line 122, in <module>
    shared.gradio_root.launch(inbrowser=True, server_name=args.listen, server_port=args.port, share=args.share)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\gradio\blocks.py", line 1912, in launch
    if _frontend and (not networking.url_ok(self.local_url)) and (not self.share):
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\gradio\networking.py", line 202, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\Stable Diffusion XL\python_embeded\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7861): Read timed out. (read timeout=3)
```
The error keeps appearing although it worked just fine a day or two ago. It sometimes launches, but then this error again.

**Comment by younyokel** [comment]
My port got changed to the same one as the Automatic1111 WebUI and I believe it was the reason it didn't work. However, I'm puzzled as to why it didn't work, especially considering that the WebUI wasn't active when I launched Fooocus..

**Comment by jasonphil14** [comment]
> My port got changed to the same one as the Automatic1111 WebUI and I believe it was the reason it didn't work. However, I'm puzzled as to why it didn't work, especially considering that the WebUI wasn't active when I launched Fooocus..
> 
> I just added --port in launch file.

please how did you add it? i have similar problem with foocus

**Comment by pen-ll** [comment]
close your proxy will fix it

**Comment by younyokel** [comment]
> close your proxy will fix it

I don't use a proxy

**Comment by Tamaritka** [comment]
> close your proxy will fix it

Thank you!
