### ISSUE TITLE
[Bug]: launcher doesnt start with 390 driver

### ISSUE THREAD

**Issue by osevan** [lllyasviel/Fooocus#3208]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

git clone https://github.com/lllyasviel/Fooocus.git
cd Fooocus
python3 -m venv fooocus_env
source fooocus_env/bin/activate
pip install -r requirements-modded.txt

See the above sections for model downloads. You can launch the software with:

source fooocus_env/bin/activate
python entry_with_update.py

Or, if you want to open a remote port, use

source fooocus_env/bin/activate
python entry_with_update.py --listen

userFooocus]$ ./fooocus_env/
bin/     include/ lib/     lib64/   share/
[userFooocus]$ ./fooocus_env/
bash: ./fooocus_env/: Ist ein Verzeichnis
[userFooocus]$ nano config.txt
[userFooocus]$ ^C
[userFooocus]$ sudo python launch.py
[sudo] Passwort für user:
[System ARGV] ['launch.py']
Python 3.12.4 (main, Jun 18 2024, 13:54:05) [GCC 14.1.1 20240522]
Fooocus version: 2.4.3
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/home/user/compile/Fooocus/launch.py", line 140, in <module>
    from webui import *
  File "/home/user/compile/Fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/home/user/compile/Fooocus/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/home/user/compile/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/home/user/compile/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/home/user/compile/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/home/user/compile/Fooocus/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/home/user/compile/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/home/user/compile/Fooocus/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/user/compile/Fooocus/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/compile/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/home/user/compile/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

### Steps to reproduce the problem

git clone https://github.com/lllyasviel/Fooocus.git
cd Fooocus
python3 -m venv fooocus_env
source fooocus_env/bin/activate
pip install -r requirements-modded.txt

My modded.txt is here

torchsde
einops
transformers
safetensors
accelerate
pyyaml
Pillow
scipy
tqdm
psutil
pytorch_lightning
omegaconf
gradio==3.41.2
pygit2
opencv-contrib-python
diffusers
httpx
onnxruntime
timm
translators
rembg
groundingdino-py

### What should have happened?

Start

### Where are you running Fooocus?

None

### What operating system are you using?

arch linux 

### Console logs

```Shell
userFooocus]$ ./fooocus_env/
bin/     include/ lib/     lib64/   share/
[userFooocus]$ ./fooocus_env/
bash: ./fooocus_env/: Ist ein Verzeichnis
[userFooocus]$ nano config.txt
[userFooocus]$ ^C
[userFooocus]$ sudo python launch.py
[sudo] Passwort für ra:
[System ARGV] ['launch.py']
Python 3.12.4 (main, Jun 18 2024, 13:54:05) [GCC 14.1.1 20240522]
Fooocus version: 2.4.3
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/home/user/compile/Fooocus/launch.py", line 140, in <module>
    from webui import *
  File "/home/user/compile/Fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/home/user/compile/Fooocus/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/home/user/compile/Fooocus/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/home/user/compile/Fooocus/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/home/user/compile/Fooocus/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/home/user/compile/Fooocus/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/home/user/compile/Fooocus/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/home/user/compile/Fooocus/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/user/compile/Fooocus/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/compile/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/cuda/__init__.py", line 778, in current_device
    _lazy_init()
  File "/home/user/compile/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
```

**Comment by mashb1t** [comment]
This is correct, older drivers are not supported. Also keep in mind that currently Fooocus only officially supports Python 3.10 and 3.11, but not 3.12.

> The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver [...]
