### ISSUE TITLE
[Bug]: Refiner SD 1.5 NSFW models do not work at all. Censured?

### ISSUE THREAD

**Issue by Cratertempus** [lllyasviel/Fooocus#3239]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

If Model Refiner can use SDXL or SD 1.5, why is NSFW SD 1.5 censured?

### Steps to reproduce the problem

1 - Go to Model, add any SD 1.5 as Refiner.
2.1 - If the model is not NSFW, an image will be generated
2.2 -If the model is NSFW, an image will not be generated

### What should have happened?

Fooocus should generate something, but stops. Some models were tested, with the same result. Is that censured? Is there any way to unlock it if so?

### Where are you running Fooocus?

Locally

### What operating system are you using?

Windows 10

### Console logs

```Shell
C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.4.3
[Cleanup] Attempting to delete content of temp dir C:\Users\JD3K\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 12288 MB, total RAM 16319 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 3.41.2, however version 4.29.0 is available, please upgrade.
--------
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
Base model loaded: C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors
VAE loaded: None
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.1)] for model [C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\models\loras\sd_xl_offset_example-lora_1.0.safetensors] for UNet [C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\models\checkpoints\juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.59 seconds
Started worker with PID 13988
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] CLIP Skip = 2
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 1168537835611695896
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 60 - 24
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Traceback (most recent call last):
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 998, in worker
    handler(task)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 469, in handler
    pipeline.refresh_everything(refiner_model_name=refiner_model_name, base_model_name=base_model_name,
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 249, in refresh_everything
    refresh_refiner_model(refiner_model_name)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\default_pipeline.py", line 96, in refresh_refiner_model
    model_refiner = core.load_model(filename)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\modules\core.py", line 147, in load_model
    unet, clip, vae, vae_filename, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings,
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\sd.py", line 449, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_detection.py", line 163, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "C:\Users\JD3K\Desktop\Fooocus_win64_2-1-831\Fooocus\ldm_patched\modules\model_detection.py", line 49, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'
Total time: 0.31 seconds
```

### Additional information

It has nothing to do with hardware.

**Comment by Cratertempus** [comment]
I'm such a fool. I was using LoRA as checkpoints.
