### ISSUE TITLE
stuck at this in first generation on ryzen 5 5600h rtx 3050 4gb

### ISSUE THREAD

**Issue by Ramam001** [lllyasviel/Fooocus#326]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:57<00:00,  3.92s/it]
Image generated with private log at: X:\A1111\FOCUS\Fooocus\outputs\2023-09-09\log.html
ERROR diffusion_model.output_blocks.2.1.transformer_blocks.2.ff.net.0.proj.weight [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 52428800 bytes.
ERROR diffusion_model.output_blocks.2.1.transformer_blocks.2.ff.net.2.weight [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 26214400 bytes.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "X:\A1111\FOCUS\Fooocus\modules\async_worker.py", line 104, in worker
    handler(task)
  File "X:\A1111\FOCUS\Fooocus\modules\async_worker.py", line 75, in handler
    imgs = pipeline.process(p_txt, n_txt, steps, switch, width, height, seed, callback=callback)
  File "X:\A1111\FOCUS\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\A1111\FOCUS\Fooocus\modules\default_pipeline.py", line 151, in process
    sampled_latent = core.ksampler_with_refiner(
  File "X:\A1111\FOCUS\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "X:\A1111\FOCUS\Fooocus\modules\core.py", line 208, in ksampler_with_refiner
    comfy.model_management.load_model_gpu(model)
  File "X:\A1111\FOCUS\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 296, in load_model_gpu
    raise e
  File "X:\A1111\FOCUS\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\model_management.py", line 292, in load_model_gpu
    real_model = model.patch_model(device_to=patch_model_to)
  File "X:\A1111\FOCUS\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 386, in patch_model
    temp_weight = weight.to(torch.float32, copy=True)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 52428800 bytes.

**Comment by mashb1t** [comment]
Please double-check if you have set up swap according to our troubleshooting guide https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#system-swap and feel free to reopen the issue if this is still relevant.
