### ISSUE TITLE
[Bug]: module 'httpx' has no attribute 'AsyncClient'

### ISSUE THREAD

**Issue by mikwee** [lllyasviel/Fooocus#3309]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Whenever I try to launch Fooocus, even in a clean installation, I get this error:
```
Traceback (most recent call last):
  File "/home/testuser/Fooocus-new/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/testuser/Fooocus-new/launch.py", line 147, in <module>
    from webui import *
  File "/home/testuser/Fooocus-new/webui.py", line 1, in <module>
    import gradio as gr
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/utils.py", line 353, in <module>
    class AsyncRequest:
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
AttributeError: module 'httpx' has no attribute 'AsyncClient'
```

### Steps to reproduce the problem

1. Run `entry_with_update.py`

### What should have happened?

Fooocus should have launched and automatically opened a tab in my browser.

### What browsers do you use to access Fooocus?

Mozilla Firefox, Other

### Where are you running Fooocus?

Locally

### What operating system are you using?

Fedora Linux

### Console logs

```Shell
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.10.14 (main, Jun  3 2024, 17:19:22) [GCC 14.1.1 20240522 (Red Hat 14.1.1-4)]
Fooocus version: 2.5.0
Error checking version for einops: expected string or bytes-like object
Installing requirements
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/home/testuser/Fooocus-new/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/testuser/Fooocus-new/launch.py", line 147, in <module>
    from webui import *
  File "/home/testuser/Fooocus-new/webui.py", line 1, in <module>
    import gradio as gr
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio import utils
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/utils.py", line 353, in <module>
    class AsyncRequest:
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/utils.py", line 372, in AsyncRequest
    client = httpx.AsyncClient()
AttributeError: module 'httpx' has no attribute 'AsyncClient'
```

### Additional information

I was trying unsuccessfully to use Pony Diffusion and the realistic preset inside Fooocus, as it turns out only the default model works (it takes forever and gets stuck on the last sampling step). Maybe that changed some configuration?

**Comment by mashb1t** [comment]
httpx should have the attribute AsyncClient. Please uninstall and reinstall httpx to ensure it's been installed correctly.

**Comment by mikwee** [comment]
I did so, and then I had to reinstall `httpcore`, `transformers` and `tokenizers` after getting similar errors. And now I'm getting an error I cannot figure out by myself:
```
Traceback (most recent call last):
  File "/home/testuser/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/testuser/Fooocus/launch.py", line 147, in <module>
    from webui import *
  File "/home/testuser/Fooocus/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/home/testuser/Fooocus/modules/async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "/home/testuser/Fooocus/extras/inpaint_mask.py", line 6, in <module>
    from extras.GroundingDINO.util.inference import default_groundingdino
  File "/home/testuser/Fooocus/extras/GroundingDINO/util/inference.py", line 11, in <module>
    from groundingdino.util.inference import Model
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/groundingdino/util/inference.py", line 8, in <module>
    from torchvision.ops import box_convert
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torchvision/ops/_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torch/onnx/__init__.py", line 46, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py", line 44, in <module>
    from torch.onnx._internal.fx import (
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torch/onnx/_internal/fx/__init__.py", line 1, in <module>
    from .patcher import ONNXTorchPatcher
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/torch/onnx/_internal/fx/patcher.py", line 11, in <module>
    import transformers  # type: ignore[import]
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 54, in <module>
    if not is_accelerate_available():
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 857, in is_accelerate_available
    return _accelerate_available and version.parse(_accelerate_version) >= version.parse(min_version)
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/testuser/.pyenv/versions/3.10.14/lib/python3.10/site-packages/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by mashb1t** [comment]
Very strange, seems like your pyenv is messed up... I'd assume that when cleaning and starting from a fresh pyenv / venv it would work, at least i could start everything without issues and it looks like a problem of your setup, not for everybody. Please report back if starting fresh worked!

**Comment by mikwee** [comment]
Sorry for the delay, had an issue with Linux but it's fixed now.

Reinstalling 3.10 from pyenv, and then reinstalling the requirements, fixed the issue.
