### ISSUE TITLE
Getting error "exceptions must derive from BaseException" - I am doing something wrong?[Bug]: 

### ISSUE THREAD

**Issue by Yogesh-DevHub** [lllyasviel/Fooocus#3326]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I am trying the enhance feature, as per the example Fooocus 2.5.0: Enhance https://github.com/lllyasviel/Fooocus/discussions/3281

Original (generated) - Upscale (before) - https://github.com/lllyasviel/Fooocus/discussions/1 Yellow Sundress
enabling debug mode shows mask for the t-shirt was done while in-painting there is an error
in-paint method below 'Detection' modify selected rest is default  
[EDITED]: it's working now, by mistake I checked "Debug Inpaint Preprocessing" instead of "Debug Enhance Masks"

### Steps to reproduce the problem

![Screenshot 2024-07-21 024843](https://github.com/user-attachments/assets/e47c28ee-83be-4f1a-8e3b-1d0c35536621)

### What should have happened?

Am I doing something wrong?

### Where are you running Fooocus?

None

### Console logs

```Shell
[Prompt Expansion] Orange t-shirt, vivid colors, aesthetic, mythical, magical, enchanted, magic, pretty, attractive, illustrious, noble, dramatic illumination, divine, stunning, highly detailed, cinematic, light, saturated, deep color, illuminated, very intricate, enhanced, complex, elite, theatrical, depicted, sharp background, extremely fine quality, awarded, professional, artistic, surreal
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding negative #1 ...
Upscaling image with shape (579, 619, 3) ...
Traceback (most recent call last):
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 1452, in worker
    handler(task)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 1394, in handler
    current_progress, img, enhance_prompt_processed, enhance_negative_prompt_processed = process_enhance(
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 1012, in process_enhance
    denoising_strength, initial_latent, width, height, current_progress = apply_inpaint(
  File "D:\Fooocus_win64_2-1-831\Fooocus\modules\async_worker.py", line 494, in apply_inpaint
    raise EarlyReturnException
TypeError: exceptions must derive from BaseException
Total time: 18.74 seconds
```

**Comment by Yogesh-DevHub** [comment]
it's working now, by mistake I checked "Debug Inpaint Preprocessing" instead of "Debug Enhance Masks"
