### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by gerroon** [lllyasviel/Fooocus#3344]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I started Fooocus, it updated itself, now  it has this issue.

These steps did not solve it

`python_embeded\python.exe -m pip install -r Fooocus\requirements_versions.txt`

`python_embeded\python.exe -m pip install importlib_metadata`

### Steps to reproduce the problem

run Foocus?

### What should have happened?

It should have started properly

### Where are you running Fooocus?

None

### Console logs

```Shell
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --enable-auto-describe-image --listen --disable-in-browser
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--enable-auto-describe-image', '--listen', '--disable-in-browser']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.5.0
Version mismatch for pyyaml: Installed version 6.0 does not meet requirement pyyaml==6.0.1
Installing requirements
[Cleanup] Attempting to delete content of temp dir C:\Users\USER\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Total VRAM 12288 MB, total RAM 65328 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : native
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "C:\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Fooocus\Fooocus\launch.py", line 147, in <module>
    from webui import *
  File "C:\Fooocus\Fooocus\webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "C:\Fooocus\Fooocus\modules\async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "C:\Fooocus\Fooocus\extras\inpaint_mask.py", line 6, in <module>
    from extras.GroundingDINO.util.inference import default_groundingdino
  File "C:\Fooocus\Fooocus\extras\GroundingDINO\util\inference.py", line 11, in <module>
    from groundingdino.util.inference import Model
  File "C:\Fooocus\python_embeded\lib\site-packages\groundingdino\util\inference.py", line 11, in <module>
    from groundingdino.models import build_model
  File "C:\Fooocus\python_embeded\lib\site-packages\groundingdino\models\__init__.py", line 8, in <module>
    from .GroundingDINO import build_groundingdino
  File "C:\Fooocus\python_embeded\lib\site-packages\groundingdino\models\GroundingDINO\__init__.py", line 15, in <module>
    from .groundingdino import build_groundingdino
  File "C:\Fooocus\python_embeded\lib\site-packages\groundingdino\models\GroundingDINO\groundingdino.py", line 36, in <module>
    from groundingdino.util.utils import get_phrases_from_posmap
  File "C:\Fooocus\python_embeded\lib\site-packages\groundingdino\util\utils.py", line 12, in <module>
    from groundingdino.util.slconfig import SLConfig
  File "C:\Fooocus\python_embeded\lib\site-packages\groundingdino\util\slconfig.py", line 14, in <module>
    from yapf.yapflib.yapf_api import FormatCode
  File "C:\Fooocus\python_embeded\lib\site-packages\yapf\__init__.py", line 36, in <module>
    from importlib_metadata import metadata
ModuleNotFoundError: No module named 'importlib_metadata'

```
```


### Additional information

_No response_

**Comment by qiap** [comment]
hi Brother, I just encountered a similar problem, using the author's method did not solve the problem, I just re-downloaded the latest installation package, deleted the original installation package, and reinstall it, I suggest you do the same

**Comment by gerroon** [comment]
> hi Brother, I just encountered a similar problem, using the author's method did not solve the problem, I just re-downloaded the latest installation package, deleted the original installation package, and reinstall it, I suggest you do the same

Thanks but getting another error


```
Traceback (most recent call last):
  File "C:\Fooocus\python_embeded\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1222, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Fooocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1209, in validate_inputs
    raise ValueError(
ValueError: An event handler didn't receive enough input values (needed: 1, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [colorpicker]
Received inputs:
    []

```

**Comment by mashb1t** [comment]
@gerroon make sure you did not delete the colorpicker or did not modify the arguments for it when doing code adjustments in the webui.py.

**Comment by gerroon** [comment]
> @gerroon make sure you did not delete the colorpicker or did not modify the arguments for it when doing code adjustments in the webui.py.

Thanks for the reply, but I did not modify anything myself.
