### ISSUE TITLE
Should  comfy be part of requirements?

### ISSUE THREAD

**Issue by AlexNolasco** [lllyasviel/Fooocus#339]
Should  comfy.cli_args be part of requirements or is it assuming global availability?

https://github.com/lllyasviel/Fooocus/blame/25fed6a4fe0e981258cd1615a124a1bac6110899/launch.py#L92

```
❯ python launch.py
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
Fooocus version: 1.0.67
Inference Engine exists.
Inference Engine checkout finished.
Traceback (most recent call last):
  File "/home/alex/Fooocus/launch.py", line 102, in <module>
    clear_comfy_args()
  File "/home/alex/Fooocus/launch.py", line 92, in clear_comfy_args
    import comfy.cli_args
ModuleNotFoundError: No module named 'comfy.cli_arg
```

**Comment by AlexNolasco** [comment]
Closing, reinstalled, now works.
