### ISSUE TITLE
ConnectionResetError: [WinError 10054],Unable to access fooocus, the browser does not pop up,

### ISSUE THREAD

**Issue by tit96** [lllyasviel/Fooocus#349]
E:\AI\Fooocus_win64_1-1-1035>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Update failed.
failed to send request: 操作超时

Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.0.0
Inference Engine exists.
Git clone failed for Inference Engine: failed to send request: 操作超时

Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to E:\AI\Fooocus_win64_1-1-1035\Fooocus\models\prompt_expansion\fooocus_expansion\pytorch_model.bin

Traceback (most recent call last):
  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1454, in connect
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\Fooocus_win64_1-1-1035\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "E:\AI\Fooocus_win64_1-1-1035\Fooocus\launch.py", line 105, in <module>
    download_models()
  File "E:\AI\Fooocus_win64_1-1-1035\Fooocus\launch.py", line 80, in download_models
    load_file_from_url(
  File "E:\AI\Fooocus_win64_1-1-1035\Fooocus\modules\model_loader.py", line 24, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "E:\AI\Fooocus_win64_1-1-1035\python_embeded\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

E:\AI\Fooocus_win64_1-1-1035>pause
请按任意键继续. . .

**Comment by mashb1t** [comment]
> Network problem, hang up the model under vpn

^ this, please check https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md#ssl-certificate_verify_failed again. This is most likely if not 100% a network issue on your side.
