### ISSUE TITLE
[Bug]: RuntimeError: unable to mmap ... Cannot allocate memory

### ISSUE THREAD

**Issue by eravion** [lllyasviel/Fooocus#3522]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

cannot load model in GPU memory.

du -sh fooocus-data/models/checkpoints/*
6.7G	fooocus-data/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors

### Steps to reproduce the problem

Default command to start the docker:
docker run -p 7865:7865 -v ./fooocus-data:/content/data -it --gpus all -e CMDARGS=--listen -e DATADIR=/content/data -e config_path=/content/data/config.txt -e config_example_path=/content/data/config_modification_tutorial.txt -e path_checkpoints=/content/data/models/checkpoints/ -e path_loras=/content/data/models/loras/ -e path_embeddings=/content/data/models/embeddings/ -e path_vae_approx=/content/data/models/vae_approx/ -e path_upscale_models=/content/data/models/upscale_models/ -e path_inpaint=/content/data/models/inpaint/ -e path_controlnet=/content/data/models/controlnet/ -e path_clip_vision=/content/data/models/clip_vision/ -e path_fooocus_expansion=/content/data/models/prompt_expansion/fooocus_expansion/ -e path_outputs=/content/app/outputs/ ghcr.io/lllyasviel/fooocus

### What should have happened?

Access to the webui is ok, but the model is not loaded.

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally with virtualization (e.g. Docker)

### What operating system are you using?

Ubuntu 18.04.6 LTS

### Console logs

```Shell
[System ARGV] ['launch.py', '--listen']
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Fooocus version: 2.5.5
Environment: config_path = /content/data/config.txt
Environment: config_example_path = /content/data/config_modification_tutorial.txt
Environment: path_checkpoints = /content/data/models/checkpoints/
Environment: path_loras = /content/data/models/loras/
Environment: path_embeddings = /content/data/models/embeddings/
Environment: path_vae_approx = /content/data/models/vae_approx/
Environment: path_upscale_models = /content/data/models/upscale_models/
Environment: path_inpaint = /content/data/models/inpaint/
Environment: path_controlnet = /content/data/models/controlnet/
Environment: path_clip_vision = /content/data/models/clip_vision/
Environment: path_fooocus_expansion = /content/data/models/prompt_expansion/fooocus_expansion/
Environment: path_outputs = /content/app/outputs/
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /content/data/models/vae_approx/xlvaeapp.pth

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 209k/209k [00:00<00:00, 6.69MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/vaeapp_sd15.pt" to /content/data/models/vae_approx/vaeapp_sd15.pth

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 209k/209k [00:00<00:00, 5.87MB/s]
Downloading: "https://huggingface.co/mashb1t/misc/resolve/main/xl-to-v1_interposer-v4.0.safetensors" to /content/data/models/vae_approx/xl-to-v1_interposer-v4.0.safetensors

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.40M/5.40M [00:00<00:00, 41.5MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to /content/data/models/prompt_expansion/fooocus_expansion/pytorch_model.bin

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:03<00:00, 106MB/s]
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to /content/data/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.62G/6.62G [01:05<00:00, 109MB/s]
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors" to /content/data/models/loras/sd_xl_offset_example-lora_1.0.safetensors

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 47.3M/47.3M [00:00<00:00, 95.2MB/s]
Total VRAM 12014 MB, total RAM 7922 MB
xformers version: 0.0.23
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using xformers cross attention
Refiner unloaded.
Exception in thread Thread-4 (worker):
Traceback (most recent call last):
  File "/content/app/modules/patch.py", line 465, in loader
    result = original_loader(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 311, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
RuntimeError: unable to mmap 7105348592 bytes from file </content/data/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors>: Cannot allocate memory (12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[System ARGV] ['launch.py', '--listen']
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
Fooocus version: 2.5.5
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/app/modules/async_worker.py", line 181, in worker
    import modules.default_pipeline as pipeline
  File "/content/app/modules/default_pipeline.py", line 270, in <module>
    refresh_everything(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/app/modules/default_pipeline.py", line 250, in refresh_everything
    refresh_base_model(base_model_name, vae_name)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/app/modules/default_pipeline.py", line 74, in refresh_base_model
    model_base = core.load_model(filename, vae_filename)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/app/modules/core.py", line 147, in load_model
    unet, clip, vae, vae_filename, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=path_embeddings,
  File "/content/app/ldm_patched/modules/sd.py", line 431, in load_checkpoint_guess_config
    sd = ldm_patched.modules.utils.load_torch_file(ckpt_path)
  File "/content/app/ldm_patched/modules/utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/content/app/modules/patch.py", line 481, in loader
    raise ValueError(exp)
ValueError: unable to mmap 7105348592 bytes from file </content/data/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors>: Cannot allocate memory (12)
File corrupted: /content/data/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors 
Fooocus has tried to move the corrupted file to /content/data/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors.corrupted 
You may try again now and Fooocus will download models again. 

[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to /content/data/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.62G/6.62G [01:06<00:00, 107MB/s]
Running on local URL:  http://0.0.0.0:7865

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 3.41.2, however version 4.29.0 is available, please upgrade.
--------
```

### Additional information

Graphical Card : NVIDIA GeForce RTX 2060 12Go
NVIDIA-SMI 550.107.02             
Driver Version: 550.107.02     
CUDA Version: 12.4

CPU : i3-3240 CPU @ 3.40GHz 4 cores
RAM : 8Go

**Comment by eravion** [comment]
find the solution, I have to add swap despite the fact that I have 8Go of RAM
Following this article, I added 5Go of swap and now it is ok:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04

My first cat
![image](https://github.com/user-attachments/assets/bb655af1-38c3-4d82-8500-3f9da237e834)
