### ISSUE TITLE
Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver fro

### ISSUE THREAD

**Issue by eduardooS1lva** [lllyasviel/Fooocus#3671]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

![image](https://github.com/user-attachments/assets/ec057c9b-9b6d-4c86-801c-e04e5ed2901a
![Captura de tela 2024-10-10 225002](https://github.com/user-attachments/assets/95f3038d-79ab-4911-9d42-de9b3a81c746)

### Steps to reproduce the problem

![image](https://github.com/user-attachments/assets/988f482b-e413-4972-a083-f6cecb0672a0)

### What should have happened?

inicializado o FOOCUS  

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Locally

### Console logs

```Shell
C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset realistic
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'realistic']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.5.5
Loaded preset: C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\presets\realistic.json
[Cleanup] Attempting to delete content of temp dir C:\Users\T-GAMER\AppData\Local\Temp\fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\launch.py", line 152, in <module>
    from webui import *
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\modules\async_worker.py", line 3, in <module>
    from extras.inpaint_mask import generate_mask_from_image, SAMOptions
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\extras\inpaint_mask.py", line 6, in <module>
    from extras.GroundingDINO.util.inference import default_groundingdino
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\extras\GroundingDINO\util\inference.py", line 3, in <module>
    import ldm_patched.modules.model_management as model_management
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\ldm_patched\modules\model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\Fooocus\ldm_patched\modules\model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

C:\Users\T-GAMER\Desktop\FOOCUS\Fooocus_win64_2-5-0>pause
Pressione qualquer tecla para continuar. . .
```

### Additional information

Recebo esta mensagem de erro e, na verdade, não tenho uma placa de vídeo Nvidia, mas sim uma AMD. Como ela não funciona bem com IA, uso o processador. Existe alguma maneira de usar esta extensão com a CPU?

**Comment by mashb1t** [comment]
see readme
