### ISSUE TITLE
anisotropic.py TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Duanexiao** [lllyasviel/Fooocus#369]
commit f2c545803cd861d29505b053e2ea77d44e703736
python version 3.8.10

python lanuch.py error

Device: cuda:0 NVIDIA Graphics Device : native
Using xformers cross attention
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Fooocus/modules/async_worker.py", line 16, in worker
    import modules.default_pipeline as pipeline
  File "/opt/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/opt/Fooocus/modules/core.py", line 14, in <module>
    from modules.patch import patch_all
  File "/opt/Fooocus/modules/patch.py", line 7, in <module>
    import modules.anisotropic as anisotropic
  File "/opt/Fooocus/modules/anisotropic.py", line 10, in <module>
    def _compute_zero_padding(kernel_size: tuple[int, int] | int) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable

**Comment by konieshadow** [comment]
I got this error too. It's bean fixed after I upgrade python version to 3.10.13 using `conda env create -f environment.yaml`.

**Comment by Duanexiao** [comment]
> I got this error too. It's bean fixed after I upgrade python version to 3.10.13 using `conda env create -f environment.yaml`.

Thank you for your reply
