### ISSUE TITLE
[Bug]: No longer works in colab

### ISSUE THREAD

**Issue by ServerDeveloper9447** [lllyasviel/Fooocus#3710]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Installing and running fooocus as intended on colab.
The script `python entry_with_update.py --share --always-high-vram` fails with `Terminated without an active exception`.

### Steps to reproduce the problem

1. Clone fooocus
2. Run entry_with_update.py

### What should have happened?

It should've provided a gradio url as output

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### What operating system are you using?

Windows 10

### Console logs

```Shell
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Fooocus version: 2.5.5
Error checking version for torchsde: No package metadata was found for torchsde
Installing requirements
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xlvaeapp.pth" to /content/Fooocus/models/vae_approx/xlvaeapp.pth

100% 209k/209k [00:00<00:00, 10.8MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/vaeapp_sd15.pt" to /content/Fooocus/models/vae_approx/vaeapp_sd15.pth

100% 209k/209k [00:00<00:00, 8.93MB/s]
Downloading: "https://huggingface.co/mashb1t/misc/resolve/main/xl-to-v1_interposer-v4.0.safetensors" to /content/Fooocus/models/vae_approx/xl-to-v1_interposer-v4.0.safetensors

100% 5.40M/5.40M [00:00<00:00, 44.9MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to /content/Fooocus/models/prompt_expansion/fooocus_expansion/pytorch_model.bin

100% 335M/335M [00:01<00:00, 229MB/s]
Downloading: "https://huggingface.co/lllyasviel/fav_models/resolve/main/fav/juggernautXL_v8Rundiffusion.safetensors" to /content/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors

100% 6.62G/6.62G [00:34<00:00, 207MB/s]
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors" to /content/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors

100% 47.3M/47.3M [00:00<00:00, 197MB/s]
Total VRAM 15102 MB, total RAM 12979 MB
Set vram state to: HIGH_VRAM
Always offload VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

Traceback (most recent call last):
  File "/content/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/Fooocus/launch.py", line 152, in <module>
    from webui import *
  File "/content/Fooocus/webui.py", line 153, in <module>
    shared.gradio_root = gr.Blocks(title=title).queue()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 867, in wrapper
    return queue(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1685, in queue
    self.app = routes.App.create_app(self)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 221, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 994, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 933, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 554, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 284, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 118, in get_param_sub_dependant
    return get_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 154, in get_sub_dependant
    sub_dependant = get_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 277, in get_dependant
    param_details = analyze_param(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 474, in analyze_param
    ensure_multipart_is_installed()
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 107, in ensure_multipart_is_installed
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

IMPORTANT: You are using gradio version 3.41.2, however version 4.44.1 is available, please upgrade.
--------
terminate called without an active exception
```

**Comment by ServerDeveloper9447** [comment]
Installing python-multipart==0.0.12 seem to have fixed the issue
