### ISSUE TITLE
[Bug]: RuntimeError: Form data requires "python-multipart" to be installed. On colab 

### ISSUE THREAD

**Issue by Atreussstz** [lllyasviel/Fooocus#3712]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with:
![20241027_185028](https://github.com/user-attachments/assets/3d6cd4f6-14eb-4d44-b10f-81d40218f574)

### Steps to reproduce the problem

Get fixed

### What should have happened?

Fooocus must be fixed immediately

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (Google Colab)

### Console logs

```Shell
Requirement already satisfied: pygit2==1.15.1 in /usr/local/lib/python3.10/dist-packages (1.15.1)
Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from pygit2==1.15.1) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.16.0->pygit2==1.15.1) (2.22)
/content
fatal: destination path 'Fooocus' already exists and is not an empty directory.
/content/Fooocus
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Fooocus version: 2.5.5
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 15102 MB, total RAM 12979 MB
Set vram state to: HIGH_VRAM
Always offload VRAM
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

Traceback (most recent call last):
  File "/content/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/Fooocus/launch.py", line 152, in <module>
    from webui import *
  File "/content/Fooocus/webui.py", line 153, in <module>
    shared.gradio_root = gr.Blocks(title=title).queue()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 867, in wrapper
    return queue(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1685, in queue
    self.app = routes.App.create_app(self)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 221, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 994, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 933, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 554, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 284, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 118, in get_param_sub_dependant
    return get_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 154, in get_sub_dependant
    sub_dependant = get_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 277, in get_dependant
    param_details = analyze_param(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 474, in analyze_param
    ensure_multipart_is_installed()
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 107, in ensure_multipart_is_installed
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

IMPORTANT: You are using gradio version 3.41.2, however version 4.44.1 is available, please upgrade.
--------
terminate called without an active exception
Produk berbayar Colab - Batalkan kontrak di sini
```

**Comment by u3-n7-d8** [comment]
I had the same problem 2 hours ago. Now i tried again and it is working now. May be it has been fixed. Kindly try again.

**Comment by Atreussstz** [comment]
Really??

**Comment by u3-n7-d8** [comment]
Yes it is working now.

**Comment by Atreussstz** [comment]
Thx
