### ISSUE TITLE
[Bug]: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by msmithers20** [lllyasviel/Fooocus#3738]
### Checklist

- [x] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [x] The issue exists on a clean installation of Fooocus
- [x] The issue exists in the current version of Fooocus
- [x] The issue has not been reported before recently
- [x] The issue has been reported before but has not been fixed yet

### What happened?

When I try to generate an image, it begins to work, but runs into this error: 
![image](https://github.com/user-attachments/assets/58471e12-79dd-4010-9e81-94864f4afe75)

### Steps to reproduce the problem

1. Launch Fooocus
2. get to the web ui
3. enter a prompt, then it breaks

### What should have happened?

It should have generated an image

### Where are you running Fooocus?

Locally

### What operating system are you using?

Ubuntu 22 using WSL and Windows 11

### Console logs

```Shell
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py']
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
Fooocus version: 2.5.5
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Total VRAM 6144 MB, total RAM 15850 MB
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : native
VAE dtype: torch.float32
Using pytorch cross attention
Refiner unloaded.
Running on local URL:  http://127.0.0.1:7865

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 3.41.2, however version 4.44.1 is available, please upgrade.
--------
gio: http://127.0.0.1:7865/: Operation not supported
model_type EPS
UNet ADM Dimension 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Base model loaded: /home/michael/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors
VAE loaded: None
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.1)] for model [/home/michael/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [/home/michael/Fooocus/models/loras/sd_xl_offset_example-lora_1.0.safetensors] for UNet [/home/michael/Fooocus/models/checkpoints/juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
loading in lowvram mode 1084.3028841018677
lowvram: loaded module regularly Embedding(49408, 768)
lowvram: loaded module regularly Embedding(77, 768)
lowvram: loaded module regularly Embedding(49408, 1280)
lowvram: loaded module regularly Embedding(77, 1280)
[Fooocus Model Management] Moving model(s) has taken 2.79 seconds
Started worker with PID 1884
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
[Parameters] Adaptive CFG = 7
[Parameters] CLIP Skip = 2
[Parameters] Sharpness = 2
[Parameters] ControlNet Softness = 0.25
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] Seed = 907403549187238456
[Parameters] CFG = 4
[Fooocus] Loading control models ...
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] a bota on fire, passionate, magic, intricate, highly detailed, colorful, vivid, surreal, beautiful, sharp focus, epic cinematic, fine still, awesome composition, dynamic light, atmosphere, creative, lively, ambient, elegant, amazing detail, professional, perfect, best, unique, illuminated, gorgeous, stunning, flawless, pretty, confident, color, shiny
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] a bota on fire, passionate, magic, intricate, detailed, dramatic light, sharp focus, fair, extremely fine detail, striking, cinematic, highly quality, elegant, elaborate, complex, epic, artistic, rich surreal background, pristine, iconic, imposing, incredible composition, perfect symmetry, clear, aesthetic, great spiritual, gorgeous scenic, marvelous, atmosphere, thought
[Fooocus] Encoding positive #1 ...
[Fooocus Model Management] Moving model(s) has taken 0.15 seconds
Traceback (most recent call last):
  File "/home/michael/Fooocus/modules/async_worker.py", line 1471, in worker
    handler(task)
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/modules/async_worker.py", line 1160, in handler
    tasks, use_expansion, loras, current_progress = process_prompt(async_task, async_task.prompt, async_task.negative_prompt,
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/modules/async_worker.py", line 746, in process_prompt
    t['c'] = pipeline.clip_encode(texts=t['positive'], pool_top_k=t['positive_top_k'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/modules/default_pipeline.py", line 196, in clip_encode
    cond, pooled = clip_encode_single(final_clip, text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/modules/default_pipeline.py", line 154, in clip_encode_single
    result = clip.encode_from_tokens(tokens, return_pooled=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/ldm_patched/modules/sd.py", line 128, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/ldm_patched/modules/sdxl_clip.py", line 54, in encode_token_weights
    g_out, g_pooled = self.clip_g.encode_token_weights(token_weight_pairs_g)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/modules/patch_clip.py", line 39, in patched_encode_token_weights
    out, pooled = self.encode(to_encode)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/ldm_patched/modules/sd1_clip.py", line 190, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/modules/patch_clip.py", line 125, in patched_SDClipModel_forward
    outputs = self.transformer(input_ids=tokens, attention_mask=attention_mask,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 806, in forward
    return self.text_model(
           ^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 698, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 220, in forward
    position_embeddings = self.position_embedding(position_ids)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/home/michael/Fooocus/fooocus_env/lib/python3.12/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
Total time: 2.96 seconds
```

**Comment by msmithers20** [comment]
Solved: 
![image](https://github.com/user-attachments/assets/b3a6f402-0d0a-46f1-b477-95dcb61238a4)
