### ISSUE TITLE
Exception in thread-2 (worker):  Error while deserializing header

### ISSUE THREAD

**Issue by kdx7214** [lllyasviel/Fooocus#426]
Just downloaded this to try it out.  Download seemed to work fine (showed 100% completion) and it launches the web page just fine.  When I go to generate the prompt "photo of a cute puppy" it just sits there stuck on initializing.  I've let it sit for 2 hours with no change.  When I check task manager there is 0% usage on GPU and around 2% on CPU.  VRAM doesn't show any increase in usage either.  GPU is NVidia RTX-2080 with 8GB VRAM.   Below is the console output from python:

C:\Users\BlackBart\Desktop\Stable Diffusion>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.0.62
Inference Engine exists.
Inference Engine checkout finished.
Detected GPU Type: NVIDIA GPU
Total VRAM 8192 MB, total RAM 32660 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 : native
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[Virtual Memory System] Logic target is CPU, memory = 32659.71875
[Virtual Memory System] Activated = False
Fooocus Text Processing Pipelines are retargeted to cuda:0
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\models\checkpoints\sd_xl_refiner_1.0_0.9vae.safetensors
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\modules\async_worker.py", line 17, in worker
    import modules.default_pipeline as pipeline
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\modules\default_pipeline.py", line 188, in <module>
    refresh_everything(
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\modules\default_pipeline.py", line 180, in refresh_everything
    refresh_base_model(base_model_name)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\modules\default_pipeline.py", line 37, in refresh_base_model
    xl_base = core.load_model(filename)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\modules\core.py", line 53, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sd.py", line 1177, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\Fooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\utils.py", line 11, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "C:\Users\BlackBart\Desktop\Stable Diffusion\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by acheronex** [comment]
I have the same problem! RTX 2060 super - 8 Gb, Nvidia driver 531.18

**Comment by krusty-7** [comment]
Having a similar issue here, I will redownload the model
thank you @acheronex

**Comment by mashb1t** [comment]
Doing cleanup, sorry for the late answer.
Please test again with the latest version of Fooocus and let us know the results. THis should lot occur anymore.
