### ISSUE TITLE
Error encountered when using image expansion.

### ISSUE THREAD

**Issue by pengpengzi** [lllyasviel/Fooocus#451]
[Fooocus] Image processing ...
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/home/anaconda3/envs/py310_fooocus/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/anaconda3/envs/py310_fooocus/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ai/Fooocus_dev/modules/async_worker.py", line 394, in worker
    handler(task)
  File "/home/anaconda3/envs/py310_fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/py310_fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ai/Fooocus_dev/modules/async_worker.py", line 198, in handler
    inpaint_worker.current_task = inpaint_worker.InpaintWorker(image=inpaint_image, mask=inpaint_mask,
  File "/home/ai/Fooocus_dev/modules/inpaint_worker.py", line 152, in __init__
    a, b, c, d = compute_initial_abcd(self.mask_raw_bg < 127)
  File "/home/ai/Fooocus_dev/modules/inpaint_worker.py", line 85, in compute_initial_abcd
    a = np.min(indices[0]) - 64
  File "<__array_function__ internals>", line 180, in amin
  File "/home/anaconda3/envs/py310_fooocus/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2918, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/anaconda3/envs/py310_fooocus/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

When I drag the generated image into the local redrawing box, there is no mask. After clicking on the upward expansion, an error occurs during the generation process. here is my error

**Comment by lllyasviel** [comment]
try update to 2.0.73 and if have problems, give full console log and screenshot

**Comment by lllyasviel** [comment]
closed as user does not respond
