### ISSUE TITLE
Takes forever to load or doesn't load at all, unable to generate

### ISSUE THREAD

**Issue by Leyntur** [lllyasviel/Fooocus#477]
Weird issue, I got Fooocus to work once on a SSD and generated some images relatively fast with no issues, then I've tried to run it from multiple HDDs and it hasn't worked ever since, nor even going back to the SSD. Note that I've been running Auto1111 without any issues.
I've tried downgrading the Nvidia driver and reinstalling python with this parameter "python -m pip install --upgrade --force-reinstall --no-cache-dir --no-deps torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"
Problem is, it takes ages to load (the refiner? Even when it's not being used) and then the process just stops there, in some other tries, it actually managed to load after around 40 minutes, but I usually don't have the patience for that

"F:\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.0.78
Inference Engine exists.
Inference Engine checkout finished.
Total VRAM 8192 MB, total RAM 16244 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 SUPER : native
Using xformers cross attention
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Fooocus Text Processing Pipelines are retargeted to cuda:0
[Virtual Memory System] Logic target is CPU, memory = 16244.33203125
[Virtual Memory System] Activated = True
model_type EPS
adm 2560
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: F:\Fooocus\Fooocus\models\checkpoints\sd_xl_refiner_1.0_0.9vae.safetensors
[Virtual Memory System] time = 22.57197s: model released from cpu: F:\Fooocus\Fooocus\models\checkpoints\sd_xl_refiner_1.0_0.9vae.safetensors
[Virtual Memory System] time = 0.44301s: refiner_clip released from cpu: F:\Fooocus\Fooocus\models\checkpoints\sd_xl_refiner_1.0_0.9vae.safetensors
model_type EPS
adm 2816"

and then there are no further actions, but sometimes, if I click generate again, it shows this, and then gets stuck once again:

"making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Base model loaded: F:\Fooocus\Fooocus\models\checkpoints\sd_xl_base_1.0_0.9vae.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
Fooocus Expansion engine loaded for cuda:0.
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
[Fooocus] Initializing ...
[Fooocus] Loading models ...
model_type EPS
adm 2560"

**Comment by hben35096** [comment]
[Fooocus] Downloading inpainter ...
Downloading: "https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/inpaint.fooocus.patch" to /mnt/workspace/Fooocus/models/inpaint/inpaint.fooocus.patch

Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/conda/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/opt/conda/lib/python3.10/http/client.py", line 951, in connect
    self._tunnel()
  File "/opt/conda/lib/python3.10/http/client.py", line 920, in _tunnel
    (version, code, message) = response._read_status()
  File "/opt/conda/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/Fooocus/modules/async_worker.py", line 391, in worker
    handler(task)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workspace/Fooocus/modules/async_worker.py", line 200, in handler
    inpaint_head_model_path, inpaint_patch_model_path = modules.path.downloading_inpaint_models()
  File "/mnt/workspace/Fooocus/modules/path.py", line 84, in downloading_inpaint_models
    load_file_from_url(
  File "/mnt/workspace/Fooocus/modules/model_loader.py", line 24, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/opt/conda/lib/python3.10/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Remote end closed connection without response>


It's pretty much the same problem, the download fails, but the task cannot be stopped via the "Stop" button, and the button does not revert to "Generate".
The only way is to restart Fooocus.

**Comment by barepixels** [comment]
@hben35096 does manual download works?

https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/inpaint.fooocus.patch

and manually place in Fooocus/models/inpaint/

**Comment by hben35096** [comment]
> 手动下载有效吗？
> 
> https://huggingface.co/lllyasviel/fooocus_inpaint/resolve/main/inpaint.fooocus.patch
> 
> 并手动放置在 Fooocus/模型/inpaint/

Manual download is valid, but in this case of load failure, shouldn't there be a setting to automatically end the task after more time?

**Comment by barepixels** [comment]
I had a similar problem couple days ago.  I went to do inpaint and forgot that I had set it to batch 10.  I tried to stop it but couldn't and I caused a crash.  Had to restart CMD

**Comment by mashb1t** [comment]
closing as stale, feel free to reopen when providing new information
