### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by FirminSun** [lllyasviel/Fooocus#496]
```bash
Fooocus] Encoding refiner negative #2 ...
[ADM] Negative ADM = True
  0%|                                                                                                                                           | 0/30 [00:00<?, ?it/s]
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/work/Fooocus/modules/async_worker.py", line 391, in worker
    handler(task)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/work/Fooocus/modules/async_worker.py", line 341, in handler
    imgs = pipeline.process_diffusion(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/work/Fooocus/modules/default_pipeline.py", line 238, in process_diffusion
    sampled_latent = core.ksampler_with_refiner(
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/work/Fooocus/modules/core.py", line 312, in ksampler_with_refiner
    samples = sampler.sample(noise, positive_copy, negative_copy, refiner_positive=refiner_positive_copy,
  File "/work/Fooocus/modules/samplers_advanced.py", line 437, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas,
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/work/Fooocus/modules/patch.py", line 275, in sample_dpmpp_fooocus_2m_sde_inpaint_seamless
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/samplers.py", line 323, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/Fooocus/modules/patch.py", line 161, in patched_discrete_eps_ddpm_denoiser_forward
    return self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/work/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/k_diffusion/external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/work/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/samplers.py", line 311, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
  File "/work/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/samplers.py", line 289, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "/work/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/samplers.py", line 261, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model_function, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "/work/Fooocus/modules/patch.py", line 170, in patched_model_function
    return func(x, t, **c)
  File "/work/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/model_base.py", line 61, in apply_model
    return self.diffusion_model(xc, t, context=context, y=c_adm, control=control, transformer_options=transformer_options).float()
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/Fooocus/modules/patch.py", line 326, in patched_unet_forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options)
  File "/work/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 63, in forward_timestep_embed
    x = layer(x)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation
```

I installed the environment according to the documentation, and got the error when I try to generate image.

**Comment by FirminSun** [comment]
my python env:
```bash
$ conda list
# packages in environment at /opt/anaconda3/envs/fooocus:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
accelerate                0.21.0                    <pip>
aiofiles                  23.2.1                    <pip>
aiohttp                   3.8.5                     <pip>
aiosignal                 1.3.1                     <pip>
altair                    5.1.1                     <pip>
annotated-types           0.5.0                     <pip>
antlr4-python3-runtime    4.9.3                     <pip>
anyio                     3.7.1                     <pip>
async-timeout             4.0.3                     <pip>
attrs                     23.1.0                    <pip>
boltons                   23.0.0                    <pip>
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2023.7.22                 <pip>
cffi                      1.15.1                    <pip>
charset-normalizer        3.2.0                     <pip>
click                     8.1.7                     <pip>
cmake                     3.27.5                    <pip>
contourpy                 1.1.1                     <pip>
cycler                    0.11.0                    <pip>
einops                    0.4.1                     <pip>
exceptiongroup            1.1.3                     <pip>
fastapi                   0.103.1                   <pip>
ffmpy                     0.3.1                     <pip>
filelock                  3.12.4                    <pip>
fonttools                 4.42.1                    <pip>
frozenlist                1.4.0                     <pip>
fsspec                    2023.9.2                  <pip>
gradio                    3.39.0                    <pip>
gradio_client             0.5.1                     <pip>
h11                       0.14.0                    <pip>
httpcore                  0.18.0                    <pip>
httpx                     0.25.0                    <pip>
huggingface-hub           0.17.2                    <pip>
idna                      3.4                       <pip>
Jinja2                    3.1.2                     <pip>
jsonschema                4.19.1                    <pip>
jsonschema-specifications 2023.7.1                  <pip>
kiwisolver                1.4.5                     <pip>
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h295c915_4  
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.41.5               h5eee18b_0  
lightning-utilities       0.9.0                     <pip>
linkify-it-py             2.0.2                     <pip>
lit                       17.0.1                    <pip>
llvm-openmp               14.0.6               h9e868ea_0  
markdown-it-py            2.2.0                     <pip>
MarkupSafe                2.1.3                     <pip>
matplotlib                3.8.0                     <pip>
mdit-py-plugins           0.3.3                     <pip>
mdurl                     0.1.2                     <pip>
mpmath                    1.3.0                     <pip>
multidict                 6.0.4                     <pip>
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                       <pip>
numpy                     1.23.5                    <pip>
omegaconf                 2.2.3                     <pip>
openssl                   3.0.11               h7f8727e_2  
orjson                    3.9.7                     <pip>
packaging                 23.1            py310h06a4308_0  
packaging                 23.1                      <pip>
pandas                    2.1.1                     <pip>
Pillow                    9.2.0                     <pip>
pip                       23.0.1                    <pip>
pip                       23.0.1          py310h06a4308_0  
psutil                    5.9.5                     <pip>
pycparser                 2.21                      <pip>
pydantic                  2.4.0                     <pip>
pydantic_core             2.10.0                    <pip>
pydub                     0.25.1                    <pip>
pygit2                    1.12.2                    <pip>
pyparsing                 3.1.1                     <pip>
python                    3.10.13              h955ad1f_0  
python-dateutil           2.8.2                     <pip>
python-multipart          0.0.6                     <pip>
pytorch-lightning         1.9.4                     <pip>
pytz                      2023.3.post1              <pip>
PyYAML                    6.0                       <pip>
readline                  8.2                  h5eee18b_0  
referencing               0.30.2                    <pip>
regex                     2023.8.8                  <pip>
requests                  2.31.0                    <pip>
rpds-py                   0.10.3                    <pip>
safetensors               0.3.1                     <pip>
scipy                     1.9.3                     <pip>
semantic-version          2.10.0                    <pip>
setuptools                68.0.0                    <pip>
setuptools                68.0.0          py310h06a4308_0  
six                       1.16.0                    <pip>
sniffio                   1.3.0                     <pip>
sqlite                    3.41.2               h5eee18b_0  
starlette                 0.27.0                    <pip>
sympy                     1.12                      <pip>
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                    <pip>
toolz                     0.12.0                    <pip>
torch                     2.0.1+cu118               <pip>
torchmetrics              1.2.0                     <pip>
torchsde                  0.2.5                     <pip>
torchvision               0.15.2+cu118              <pip>
tqdm                      4.64.1                    <pip>
trampoline                0.1.2                     <pip>
transformers              4.30.2                    <pip>
triton                    2.0.0                     <pip>
typing_extensions         4.8.0                     <pip>
tzdata                    2023c                h04d1e81_0  
tzdata                    2023.3                    <pip>
uc-micro-py               1.0.2                     <pip>
urllib3                   2.0.5                     <pip>
uvicorn                   0.23.2                    <pip>
websockets                11.0.3                    <pip>
wheel                     0.38.4                    <pip>
wheel                     0.38.4          py310h06a4308_0  
xformers                  0.0.20                    <pip>
xz                        5.4.2                h5eee18b_0  
yarl                      1.9.2                     <pip>
zlib                      1.2.13               h5eee18b_0  
```

**Comment by FirminSun** [comment]
it is working fine after reinstall env。
