### ISSUE TITLE
I had an error related to ComfyUI

### ISSUE THREAD

**Issue by ikmalsaid** [lllyasviel/Fooocus#504]
Hey, @lllyasviel! Is there any chance you encounter this error before:

`Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Personal\Downloads\Fooocus\Fooocus\modules\async_worker.py", line 17, in worker
    import modules.default_pipeline as pipeline
  File "E:\Personal\Downloads\Fooocus\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "E:\Personal\Downloads\Fooocus\Fooocus\modules\core.py", line 3, in <module>
    patch_all()
  File "E:\Personal\Downloads\Fooocus\Fooocus\modules\patch.py", line 436, in patch_all
    comfy.sd.ModelPatcher.calculate_weight = calculate_weight_patched
AttributeError: module 'comfy.sd' has no attribute 'ModelPatcher'`

It happens during the starting phase and I can't generate anything afterwards.

**Comment by MoonRide303** [comment]
@ikmalsaid Did you use [official release](https://github.com/lllyasviel/Fooocus/releases), and made no changes in Fooocus or ComfyUI repo files? v2.0.50 (upgraded to v2.0.78 on launch) works just fine for me.

**Comment by kites262** [comment]
the same to me. But I'm also confused how to do

**Comment by mashb1t** [comment]
Please make sure you update to the latest version of Fooocus and test again. Known working for many users.
