### ISSUE TITLE
AMD GPU on linux 

### ISSUE THREAD

**Issue by Vortex1x1x1x** [lllyasviel/Fooocus#519]
How do i get this to work with my AMD GPU it says that you can use an AMD GPU and the installation is the same but whenever a try to run the program it says a need NVIDIA drivers for my GPU i have the amdgpu drivers installed so that might be the problem sorry if this is a stupid question 

This is what my terminal spits out after i run "python3 entry_with_update.py"

vortext1x1x1x@byron-pc:~/Fooocus$ python3 entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Fooocus version: 2.0.78
Inference Engine exists.
Inference Engine checkout finished.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vortext1x1x1x/Fooocus/modules/async_worker.py", line 17, in worker
    import modules.default_pipeline as pipeline
  File "/home/vortext1x1x1x/Fooocus/modules/default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "/home/vortext1x1x1x/Fooocus/modules/core.py", line 1, in <module>
    from modules.patch import patch_all
  File "/home/vortext1x1x1x/Fooocus/modules/patch.py", line 3, in <module>
    import comfy.model_base
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/model_base.py", line 2, in <module>
    from comfy.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 18, in <module>
    from ..attention import SpatialTransformer
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/ldm/modules/attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from comfy import model_management
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/model_management.py", line 104, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/model_management.py", line 74, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/vortext1x1x1x/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/vortext1x1x1x/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Traceback (most recent call last):
  File "/home/vortext1x1x1x/Fooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/home/vortext1x1x1x/Fooocus/launch.py", line 117, in <module>
    from webui import *
  File "/home/vortext1x1x1x/Fooocus/webui.py", line 12, in <module>
    import comfy.model_management as model_management
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/model_management.py", line 104, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/home/vortext1x1x1x/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/model_management.py", line 74, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/vortext1x1x1x/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/vortext1x1x1x/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by MatthewForrester** [comment]
@Vortex1x1x1x  What did you change to solve this issue, please? Use the AMDGPU-PRO driver instead of the open-source amdgpu?

**Comment by Vortex1x1x1x** [comment]
> @Vortex1x1x1x What did you change to solve this issue, please? Use the AMDGPU-PRO driver instead of the open-source amdgpu?

neither one of the drivers work i misread the read me and thought it said amd gpu where compatible on Linux but i was wrong

**Comment by Vortex1x1x1x** [comment]
Hold on i just  ran the program  and it worked
