### ISSUE TITLE
Error occurs when inpainting or outpainting on Mac

### ISSUE THREAD

**Issue by eric23** [lllyasviel/Fooocus#572]
Everything is ok except inpainting and outpainting:

[Parameters] Sampler = dpmpp_fooocus_2m_sde_inpaint_seamless - karras
[Parameters] Steps = 30 - 20
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Traceback (most recent call last):
  File "/Users/yanjun/Fooocus/modules/async_worker.py", line 552, in worker
    handler(task)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/Fooocus/modules/async_worker.py", line 226, in handler
    pipeline.refresh_everything(refiner_model_name=refiner_model_name, base_model_name=base_model_name, loras=loras)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/Fooocus/modules/default_pipeline.py", line 210, in refresh_everything
    refresh_loras(loras)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/Fooocus/modules/default_pipeline.py", line 137, in refresh_loras
    model = core.load_sd_lora(model, filename, strength_model=weight, strength_clip=weight)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/yanjun/Fooocus/modules/core.py", line 114, in load_sd_lora
    lora = comfy.utils.load_torch_file(lora_filename, safe_load=False)
  File "/Users/yanjun/Fooocus/repositories/ComfyUI-from-StabilityAI-Official/comfy/utils.py", line 22, in load_torch_file
    pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/serialization.py", line 985, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/Users/yanjun/miniconda3/envs/fooocus/lib/python3.10/site-packages/torch/serialization.py", line 439, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Zephiel13** [comment]
hello.
I have exactly the same problem on pc

**Comment by lllyasviel** [comment]
seems that "PytorchStreamReader failed" means corrupted file

**Comment by Zephiel13** [comment]
THANKS
I unzipped the installation file with 7zip (winrar before) and everything works fine now.

**Comment by eric23** [comment]
> seems that "PytorchStreamReader failed" means corrupted file

I don't know which file it means? the inpaint patch file? I can't find any zip file in the project folder...

**Comment by eric23** [comment]
> THANKS I unzipped the installation file with 7zip (winrar before) and everything works fine now.

What does installation file mean?  I have never unzipped any file before.

**Comment by Zephiel13** [comment]
for windows the install file "Fooocus_win64_2-1-14.7z" need to be unzipped
when lllyasviel tell us that it was a corrupted file problem, i downloaded the installer again and make a clean install but the issue persist, so i tried to decompress with another unzipper (7zip) and its worked.

**Comment by eric23** [comment]
> for windows the install file "Fooocus_win64_2-1-14.7z" need to be unzipped when lllyasviel tell us that it was a corrupted file problem, i downloaded the installer again and make a clean install but the issue persist, so i tried to decompress with another unzipper (7zip) and its worked.

I think it exists only in 2.1.14 and later versions, my env is 2.1.0.

**Comment by eric23** [comment]
After deleting pth file and re-download, it works. It seems the file copied from my linux server doesn't work although they have same size and hash. Tricky...
