### ISSUE TITLE
"MetadataIncompleteBuffer" Error

### ISSUE THREAD

**Issue by AKDigitalAgency** [lllyasviel/Fooocus#672]
Can someone please help solve this problem "MetadataIncompleteBuffer" ???
PS I have tried to fix it by deleting both SDXL base & Finer models BUT it didn't fix this error as suggested by Moonbeam :(
Running on CPU build torch, works on other WebUI ie Comfy, A1111, Vlad1111, Volta
Also get same error with Foocus-MRE
Please help fix this!

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Fooocus version: 2.1.58
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/vaeapp_sd15.pt" to D:\AIs\Stability Matrix\Data\Packages\Fooocus\models\vae_approx\vaeapp_sd15.pth

100%|##########| 209k/209k [00:00<00:00, 7.16MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/xl-to-v1_interposer-v3.1.safetensors" to D:\AIs\Stability Matrix\Data\Packages\Fooocus\models\vae_approx\xl-to-v1_interposer-v3.1.safetensors

100%|##########| 6.25M/6.25M [00:00<00:00, 12.1MB/s]
Downloading: "https://huggingface.co/lllyasviel/misc/resolve/main/fooocus_expansion.bin" to D:\AIs\Stability Matrix\Data\Packages\Fooocus\models\prompt_expansion\fooocus_expansion\pytorch_model.bin

100%|##########| 335M/335M [00:09<00:00, 36.8MB/s]
Running on local URL:  http://***

To create a public link, set `share=True` in `launch()`.
Total VRAM 16244 MB, total RAM 16244 MB
Forcing FP32, if this improves things please report it.
Set vram state to: DISABLED
Device: cpu
VAE dtype: torch.float32
Using split optimization for cross attention
[Fooocus Smart Memory] Disabling smart memory, vram_inadequate = True, is_old_gpu_arch = True.
model_type EPS
adm 2560
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
Refiner model loaded: D:\AIs\Stability Matrix\Data\Models\StableDiffusion\sd_xl_refiner_1.0_0.9vae.safetensors
Exception in thread Thread-3 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\modules\async_worker.py", line 18, in worker
    import modules.default_pipeline as pipeline
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\modules\default_pipeline.py", line 252, in <module>
    refresh_everything(
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\modules\default_pipeline.py", line 225, in refresh_everything
    refresh_base_model(base_model_name)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\modules\default_pipeline.py", line 94, in refresh_base_model
    xl_base = core.load_model(filename)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\modules\core.py", line 69, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\backend\headless\fcbh\sd.py", line 398, in load_checkpoint_guess_config
    sd = fcbh.utils.load_torch_file(ckpt_path)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\backend\headless\fcbh\utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\AIs\Stability Matrix\Data\Packages\Fooocus\venv\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by barepixels** [comment]
Have you tried installing Fooocus without using Stability Matrix?

**Comment by hylarucoder** [comment]
MetadataIncompleteBuffer means your model file is corrupt, can you check other models?

**Comment by i7ian** [comment]
Meet the same problem with you

**Comment by AKDigitalAgency** [comment]
I have tried many different SDXL & 1.5 models but still get same error, so I don't think it has anything to do with models you use :(

I've tested all versions of stand alone Fooocus & Fooocus-MRE & through Stable Matrix get same error in all versions :(

Reason I use Stable Matrix it lets me run Fooocus with CPU build torch, while standalone Fooocus keeps aborting due to "Torch not comaptible with Nvidia" well no kidding I don't have Nvidia card :(

**Comment by i7ian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lllyasviel** [comment]
![image](https://github.com/lllyasviel/Fooocus/assets/19834515/16ccce8d-f309-477e-a2db-8bfdc6c64646)

I added a file checking system in 2.1.677
it will automatically delete correupted files so that it will be downloaded again in the next run
