### ISSUE TITLE
 Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by i7ian** [lllyasviel/Fooocus#685]
Run "run_anime.bat" wrong, "run_realistic.bat" and "run.bat" is no problem, model "DreamShaper_8_pruned.safetensors" download are the same in many ways, what solution?

making attention of type 'vanilla-pytorch' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-pytorch' with 512 in_channels
missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
Refiner model loaded: D:\7ian\Tool\Fooocus_win64\Fooocus\models\checkpoints\DreamShaper_8_pruned.safetensors
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\7ian\Tool\Fooocus_win64\Fooocus\modules\async_worker.py", line 18, in worker
    import modules.default_pipeline as pipeline
  File "D:\7ian\Tool\Fooocus_win64\Fooocus\modules\default_pipeline.py", line 254, in <module>
    refresh_everything(
  File "D:\7ian\Tool\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\7ian\Tool\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\7ian\Tool\Fooocus_win64\Fooocus\modules\default_pipeline.py", line 227, in refresh_everything
    refresh_base_model(base_model_name)
  File "D:\7ian\Tool\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\7ian\Tool\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\7ian\Tool\Fooocus_win64\Fooocus\modules\default_pipeline.py", line 96, in refresh_base_model
    xl_base = core.load_model(filename)
  File "D:\7ian\Tool\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\7ian\Tool\Fooocus_win64\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\7ian\Tool\Fooocus_win64\Fooocus\modules\core.py", line 70, in load_model
    unet, clip, vae, clip_vision = load_checkpoint_guess_config(ckpt_filename, embedding_directory=embeddings_path)
  File "D:\7ian\Tool\Fooocus_win64\Fooocus\backend\headless\fcbh\sd.py", line 400, in load_checkpoint_guess_config
    sd = fcbh.utils.load_torch_file(ckpt_path)
  File "D:\7ian\Tool\Fooocus_win64\Fooocus\backend\headless\fcbh\utils.py", line 13, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\7ian\Tool\Fooocus_win64\python_embeded\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by lucknini** [comment]
这个259行的错误，和我的一样，我已经搞了一个星期，连硬盘都换了，搞不定，其他功能都好的，就这个不行。
