### ISSUE TITLE
Possible bug when no lora is selected

### ISSUE THREAD

**Issue by agarzon** [lllyasviel/Fooocus#789]
**Describe the problem**

When in any LoRA  field, the text is removed, the console shows an error.

![image](https://github.com/lllyasviel/Fooocus/assets/339828/dcaf275a-531e-4343-b453-6a55cb02f967)

**Full Console Log**

```
Traceback (most recent call last):
  File "D:\SD\Data\Packages\Fooocus\modules\async_worker.py", line 583, in worker
    handler(task)
  File "D:\SD\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\Data\Packages\Fooocus\modules\async_worker.py", line 223, in handler
    pipeline.refresh_everything(refiner_model_name=refiner_model_name, base_model_name=base_model_name, loras=loras)
  File "D:\SD\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\Data\Packages\Fooocus\modules\default_pipeline.py", line 233, in refresh_everything
    refresh_loras(loras)
  File "D:\SD\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\Data\Packages\Fooocus\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\Data\Packages\Fooocus\modules\default_pipeline.py", line 147, in refresh_loras
    if os.path.exists(name):
Total time: 1.16 seconds
  File "genericpath.py", line 19, in exists
```

**Comment by mashb1t** [comment]
Issue does not exist anymore in latest version of Fooocus, closing this issue.
