### ISSUE TITLE
AMD 6700XT 12GB out of memory.

### ISSUE THREAD

**Issue by uzior** [lllyasviel/Fooocus#835]
Hi!
I realize that AMD devices are still in the beta phase, but the problem I encountered seems relatively easy to solve, namely:

Everything starts correctly, the generation process starts, but when it allocates VRAM memory after exceeding 7GB, the system crashes.

Any suggestions? I will be grateful for all suggestions.
log below.

Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.771
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Using directml with device:
Total VRAM 1024 MB, total RAM 32694 MB
Set vram state to: NORMAL_VRAM
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
[Fooocus] Disabling smart memory
Refiner unloaded.
model_type EPS
adm 2816
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
Base model loaded: E:\VM\AI\Fooocus\models\checkpoints\juggernautXL_version6Rundiffusion.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.1), ('None', 0.1), ('None', 0.1), ('None', 0.1), ('None', 0.1)]
Fooocus Expansion engine loaded for cpu, use_fp16 = False.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 1
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 139978393905596030
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 24
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
Preparation time: 3.72 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.02916753850877285, sigma_max = 14.614643096923828
Requested to load SDXL
Loading 1 new model
[W D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_heap_allocator.cc:120] DML allocator out of memory!
[W D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_heap_allocator.cc:120] DML allocator out of memory!

**Comment by klementf95** [comment]
I have a similar problem on my RX 6800S, the laptop runs out of memory and crashes at every run

**Comment by PowerZones** [comment]
Same on RX580 8gb

**Comment by webredraptors** [comment]
Can confirm this issue exists on my 6700XT as well. Here's the full traceback:

`[Parameters] Adaptive CFG = 7
[Parameters] Sharpness = 2
[Parameters] ADM Scale = 1.5 : 0.8 : 0.3
[Parameters] CFG = 4.0
[Parameters] Seed = 6699321370314285901
[Parameters] Sampler = dpmpp_2m_sde_gpu - karras
[Parameters] Steps = 30 - 15
[Fooocus] Initializing ...
[Fooocus] Loading models ...
Refiner unloaded.
[Fooocus] Processing prompts ...
[Fooocus] Preparing Fooocus text #1 ...
[Prompt Expansion] realistic portrait photo of beautiful woman in mid twenties with long straight platinum colored hair, scandinavian, influencer, light freckles, green eyes, no makeup, instagram, shiny colorful, elegant, highly detailed, pretty, aesthetic detail, bright colors, inspired, designed, intricate, innocent, vibrant, rich deep expressive artistic color, sparkling complex background
[Fooocus] Preparing Fooocus text #2 ...
[Prompt Expansion] realistic portrait of a man dressed in construction clothes
[Fooocus] Encoding positive #1 ...
[Fooocus] Encoding positive #2 ...
[Fooocus] Encoding negative #1 ...
[Fooocus] Encoding negative #2 ...
[Parameters] Denoising Strength = 1.0
[Parameters] Initial Latent shape: Image Space (1024, 1024)
Preparation time: 18.96 seconds
[Sampler] refiner_swap_method = joint
[Sampler] sigma_min = 0.0291671771556139, sigma_max = 14.614643096923828
Traceback (most recent call last):
  File "C:\Users\nicka\AI\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\nicka\AI\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\nicka\AI\Fooocus\modules\default_pipeline.py", line 354, in process_diffusion
    modules.patch.BrownianTreeNoiseSamplerPatched.global_init(
  File "C:\Users\nicka\AI\Fooocus\modules\patch.py", line 173, in global_init
    BrownianTreeNoiseSamplerPatched.tree = BatchedBrownianTree(x, t0, t1, seed, cpu=cpu)
  File "C:\Users\nicka\AI\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in __init__
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "C:\Users\nicka\AI\Fooocus\backend\headless\fcbh\k_diffusion\sampling.py", line 85, in <listcomp>
    self.trees = [torchsde.BrownianTree(t0, w0, t1, entropy=s, **kwargs) for s in seed]
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torchsde\_brownian\derived.py", line 155, in __init__
    self._interval = brownian_interval.BrownianInterval(t0=t0,
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 540, in __init__
    W = self._randn(initial_W_seed) * math.sqrt(t1 - t0)
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 234, in _randn
    return _randn(size, self._top._dtype, self._top._device, seed)
  File "C:\Users\nicka\AI\python_embeded\lib\site-packages\torchsde\_brownian\brownian_interval.py", line 32, in _randn
    generator = torch.Generator(device).manual_seed(int(seed))
RuntimeError: Device type privateuseone is not supported for torch.Generator() api.
Total time: 19.03 seconds`

**Comment by jhoyocartes** [comment]
Same on RX580 8gb too

**Comment by quoije** [comment]
Same issue with AMD 6700XT.

**Comment by Crunch91** [comment]
Same here.
My specs:

6700 XT (12gb)
16GB RAM
24576 MB swap file
SSD
Windows

**Comment by ptrkrnstnr** [comment]
same here... 
7900xtx (24GB), 7800x3d, 32 GB RAM, 26624 MB swapfile, SSD, Windows 10

**Comment by TobiWan-Kenobi** [comment]
Same issue here with Intel(R) UHD Graphics GPU ... Will I have any chance of running this with this kind of GPU at all? (Windows 11)

**Comment by OdinM13** [comment]
I have the same issue while having 32gb ram and radeon rx6800xt. The strange thing is, that it worked properly before. For a few days I could generate as many pictures as I desired with all kinds of different settings, but now this is no longer possbile and I don't know why

**Comment by ptrkrnstnr** [comment]
I have a solution: go back to version 2.1.851, modify the "run.bat" to disable all updates like so: 

`:: .\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y
:: .\python_embeded\python.exe -m pip install torch-directml
.\python_embeded\python.exe -s Fooocus\launch.py --directml
pause`

you can download the files of v 2.1.851 by selecting the right branch and just copy the files over a fresh installation.

**Comment by lgwjames** [comment]
> I have a solution: go back to version 2.1.851, modify the "run.bat" to disable all updates like so:
> 
> `:: .\python_embeded\python.exe -m pip uninstall torch torchvision torchaudio torchtext functorch xformers -y :: .\python_embeded\python.exe -m pip install torch-directml .\python_embeded\python.exe -s Fooocus\launch.py --directml pause`
> 
> you can download the files of v 2.1.851 by selecting the right branch and just copy the files over a fresh installation.

Tried this today as installed on bootcamp with rx580 8gb

get this

Traceback (most recent call last):
  File "C:\Program Files\Fooocus\Fooocus\modules\async_worker.py", line 803, in worker
    handler(task)
  File "C:\Program Files\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Fooocus\Fooocus\modules\async_worker.py", line 735, in handler
    imgs = pipeline.process_diffusion(
  File "C:\Program Files\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Fooocus\Fooocus\modules\default_pipeline.py", line 361, in process_diffusion
    sampled_latent = core.ksampler(
  File "C:\Program Files\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Fooocus\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Fooocus\Fooocus\modules\core.py", line 313, in ksampler
    samples = ldm_patched.modules.sample.sample(model,
  File "C:\Program Files\Fooocus\Fooocus\ldm_patched\modules\sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
  File "C:\Program Files\Fooocus\Fooocus\ldm_patched\modules\sample.py", line 86, in prepare_sampling
    ldm_patched.modules.model_management.load_models_gpu([model] + models, model.memory_required([noise_shape[0] * 2] + list(noise_shape[1:])) + inference_memory)
  File "C:\Program Files\Fooocus\Fooocus\modules\patch.py", line 441, in patched_load_models_gpu
    y = ldm_patched.modules.model_management.load_models_gpu_origin(*args, **kwargs)
  File "C:\Program Files\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 414, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
  File "C:\Program Files\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 297, in model_load
    raise e
  File "C:\Program Files\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 293, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
  File "C:\Program Files\Fooocus\Fooocus\ldm_patched\modules\model_patcher.py", line 198, in patch_model
    temp_weight = ldm_patched.modules.model_management.cast_to_device(weight, device_to, torch.float32, copy=True)
  File "C:\Program Files\Fooocus\Fooocus\ldm_patched\modules\model_management.py", line 587, in cast_to_device
    return tensor.to(device, copy=copy, non_blocking=non_blocking).to(dtype, non_blocking=non_blocking)
RuntimeError: Could not allocate tensor with 52428800 bytes. There is not enough GPU video memory available!
Total time: 13.93 seconds

**Comment by patientx** [comment]
strangely while I am not getting any memory errors (8 GB 6600) my friend does , (16 GB 6800XT). Both of us also have fast nvme drives as swap drives. And 16 GB system memory.

**Comment by Lysuwel** [comment]
It maybe use memory,not GPU's memory，I had add some ‘Virtual memory’,and then  it's work!

**Comment by Lysuwel** [comment]
> Same here. My specs:
> 
> 6700 XT (12gb) 16GB RAM 24576 MB swap file SSD Windows
> 
> ```
> DML allocator out of memory!
> ```

try to add some cpu memory，you can add some Virtual memory  to retry.

**Comment by gasperpb** [comment]
python main.py --directml --use-split-cross-attention --lowvram
