### ISSUE TITLE
ImportError: cannot import name 'amp' from partially initialized module 'torch.cuda' (most likely due to a circular import)

### ISSUE THREAD

**Issue by wubbalubsbadubdub** [lllyasviel/Fooocus#842]
When I launch Run.bat I get this error.

Traceback (most recent call last):
  File "C:\Users\j1noo\Desktop\AI Art Generator\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\Users\j1noo\Desktop\AI Art Generator\Fooocus\launch.py", line 86, in <module>
    download_models()
  File "C:\Users\j1noo\Desktop\AI Art Generator\Fooocus\launch.py", line 61, in download_models
    load_file_from_url(url=url, model_dir=modelfile_path, file_name=file_name)
  File "C:\Users\j1noo\Desktop\AI Art Generator\Fooocus\modules\model_loader.py", line 24, in load_file_from_url
    from torch.hub import download_url_to_file
  File "C:\Users\j1noo\Desktop\AI Art Generator\python_embeded\lib\site-packages\torch\__init__.py", line 1332, in <module>
    _C._initExtension(manager_path())
  File "C:\Users\j1noo\Desktop\AI Art Generator\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 1275, in <module>
    from . import amp, jiterator, nvtx, profiler, sparse
ImportError: cannot import name 'amp' from partially initialized module 'torch.cuda' (most likely due to a circular import) (C:\Users\j1noo\Desktop\AI Art Generator\python_embeded\lib\site-packages\torch\cuda\__init__.py)

**Comment by wubbalubsbadubdub** [comment]
Please help. I am a noob when it comes to figuring out how to fix this kind of stuff.
