### ISSUE TITLE
Traceback problem loading

### ISSUE THREAD

**Issue by AFOLcast** [lllyasviel/Fooocus#868]
SImply, after closing and restarting Fooocus and my MSI Creator 15, I get start up errors.

D:\Foocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py
Already up-to-date
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.777
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 705, in readinto
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Foocus\python_embeded\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\Foocus\python_embeded\lib\site-packages\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Foocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "D:\Foocus\Fooocus\launch.py", line 88, in <module>
    from webui import *
  File "D:\Foocus\Fooocus\webui.py", line 396, in <module>
    shared.gradio_root.launch(
  File "D:\Foocus\python_embeded\lib\site-packages\gradio\blocks.py", line 1968, in launch
    and not networking.url_ok(self.local_url)
  File "D:\Foocus\python_embeded\lib\site-packages\gradio\networking.py", line 202, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "D:\Foocus\python_embeded\lib\site-packages\requests\api.py", line 100, in head
    return request("head", url, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Foocus\python_embeded\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

**Comment by lllyasviel** [comment]
https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md

**Comment by Echostorm44** [comment]
This happened to me.  It seems to stem from something else running on the same port.  Add -- port 12355 (or whatever number you like) to your run.bat

Like this:
.\python_embeded\python.exe -s Fooocus\entry_with_update.py --port 12355
