### ISSUE TITLE
getting stucked at"Initializing ..."

### ISSUE THREAD

**Issue by moosescap** [lllyasviel/Fooocus#885]
It jjust stuck at the "Initializing..." step with a spinning circle, and it never progresses. The console displays that the driver version is too low, but since I am using a P40 graphics card, I cannot upgrade the version any further. Is there a solution for this, or does it mean I can't use FOOOCUS? Thank you very much.

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Fooocus_win64_2-1-754\Fooocus\modules\async_worker.py", line 20, in worker
    import modules.default_pipeline as pipeline
  File "E:\Fooocus_win64_2-1-754\Fooocus\modules\default_pipeline.py", line 1, in <module>
    import modules.core as core
  File "E:\Fooocus_win64_2-1-754\Fooocus\modules\core.py", line 1, in <module>
    from modules.patch import patch_all
  File "E:\Fooocus_win64_2-1-754\Fooocus\modules\patch.py", line 5, in <module>
    import fcbh.model_base
  File "E:\Fooocus_win64_2-1-754\Fooocus\backend\headless\fcbh\model_base.py", line 2, in <module>
    from fcbh.ldm.modules.diffusionmodules.openaimodel import UNetModel
  File "E:\Fooocus_win64_2-1-754\Fooocus\backend\headless\fcbh\ldm\modules\diffusionmodules\openaimodel.py", line 16, in <module>
    from ..attention import SpatialTransformer
  File "E:\Fooocus_win64_2-1-754\Fooocus\backend\headless\fcbh\ldm\modules\attention.py", line 10, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "E:\Fooocus_win64_2-1-754\Fooocus\backend\headless\fcbh\ldm\modules\sub_quadratic_attention.py", line 27, in <module>
    from fcbh import model_management
  File "E:\Fooocus_win64_2-1-754\Fooocus\backend\headless\fcbh\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "E:\Fooocus_win64_2-1-754\Fooocus\backend\headless\fcbh\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "E:\Fooocus_win64_2-1-754\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "E:\Fooocus_win64_2-1-754\python_embeded\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by lanma** [comment]
I got the same error message. My Nvidia driver version is 11080. I run the A1111 webui successfully in the same environment.

**Comment by mashb1t** [comment]
There sadly isn't a solution, you have to upgrade your driver in order to be able to use Fooocus. Sorry.
See also https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md
